import { expect, test } from "../browserTest"
import { owner, say } from "./j1-fixtures"

// UI projection of .specs/engineering/checks/C-J8-03.md.
// Written before implementation: mvp.md §6.11 Obsidian, J8; lands with T-FLW-12
test("C-J8-03: owner configures two-way Obsidian sync and members cannot", async ({ page }) => {
  test.fixme(true, "Written before implementation: mvp.md §6.11 Obsidian, J8; lands with T-FLW-12")
// Seed retry.md and an owner branch terminal on the install Mac, with ~/Vault empty.
// Disk bytes, attachments and frontmatter need the reference-host folder receipts.
  await owner(page)
  await page.goto('/smithers-mvp-canary/node')
  await say(page, '/settings')
  await page.getByLabel(/Obsidian.*folder|Vault folder/i).fill('~/Vault')
  await page.getByLabel(/Obsidian.*folder|Vault folder/i).locator('xpath=ancestor::form').getByRole('button', { name: 'Change', exact: true }).press('Enter')
  await say(page, '/branch main')
  await page.getByRole('button', { name: 'Terminal', exact: true }).last().press('Enter')
  const terminal = page.getByRole('region', { name: /output/ }).last()
  await terminal.locator('.xterm-helper-textarea').focus()
  await page.keyboard.type("cat ~/Vault/decisions/retry.md")
  await page.keyboard.press('Enter')
  await expect(terminal).toContainText('---')
  await page.keyboard.type("printf '\nDisk retry decision\n' >> ~/Vault/decisions/retry.md")
  await page.keyboard.press('Enter')
  await say(page, '/wiki.page decisions/retry')
  await expect(page.getByText('Disk retry decision', { exact: true }).last()).toBeVisible()
  await expect(page.getByTitle('r2 by canary-owner', { exact: true }).last()).toBeVisible()
  const document = page.getByRole('textbox', { name: /Retry/ }).last()
  await document.press('Control+End')
  await page.keyboard.type(' App retry decision')
  await expect(page.getByText('Saving…', { exact: true })).toHaveCount(0)
  await say(page, '/branch main')
  await page.getByRole('button', { name: 'Terminal', exact: true }).last().press('Enter')
  await terminal.locator('.xterm-helper-textarea').focus()
  await page.keyboard.type('cat ~/Vault/decisions/retry.md')
  await page.keyboard.press('Enter')
  await expect(terminal).toContainText('App retry decision')
  await say(page, '/settings')
  await page.getByLabel(/Obsidian.*folder|Vault folder/i).fill('~/.smithers')
  await page.getByLabel(/Obsidian.*folder|Vault folder/i).locator('xpath=ancestor::form').getByRole('button', { name: 'Change', exact: true }).press('Enter')
  await expect(page.getByRole('alert').last()).toContainText(/state directory/i)
  await page.route('**/api/user', route => route.fulfill({ json: { id: 2, username: 'alice', is_admin: false } }))
  await page.reload()
  await say(page, '/settings')
  await expect(page.getByLabel(/Obsidian.*folder|Vault folder/i)).toHaveCount(0)
})
