import { expect, test } from "../browserTest"
import { owner, say } from "./j1-fixtures"

// UI projection of .specs/engineering/checks/C-UI-02.md.
// Integration and reference-host evidence remains required separately.
// Written before implementation: mvp.md §3, §9; lands with T-CAT-01
test("C-UI-02: Product words and minimal text: a deterministic copy lint", async ({ page }) => {
  test.fixme(true, "Written before implementation: mvp.md §3, §9; lands with T-CAT-01")
  // Required seed: every View fixture, including maximized states. The unit
  // check owns boundary fixtures; here the same chrome is read in the browser.
  await owner(page)
  await page.goto("/")
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 1000 })
    for (const scheme of ["light", "dark"] as const) {
      await page.emulateMedia({ colorScheme: scheme })
      for (const line of ["/home", "/settings", "/todo T8", "/branch retry-webhooks", "/help"]) {
        await say(page, line)
        const card = page.locator(".smithers-card").last()
        await expect(card).toBeVisible()
        const chrome = await card.locator("button, label, h1, h2, h3, dt").allTextContents()
        for (const text of chrome) {
          expect(text).not.toMatch(/\b(?:workflows?|threads?|tasks?|lanes?|boxes?|workspaces?|mythical|sandboxes?|VMs?|seats?|profiles?|Jev|forges?|microVM)\b/i)
          expect(text).not.toMatch(/not (?:yet )?measured|generated by|powered by|provided by|data from|source:/i)
          expect(text.trim().split(/\s+/).length).toBeLessThanOrEqual(12)
          expect(text).not.toMatch(/[.!?]\s+[A-Za-z]/)
        }
      }
      await say(page, "/settings")
      await expect(page.locator(".smithers-card").last()).toContainText("This Mac")
    }
  }
})
