/** Generated from Appendix C by scripts/generate-inspect-labels.mjs; do not edit. */
export const INSPECT_LABELS: Readonly<Record<string, string>> = {
  "agent/capacity/<seat>/cool/<n>": "Waiting for a model",
  "agent/opening-instructions": "Inspect: \"Read the instructions\"",
  "agent/opening-memory": "Inspect: \"Loaded context\"",
  "agent/route-seat": "Inspect: \"Chose a model\"",
  "agent/run": "Inspect: \"Worked a turn\"",
  "apply_patch": "An attributed edit in the File and Diff cards",
  "ask": "Needs you",
  "bash": "Terminal card (agent session). Missing: no terminal today",
  "checks/lint": "Linted the change",
  "checks/review": "Reviewed the change",
  "checks/security": "Reviewed security",
  "checks/wiki": "Checked the wiki",
  "coding/admit-retained-source": "Opened the source",
  "coding/admit-verify-source": "Opened the candidate",
  "coding/AdmitVibe": "Opened the change for landing",
  "coding/ApplyNative": "Applied the changes",
  "coding/assess": "Assessed the change",
  "coding/audit-security": "Audited security",
  "coding/begin-correction": "Started a fix round",
  "coding/capture-poc-source": "Captured the source",
  "coding/capture-review-check": "Captured the change",
  "coding/capture-wiki-check": "Captured the wiki",
  "coding/check": "Ran checks",
  "coding/check-command": "Ran checks",
  "coding/check-jev-rules": "Checked rules",
  "coding/CleanVibeHistory": "Tidied the history",
  "coding/CommandCheck": "Ran checks",
  "coding/configure-planning-wiki": "Chose wiki pages",
  "coding/confirm-final-description": "Confirmed the commit message",
  "coding/CoordinateRequest": "Worked the TODO",
  "coding/CorrectionRound": "Fixed review findings",
  "coding/CorrectPlan": "Fixed review findings",
  "coding/create-stack-base": "Created the stack base",
  "coding/create-vibe-landing": "Added to the stack",
  "coding/decline-request": "Declined the request",
  "coding/DescribeFinalAtom": "Wrote the commit message",
  "coding/Dispatch": "Ran an agent turn",
  "coding/dispatch-turn": "Worked a turn",
  "coding/draft-plan": "Drafted the plan",
  "coding/draft-poc": "Drafted a prototype",
  "coding/edit-atom": "Edited the files",
  "coding/fast-forward-vibe": "Moved the branch forward",
  "coding/fast-gate": "Ran quick checks",
  "coding/fence-vibe-source": "Pinned the change",
  "coding/finalize-plan": "Finalized the plan",
  "coding/find-planning-wiki-review": "Found wiki notes",
  "coding/finish-correction": "Finished the fix round",
  "coding/finish-final-history": "Finished the history",
  "coding/finish-review-check": "Collected review findings",
  "coding/finish-wiki-check": "Checked the wiki",
  "coding/gather-planning-context": "Gathered context",
  "coding/implement-change": "Implemented the change",
  "coding/ImplementAtom": "Implemented one step",
  "coding/ImplementAtoms": "Implemented the plan",
  "coding/ImplementPlan": "Implemented the plan",
  "coding/import-dependency-docs": "Imported dependency docs",
  "coding/install-dependency-pages": "Added dependency pages",
  "coding/JevCheck": "Checked rules",
  "coding/LandVibe": "Landed the change",
  "coding/materialize-poc": "Applied the prototype",
  "coding/merge-request-feedback": "Took in your steer",
  "coding/merge-vibe-local-pull": "Merged the change",
  "coding/observe-atom": "Saved the edit",
  "coding/observe-dispatch": "Saved the turn",
  "coding/observe-vibe-append": "Added to the stack",
  "coding/observe-vibe-pull-checks": "Watched PR checks",
  "coding/ObservePlan": "Tracked progress",
  "coding/open-vibe-local-pull": "Opened the pull request",
  "coding/open-vibe-pull": "Opened the pull request",
  "coding/Poc": "Drafted a prototype",
  "coding/prepare-atom": "Opened the working copy",
  "coding/prepare-atom-mutation": "Prepared to edit",
  "coding/prepare-final-description": "Drafted the commit message",
  "coding/prepare-owner-repair": "Prepared the repair",
  "coding/prepare-repair-context": "Gathered repair context",
  "coding/prepare-return-mythical-tip": "Returned to the stack tip",
  "coding/prepare-stack-base": "Prepared the stack",
  "coding/prepare-vibe-append": "Prepared to add to the stack",
  "coding/prepare-vibe-candidate": "Prepared the change",
  "coding/PreparePlan": "Planned the change",
  "coding/PrepareRequest": "Prepared the request",
  "coding/ProposeFinalHistory": "Reviewed the history",
  "coding/Prototype": "Drafted a prototype",
  "coding/publish-vibe-source": "Published the change",
  "coding/PublishVibeSource": "Published the change",
  "coding/queue-vibe-append": "Queued for the stack",
  "coding/read-correction-history": "Read earlier fixes",
  "coding/read-feedback-cancellation": "Read your steer",
  "coding/read-published-wiki": "Read the wiki",
  "coding/read-vibe-delivery": "Read delivery status",
  "coding/read-vibe-lander": "Read landing state",
  "coding/read-vibe-request": "Read the request",
  "coding/read-vibe-stack": "Read the stack",
  "coding/ReadNative": "Read the changes",
  "coding/receive-request-feedback": "Waited for your steer",
  "coding/RecheckCorrected": "Re-checked the fix",
  "coding/RecheckFinalHistory": "Re-checked the history",
  "coding/record-fast-gated-progress": "Recorded progress",
  "coding/record-learning": "Saved a lesson",
  "coding/record-slow-feedback": "Recorded feedback",
  "coding/refresh-final-history": "Refreshed the history",
  "coding/refresh-planning-wiki": "Refreshed wiki pages",
  "coding/refresh-restacked-evidence": "Refreshed evidence",
  "coding/RefreshWiki": "Refreshed wiki pages",
  "coding/refuse-plan-approval": "Refused a plan approval",
  "coding/repair-final-history": "Corrected the history",
  "coding/RepairPass": "Repaired the change",
  "coding/retain-poc": "Saved the prototype",
  "coding/review-final-history": "Reviewed the history",
  "coding/review-lens": "Reviewed through one lens",
  "coding/review-poc": "Reviewed the prototype",
  "coding/review-request": "Reviewed the request",
  "coding/review-security": "Reviewed security",
  "coding/ReviewCapturedChange": "Reviewed the change",
  "coding/ReviewCapturedWiki": "Checked the wiki",
  "coding/ReviewCheck": "Reviewed the change",
  "coding/RewriteFinalHistory": "Tidied the history",
  "coding/run-correction-round": "Fixed review findings",
  "coding/SecurityAudit": "Audited security",
  "coding/SecurityReviewCheck": "Reviewed security",
  "coding/select-owner-repair": "Chose what to fix",
  "coding/submit-vibe-lane": "Queued the change",
  "coding/validate-final-history": "Checked the history",
  "coding/validate-plan": "Checked the plan",
  "coding/verify-planning-context": "Checked the context",
  "coding/verify-vibe-landed": "Confirmed it landed",
  "coding/VerifyVibe": "Verified before landing",
  "coding/Wiki": "Refreshed the wiki",
  "coding/WikiCheck": "Checked the wiki",
  "create-flow": "Created a flow",
  "create-flow/clarify": "Asked what the flow should do",
  "create-flow/design": "Designed the flow",
  "create-flow/document": "Documented the flow",
  "create-flow/fix": "Fixed the flow",
  "create-flow/provision": "Set up the flow",
  "create-flow/scaffold": "Wrote the flow",
  "edit": "An attributed edit in the File and Diff cards",
  "factory/route-todo": "Chose how to start",
  "factory/stamp-route": "Declined the TODO",
  "factory/Todo": "Routed the TODO",
  "glob": "A \"read\" line in branch activity, opening the File card",
  "grep": "A \"read\" line in branch activity, opening the File card",
  "jev": "Inspect only: \"Decided <question>\"",
  "ls": "A \"read\" line in branch activity, opening the File card",
  "memory": "The \"Context\" line and the preflight cell in Inspect",
  "memory/mine": "Saved lessons",
  "memory/mine/run": "Saved lessons",
  "read": "A \"read\" line in branch activity, opening the File card",
  "recall": "The \"Context\" line and the preflight cell in Inspect",
  "recall (namespaced)": "The \"Context\" line and the preflight cell in Inspect",
  "remember": "Learning receipt",
  "review": "Reviewed the change",
  "smithers-review/ApplyVerdicts": "Settled findings",
  "smithers-review/FinalizeReview": "Finished the review",
  "smithers-review/MergeFileBatch": "Collected findings",
  "smithers-review/NarrateChanges": "Wrote the walkthrough",
  "smithers-review/NarrateReview": "Wrote the walkthrough",
  "smithers-review/PrepareReview": "Prepared the review",
  "smithers-review/RenderWalkthrough": "Rendered the walkthrough",
  "smithers-review/ReviewFile": "Reviewed one file",
  "smithers-review/ReviewFiles": "Reviewed the files",
  "smithers-review/VerifyFindings": "Verified findings",
  "smithers-review/VerifyReview": "Verified findings",
  "smithers/IncrementalWiki": "Refreshed the wiki",
  "smithers/Wiki": "Refreshed the wiki",
  "test": "Terminal card plus checks. Missing: needs SMITHERS_TEST_COMMAND",
  "wait": "Inspect: \"Waited\"",
  "wiki/assess-review": "Assessed a wiki page",
  "wiki/bind-review-provenance": "Linked a review to its source",
  "wiki/check-citations": "Checked citations",
  "wiki/collect-page": "Collected sources for a page",
  "wiki/load-recorded-reviews": "Found earlier reviews",
  "wiki/publish-recorded-reviews": "Saved wiki pages",
  "wiki/review-page": "Reviewed a wiki page",
  "wiki/select-recorded-review": "Reused a review",
  "wiki/validate-review": "Checked a wiki page",
  "wiki/write-snapshot": "Saved wiki pages",
  "write": "An attributed edit in the File and Diff cards"
}
