import { describe, expect, test } from "bun:test"
import "./views/testDom"
import { lintCopy, lintText } from "./productWords"

describe("C-UI-02 copy boundaries", () => {
  test.each(["workflow", "thread", "task", "lane", "box", "workspace", "mythical", "sandbox", "VM", "microVM", "seat", "profile", "Jev", "forge"])("bans %s and inflections in any case", word => {
    for (const suffix of ["", "s", "es"]) expect(lintText(`${word.toUpperCase()}${suffix}`)).toEqual([{ rule: "product-word", text: `${word.toUpperCase()}${suffix}` }])
  })
  test.each(["Taskbar", "sandboxed", "boxing", "seating", "profiled", "This Mac", "TODO T12", "No runs", "", " \n "])("accepts boundary %s", text => expect(lintText(text)).toEqual([]))
  test("counts words and sentences independently of wrapping", () => {
    expect(lintText("one two three four five six seven eight nine ten eleven twelve")).toEqual([])
    expect(lintText("one two three four five six seven eight nine ten eleven twelve thirteen").map(v => v.rule)).toEqual(["word-count"])
    expect(lintText("Done. Next").map(v => v.rule)).toEqual(["sentence-count"])
    expect(lintText("Done.\nNext")).toEqual(lintText("Done. Next"))
    expect(lintText("flow.ts")).toEqual([])
  })
  test("checks assistive copy and logical blocks while excluding supplied content", () => {
    const host = document.createElement("div")
    host.innerHTML = '<p>Open <b>thread</b></p><button aria-label="task" title="workspace">Run</button><input placeholder="box"><p data-content>workflow</p><div data-content><button>forge</button></div>'
    expect(lintCopy(host)).toEqual([
      { rule: "product-word", text: "thread" }, { rule: "product-word", text: "task" },
      { rule: "product-word", text: "workspace" }, { rule: "product-word", text: "box" }
    ])
    host.style.width = "100px"
    expect(lintCopy(host)).toHaveLength(4)
  })
  test("nested blocks do not duplicate violations", () => {
    const host = document.createElement("div")
    host.innerHTML = '<li><p>thread</p><button>task</button></li>'
    expect(lintCopy(host).map(v => v.text)).toEqual(["thread", "task"])
  })
  test.each(["Not measured", "Not yet measured", "Generated by Smithers", "Powered by Smithers", "Provided by Smithers", "Data from Smithers"])("rejects provenance %s", text => expect(lintText(text).map(v => v.rule)).toEqual(["provenance"]))
})
