/** Deterministic copy checks: logical DOM blocks, independent of layout. */
export interface CopyViolation {
  readonly rule: "product-word" | "word-count" | "sentence-count" | "provenance"
  readonly text: string
}
const internal = /\b(?:workflow|thread|task|lane|box|workspace|mythical|sandbox|vm|microvm|seat|profile|jev|forge)(?:s|es)?\b/giu
const provenance = /\b(?:not (?:yet )?measured|generated by|powered by|provided by|data from|source:)\b/iu

export const lintText = (text: string): ReadonlyArray<CopyViolation> => {
  const normalized = text.replace(/\s+/gu, " ").trim()
  if (!normalized) return []
  const violations: CopyViolation[] = []
  for (const match of normalized.matchAll(internal)) violations.push({ rule: "product-word", text: match[0] })
  if (normalized.split(" ").length > 12) violations.push({ rule: "word-count", text: normalized })
  if (/[.!?](?:["'”’)]*)\s+\p{L}/u.test(normalized)) violations.push({ rule: "sentence-count", text: normalized })
  if (provenance.test(normalized)) violations.push({ rule: "provenance", text: normalized })
  return violations
}

const blocks = "p,li,h1,h2,h3,h4,h5,h6,label,button,th,td,dt,dd,summary,div,span,time"
/** Repository/user content is excluded; accessible chrome attributes are checked too. */
export const lintCopy = (root: Element): ReadonlyArray<CopyViolation> => {
  const result: CopyViolation[] = []
  for (const element of [root, ...root.querySelectorAll("*")]) {
    if (element.closest("[data-content],style,script,template")) continue
    for (const attribute of ["aria-label", "title", "placeholder"]) {
      const text = element.getAttribute(attribute)
      if (text !== null) result.push(...lintText(text))
    }
    if (!element.matches(blocks) || (element.matches("span,time") && element.parentElement?.closest("p,button,h1,h2,h3,h4,h5,h6"))) continue
    // Nested logical blocks own their own copy; inline elements stay in this block.
    const copy = element.cloneNode(true) as Element
    for (const child of copy.querySelectorAll(`${blocks},[data-content],select,textarea,style,script,template`)) {
      if (child.matches("span,time") && element.matches("p,button,h1,h2,h3,h4,h5,h6")) continue
      child.remove()
    }
    result.push(...lintText(copy.textContent ?? ""))
  }
  return result
}
