// Code generated by go run ./packages/backend/modelprice/cmd/generate; DO NOT EDIT.
export type ModelPrice = { input: number; output: number; cacheRead: number; cacheWrite: number; cacheWrite1h: number; provider: string; context: string; longContextFrom?: number; longContext?: { input: number; output: number; cacheRead: number; cacheWrite: number; cacheWrite1h: number }; flatPerCall?: number; nextFrom?: string; next?: ModelPrice }
export const modelPrices: Record<string, ModelPrice> = {
  "claude-fable-5": {
    "input": 10,
    "output": 50,
    "cacheRead": 1,
    "cacheWrite": 12.5,
    "cacheWrite1h": 20,
    "provider": "anthropic",
    "context": "flat"
  },
  "claude-fable-5-1": {
    "input": 10,
    "output": 50,
    "cacheRead": 0.25,
    "cacheWrite": 12.5,
    "cacheWrite1h": 20,
    "provider": "anthropic",
    "context": "flat"
  },
  "claude-haiku-4-5": {
    "input": 1,
    "output": 5,
    "cacheRead": 0.1,
    "cacheWrite": 1.25,
    "cacheWrite1h": 2,
    "provider": "anthropic",
    "context": "flat"
  },
  "claude-opus-4-6": {
    "input": 5,
    "output": 25,
    "cacheRead": 0.5,
    "cacheWrite": 6.25,
    "cacheWrite1h": 10,
    "provider": "anthropic",
    "context": "flat"
  },
  "claude-opus-4-7": {
    "input": 5,
    "output": 25,
    "cacheRead": 0.5,
    "cacheWrite": 6.25,
    "cacheWrite1h": 10,
    "provider": "anthropic",
    "context": "flat"
  },
  "claude-opus-4-8": {
    "input": 5,
    "output": 25,
    "cacheRead": 0.5,
    "cacheWrite": 6.25,
    "cacheWrite1h": 10,
    "provider": "anthropic",
    "context": "flat"
  },
  "claude-opus-5": {
    "input": 5,
    "output": 25,
    "cacheRead": 0.5,
    "cacheWrite": 6.25,
    "cacheWrite1h": 10,
    "provider": "anthropic",
    "context": "flat"
  },
  "claude-opus-5-5": {
    "input": 4,
    "output": 20,
    "cacheRead": 0.2,
    "cacheWrite": 5,
    "cacheWrite1h": 8,
    "provider": "anthropic",
    "context": "flat"
  },
  "claude-sonnet-4-5": {
    "input": 3,
    "output": 15,
    "cacheRead": 0.3,
    "cacheWrite": 3.75,
    "cacheWrite1h": 6,
    "provider": "anthropic",
    "context": "tiered",
    "longContextFrom": 200000,
    "longContext": {
      "input": 6,
      "output": 22.5,
      "cacheRead": 0.6,
      "cacheWrite": 7.5,
      "cacheWrite1h": 12
    }
  },
  "claude-sonnet-4-6": {
    "input": 3,
    "output": 15,
    "cacheRead": 0.3,
    "cacheWrite": 3.75,
    "cacheWrite1h": 6,
    "provider": "anthropic",
    "context": "flat"
  },
  "claude-sonnet-5": {
    "input": 2,
    "output": 10,
    "cacheRead": 0.2,
    "cacheWrite": 2.5,
    "cacheWrite1h": 4,
    "provider": "anthropic",
    "context": "flat"
  },
  "gemini-3.8-flash": {
    "input": 0.75,
    "output": 3.75,
    "cacheRead": 0.075,
    "cacheWrite": 0.75,
    "cacheWrite1h": 0.75,
    "provider": "google",
    "context": "flat",
    "nextFrom": "2027-01-01T00:00:00Z",
    "next": {
      "input": 1.5,
      "output": 7.5,
      "cacheRead": 0.15,
      "cacheWrite": 1.5,
      "cacheWrite1h": 1.5,
      "provider": "google",
      "context": "flat"
    }
  },
  "gpt-4o": {
    "input": 2.5,
    "output": 10,
    "cacheRead": 1.25,
    "cacheWrite": 2.5,
    "cacheWrite1h": 2.5,
    "provider": "openai",
    "context": "flat"
  },
  "gpt-5.5": {
    "input": 5,
    "output": 30,
    "cacheRead": 0.5,
    "cacheWrite": 5,
    "cacheWrite1h": 5,
    "provider": "openai",
    "context": "tiered",
    "longContextFrom": 272000,
    "longContext": {
      "input": 10,
      "output": 45,
      "cacheRead": 1,
      "cacheWrite": 10,
      "cacheWrite1h": 10
    }
  },
  "gpt-5.6-luna": {
    "input": 0.2,
    "output": 1.2,
    "cacheRead": 0.02,
    "cacheWrite": 0.25,
    "cacheWrite1h": 0.25,
    "provider": "openai",
    "context": "tiered",
    "longContextFrom": 272000,
    "longContext": {
      "input": 0.4,
      "output": 1.8,
      "cacheRead": 0.04,
      "cacheWrite": 0.5,
      "cacheWrite1h": 0.5
    }
  },
  "gpt-5.6-sol": {
    "input": 4,
    "output": 20,
    "cacheRead": 0.4,
    "cacheWrite": 5,
    "cacheWrite1h": 5,
    "provider": "openai",
    "context": "tiered",
    "longContextFrom": 272000,
    "longContext": {
      "input": 8,
      "output": 30,
      "cacheRead": 0.8,
      "cacheWrite": 10,
      "cacheWrite1h": 10
    }
  },
  "gpt-5.6-terra": {
    "input": 2,
    "output": 12,
    "cacheRead": 0.2,
    "cacheWrite": 2.5,
    "cacheWrite1h": 2.5,
    "provider": "openai",
    "context": "tiered",
    "longContextFrom": 272000,
    "longContext": {
      "input": 4,
      "output": 18,
      "cacheRead": 0.4,
      "cacheWrite": 5,
      "cacheWrite1h": 5
    }
  },
  "gpt-6-astra": {
    "input": 10,
    "output": 50,
    "cacheRead": 1,
    "cacheWrite": 12.5,
    "cacheWrite1h": 12.5,
    "provider": "openai",
    "context": "tiered",
    "longContextFrom": 272000,
    "longContext": {
      "input": 20,
      "output": 75,
      "cacheRead": 2,
      "cacheWrite": 25,
      "cacheWrite1h": 25
    }
  },
  "gpt-6-luna": {
    "input": 0.1,
    "output": 0.5,
    "cacheRead": 0.01,
    "cacheWrite": 0.125,
    "cacheWrite1h": 0.125,
    "provider": "openai",
    "context": "tiered",
    "longContextFrom": 272000,
    "longContext": {
      "input": 0.2,
      "output": 0.75,
      "cacheRead": 0.02,
      "cacheWrite": 0.25,
      "cacheWrite1h": 0.25
    }
  },
  "gpt-6-sol": {
    "input": 2,
    "output": 10,
    "cacheRead": 0.2,
    "cacheWrite": 2.5,
    "cacheWrite1h": 2.5,
    "provider": "openai",
    "context": "tiered",
    "longContextFrom": 272000,
    "longContext": {
      "input": 4,
      "output": 15,
      "cacheRead": 0.4,
      "cacheWrite": 5,
      "cacheWrite1h": 5
    }
  },
  "gpt-oss-120b": {
    "input": 0.35,
    "output": 0.75,
    "cacheRead": 0.35,
    "cacheWrite": 0.35,
    "cacheWrite1h": 0.35,
    "provider": "cerebras",
    "context": "flat"
  },
  "gpt-oss-120b@openrouter": {
    "input": 0.35,
    "output": 0.75,
    "cacheRead": 0.35,
    "cacheWrite": 0.35,
    "cacheWrite1h": 0.35,
    "provider": "openrouter",
    "context": "flat"
  },
  "qwen-3.8-27b": {
    "input": 0.99,
    "output": 1.49,
    "cacheRead": 0.99,
    "cacheWrite": 0.99,
    "cacheWrite1h": 0.99,
    "provider": "cerebras",
    "context": "flat"
  },
  "typesafe-ai/jev": {
    "input": 0,
    "output": 0,
    "cacheRead": 0,
    "cacheWrite": 0,
    "cacheWrite1h": 0,
    "provider": "vercel",
    "context": "flat",
    "flatPerCall": 0.002
  }
}
