// Command generate writes the TypeScript view of modelprice.Table.
// Run: go run ./packages/backend/modelprice/cmd/generate
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/scanner"
	"time"

	"github.com/smithersai/smithers/packages/backend/modelprice"
)

type rate struct {
	Input        float64 `json:"input"`
	Output       float64 `json:"output"`
	CacheRead    float64 `json:"cacheRead"`
	CacheWrite   float64 `json:"cacheWrite"`
	CacheWrite1h float64 `json:"cacheWrite1h"`
}
type row struct {
	rate
	Provider        string `json:"provider"`
	Context         string `json:"context"`
	LongContextFrom int64  `json:"longContextFrom,omitempty"`
	LongContext     *rate  `json:"longContext,omitempty"`
	NextFrom        string `json:"nextFrom,omitempty"`
	Next            *row   `json:"next,omitempty"`
}

func rates(r modelprice.Rates) rate {
	return rate{float64(r.InputPerMTok) / 1e6, float64(r.OutputPerMTok) / 1e6, float64(r.CacheReadPerMTok) / 1e6, float64(r.CacheWritePerMTok) / 1e6, float64(r.CacheWrite1hPerMTok) / 1e6}
}
func convert(p modelprice.Price) row {
	c := "flat"
	if p.Context == modelprice.ContextTiered {
		c = "tiered"
	}
	v := row{rate: rates(p.Rates), Provider: p.Provider, Context: c, LongContextFrom: p.LongContextFrom}
	if p.Context == modelprice.ContextTiered {
		x := rates(p.LongContext)
		v.LongContext = &x
	}
	if p.Next != nil {
		x := convert(*p.Next)
		v.Next = &x
		v.NextFrom = p.NextFrom.Format(time.RFC3339)
	}
	return v
}

// header opens the generated module. The table is the one TypeScript copy of
// modelprice.Table; @smthrs/model's Pricing module, the eval scorecard and
// the review proxy all read it.
const header = `/**
 * Code generated by go run ./packages/backend/modelprice/cmd/generate; DO NOT EDIT.
 *
 * The backend rate card, packages/backend/modelprice/prices.go, in USD per
 * million tokens. cacheWrite is the 5-minute cache write; cacheWrite1h the
 * 1-hour one.
 *
 * @since 1.0.0-rc.1
 */

/**
 * One model's rate card.
 *
 * @category models
 * @since 1.0.0-rc.1
 */
export interface ModelPrice {
  readonly input: number
  readonly output: number
  readonly cacheRead: number
  readonly cacheWrite: number
  readonly cacheWrite1h: number
  readonly provider: string
  readonly context: string
  readonly longContextFrom?: number
  readonly longContext?: {
    readonly input: number
    readonly output: number
    readonly cacheRead: number
    readonly cacheWrite: number
    readonly cacheWrite1h: number
  }
  readonly nextFrom?: string
  readonly next?: ModelPrice
}

/**
 * Every model the backend prices, keyed by the model id sent on the wire.
 *
 * @category constants
 * @since 1.0.0-rc.1
 */
export const modelPrices: Readonly<Record<string, ModelPrice>> = `

func main() {
	check := flag.Bool("check", false, "fail if the generated table is stale")
	flag.Parse()
	rows := make(map[string]row, len(modelprice.Table))
	for id, p := range modelprice.Table {
		rows[id] = convert(p)
	}
	data, err := json.MarshalIndent(rows, "", "  ")
	if err != nil {
		panic(err)
	}
	var out bytes.Buffer
	out.WriteString(header)
	out.Write(data)
	out.WriteString("\n")
	path := filepath.Join("packages", "smithers", "agent", "model", "src", "internal", "prices.generated.ts")
	if *check {
		current, err := os.ReadFile(path)
		if err != nil || !bytes.Equal(current, out.Bytes()) {
			fmt.Fprintln(os.Stderr, "stale "+path+"; run go run ./packages/backend/modelprice/cmd/generate")
			os.Exit(1)
		}
		pricing := "packages/smithers/agent/model/src/Pricing.ts"
		consumers := []string{"evals/swebench/prices.ts"}
		for _, file := range append(consumers, pricing) {
			content, err := os.ReadFile(file)
			generated := importsValue(string(content), file, path, "modelPrices")
			public := file != pricing && importsValue(string(content), file, "@smthrs/model/Pricing", "table")
			if err != nil || !(generated || public) {
				fmt.Fprintln(os.Stderr, "consumer does not import generated prices: "+file)
				os.Exit(1)
			}
		}
		return
	}
	if err := os.WriteFile(path, out.Bytes(), 0644); err != nil {
		panic(err)
	}
}

// importsValue follows a runtime table import, including aliases and namespace
// imports. Tokenizing keeps comments, quoted examples and type-only imports
// from satisfying the provenance check.
func importsValue(source, file, module, binding string) bool {
	var scan scanner.Scanner
	scan.Init(strings.NewReader(source))
	scan.Mode = scanner.ScanIdents | scanner.ScanStrings | scanner.ScanChars | scanner.ScanRawStrings | scanner.ScanComments | scanner.SkipComments
	// TypeScript single-quoted module names are not Go character literals.
	scan.Error = func(*scanner.Scanner, string) {}
	type token struct {
		kind rune
		text string
	}
	var tokens []token
	for kind := scan.Scan(); kind != scanner.EOF; kind = scan.Scan() {
		tokens = append(tokens, token{kind, scan.TokenText()})
	}
	for i, tok := range tokens {
		if tok.kind != scanner.Ident || tok.text != "import" {
			continue
		}
		j := i + 1
		if j >= len(tokens) || tokens[j].text == "type" {
			continue
		}
		value := false
		if tokens[j].text == "*" {
			value = j+2 < len(tokens) && tokens[j+1].text == "as" && tokens[j+2].kind == scanner.Ident
			j += 3
		} else if tokens[j].text == "{" {
			j++
			for j < len(tokens) && tokens[j].text != "}" {
				// Each comma-separated named specifier begins with its
				// exported name, or with type for an erased import.
				if tokens[j].kind == scanner.Ident && tokens[j].text == binding {
					value = true
				}
				for j < len(tokens) && tokens[j].text != "," && tokens[j].text != "}" {
					j++
				}
				if j < len(tokens) && tokens[j].text == "," {
					j++
				}
			}
			j++
		}
		if !value || j+1 >= len(tokens) || tokens[j].text != "from" {
			continue
		}
		literal := tokens[j+1]
		if (literal.kind != scanner.String && literal.kind != scanner.Char) || len(literal.text) < 2 || literal.text[len(literal.text)-1] != literal.text[0] {
			continue
		}
		specifier := literal.text[1 : len(literal.text)-1]
		if strings.HasPrefix(specifier, ".") {
			specifier = filepath.ToSlash(filepath.Clean(filepath.Join(filepath.Dir(file), specifier)))
		}
		if specifier == filepath.ToSlash(module) {
			return true
		}
	}
	return false
}
