// Command generate writes the TypeScript view of modelprice.Table.
// Run: go run ./packages/backend/modelprice/cmd/generate
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/smithersai/smithers/packages/backend/modelprice"
)

type rate struct {
	Input      float64 `json:"input"`
	Output     float64 `json:"output"`
	CacheRead  float64 `json:"cacheRead"`
	CacheWrite float64 `json:"cacheWrite"`
}
type row struct {
	rate
	Provider        string  `json:"provider"`
	Context         string  `json:"context"`
	LongContextFrom int64   `json:"longContextFrom,omitempty"`
	LongContext     *rate   `json:"longContext,omitempty"`
	FlatPerCall     float64 `json:"flatPerCall,omitempty"`
	NextFrom        string  `json:"nextFrom,omitempty"`
	Next            *row    `json:"next,omitempty"`
}

func rates(r modelprice.Rates) rate {
	return rate{float64(r.InputPerMTok) / 1e6, float64(r.OutputPerMTok) / 1e6, float64(r.CacheReadPerMTok) / 1e6, float64(r.CacheWritePerMTok) / 1e6}
}
func convert(p modelprice.Price) row {
	c := "flat"
	if p.Context == modelprice.ContextTiered {
		c = "tiered"
	}
	v := row{rate: rates(p.Rates), Provider: p.Provider, Context: c, LongContextFrom: p.LongContextFrom, FlatPerCall: float64(p.FlatPerCall) / 1e6}
	if p.Context == modelprice.ContextTiered {
		x := rates(p.LongContext)
		v.LongContext = &x
	}
	if p.Next != nil {
		x := convert(*p.Next)
		v.Next = &x
		v.NextFrom = p.NextFrom.Format(time.RFC3339)
	}
	return v
}
func main() {
	check := flag.Bool("check", false, "fail if the generated table is stale")
	flag.Parse()
	rows := make(map[string]row, len(modelprice.Table))
	for id, p := range modelprice.Table {
		rows[id] = convert(p)
	}
	data, err := json.MarshalIndent(rows, "", "  ")
	if err != nil {
		panic(err)
	}
	var out bytes.Buffer
	out.WriteString("// Code generated by go run ./packages/backend/modelprice/cmd/generate; DO NOT EDIT.\n")
	out.WriteString("export type ModelPrice = { input: number; output: number; cacheRead: number; cacheWrite: number; provider: string; context: string; longContextFrom?: number; longContext?: { input: number; output: number; cacheRead: number; cacheWrite: number }; flatPerCall?: number; nextFrom?: string; next?: ModelPrice }\n")
	out.WriteString("export const modelPrices: Record<string, ModelPrice> = ")
	out.Write(data)
	out.WriteString("\n")
	path := filepath.Join("packages", "backend", "modelprice", "prices.generated.ts")
	if *check {
		current, err := os.ReadFile(path)
		if err != nil || !bytes.Equal(current, out.Bytes()) {
			fmt.Fprintln(os.Stderr, "stale "+path+"; run go run ./packages/backend/modelprice/cmd/generate")
			os.Exit(1)
		}
		for file, needle := range map[string]string{
			"evals/swebench/prices.ts":                    "prices.generated.ts",
			"apps/review/src/server/proxy/modelPrices.ts": "prices.generated.ts",
		} {
			content, err := os.ReadFile(file)
			if err != nil || !strings.Contains(string(content), needle) {
				fmt.Fprintln(os.Stderr, "consumer does not import generated prices: "+file)
				os.Exit(1)
			}
		}
		return
	}
	if err := os.WriteFile(path, out.Bytes(), 0644); err != nil {
		panic(err)
	}
}
