// Command generate writes the TypeScript view of modelprice.Table.
// Run: go run ./packages/backend/modelprice/cmd/generate
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/smithersai/smithers/packages/backend/modelprice"
)

type rate struct {
	Input        float64 `json:"input"`
	Output       float64 `json:"output"`
	CacheRead    float64 `json:"cacheRead"`
	CacheWrite   float64 `json:"cacheWrite"`
	CacheWrite1h float64 `json:"cacheWrite1h"`
}
type row struct {
	rate
	Provider        string  `json:"provider"`
	Context         string  `json:"context"`
	LongContextFrom int64   `json:"longContextFrom,omitempty"`
	LongContext     *rate   `json:"longContext,omitempty"`
	FlatPerCall     float64 `json:"flatPerCall,omitempty"`
	NextFrom        string  `json:"nextFrom,omitempty"`
	Next            *row    `json:"next,omitempty"`
}

func rates(r modelprice.Rates) rate {
	return rate{float64(r.InputPerMTok) / 1e6, float64(r.OutputPerMTok) / 1e6, float64(r.CacheReadPerMTok) / 1e6, float64(r.CacheWritePerMTok) / 1e6, float64(r.CacheWrite1hPerMTok) / 1e6}
}
func convert(p modelprice.Price) row {
	c := "flat"
	if p.Context == modelprice.ContextTiered {
		c = "tiered"
	}
	v := row{rate: rates(p.Rates), Provider: p.Provider, Context: c, LongContextFrom: p.LongContextFrom, FlatPerCall: float64(p.FlatPerCall) / 1e6}
	if p.Context == modelprice.ContextTiered {
		x := rates(p.LongContext)
		v.LongContext = &x
	}
	if p.Next != nil {
		x := convert(*p.Next)
		v.Next = &x
		v.NextFrom = p.NextFrom.Format(time.RFC3339)
	}
	return v
}
func main() {
	check := flag.Bool("check", false, "fail if the generated table is stale")
	flag.Parse()
	rows := make(map[string]row, len(modelprice.Table))
	for id, p := range modelprice.Table {
		rows[id] = convert(p)
	}
	data, err := json.MarshalIndent(rows, "", "  ")
	if err != nil {
		panic(err)
	}
	var out bytes.Buffer
	out.WriteString("// Code generated by go run ./packages/backend/modelprice/cmd/generate; DO NOT EDIT.\n")
	out.WriteString("export type ModelPrice = { input: number; output: number; cacheRead: number; cacheWrite: number; cacheWrite1h: number; provider: string; context: string; longContextFrom?: number; longContext?: { input: number; output: number; cacheRead: number; cacheWrite: number; cacheWrite1h: number }; flatPerCall?: number; nextFrom?: string; next?: ModelPrice }\n")
	out.WriteString("export const modelPrices: Record<string, ModelPrice> = ")
	out.Write(data)
	out.WriteString("\n")
	docPath := filepath.Join("apps", "site", "src", "content", "docs", "docs", "model-prices.mdx")
	var sheet bytes.Buffer
	sheet.WriteString("---\ntitle: \"Model prices\"\ndescription: \"Managed model credit rates per million tokens.\"\n---\n\n")
	sheet.WriteString("Source date: 2026-09-27. Generated from [the checked-in backend rate card](https://github.com/smithersai/smithers/blob/main/packages/backend/modelprice/prices.go); these are Smithers managed model credit rates, not live provider quotes. Token rates below are USD per million tokens; per-call charges are USD per call. Cache read is cached input; cache write is 5-minute prompt-cache writes; 1h cache write is 1-hour prompt-cache writes. A dash means no separate long-context tier.\n\n")
	sheet.WriteString("| Model | Input | Cached input | Cache write | 1h cache write | Output | Long context from (prompt tokens) | Long input | Long cached input | Long cache write | Long 1h cache write | Long output | Per call |\n| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n")
	ids := make([]string, 0, len(rows))
	for id := range rows {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		p := rows[id]
		longFrom, longIn, longRead, longWrite, longWrite1h, longOut := "-", "-", "-", "-", "-", "-"
		if p.LongContext != nil {
			longFrom = fmt.Sprint(p.LongContextFrom)
			longIn = fmt.Sprint(p.LongContext.Input)
			longRead = fmt.Sprint(p.LongContext.CacheRead)
			longWrite = fmt.Sprint(p.LongContext.CacheWrite)
			longWrite1h = fmt.Sprint(p.LongContext.CacheWrite1h)
			longOut = fmt.Sprint(p.LongContext.Output)
		}
		perCall := "-"
		if p.FlatPerCall != 0 {
			perCall = fmt.Sprint(p.FlatPerCall)
		}
		fmt.Fprintf(&sheet, "| %s | %g | %g | %g | %g | %g | %s | %s | %s | %s | %s | %s | %s |\n", id, p.Input, p.CacheRead, p.CacheWrite, p.CacheWrite1h, p.Output, longFrom, longIn, longRead, longWrite, longWrite1h, longOut, perCall)
	}
	sheet.WriteString("\nAt or above the long-context prompt threshold, the long rates apply to the whole call.\n")
	for _, id := range ids {
		p := rows[id]
		if p.Next == nil {
			continue
		}
		fmt.Fprintf(&sheet, "\n## %s from %s\n\nScheduled USD per million tokens: input %g, cached input %g, cache write %g, 1h cache write %g, output %g.\n", id, p.NextFrom, p.Next.Input, p.Next.CacheRead, p.Next.CacheWrite, p.Next.CacheWrite1h, p.Next.Output)
		if p.Next.LongContext != nil {
			fmt.Fprintf(&sheet, "From %d prompt tokens: input %g, cached input %g, cache write %g, 1h cache write %g, output %g.\n", p.Next.LongContextFrom, p.Next.LongContext.Input, p.Next.LongContext.CacheRead, p.Next.LongContext.CacheWrite, p.Next.LongContext.CacheWrite1h, p.Next.LongContext.Output)
		}
	}

	path := filepath.Join("packages", "backend", "modelprice", "prices.generated.ts")
	if *check {
		current, err := os.ReadFile(path)
		if err != nil || !bytes.Equal(current, out.Bytes()) {
			fmt.Fprintln(os.Stderr, "stale "+path+"; run go run ./packages/backend/modelprice/cmd/generate")
			os.Exit(1)
		}
		currentDoc, err := os.ReadFile(docPath)
		if err != nil || !bytes.Equal(currentDoc, sheet.Bytes()) {
			fmt.Fprintln(os.Stderr, "stale "+docPath+"; run go run ./packages/backend/modelprice/cmd/generate")
			os.Exit(1)
		}
		for file, needle := range map[string]string{
			"evals/swebench/prices.ts":                    "prices.generated.ts",
			"apps/review/src/server/proxy/modelPrices.ts": "prices.generated.ts",
		} {
			content, err := os.ReadFile(file)
			if err != nil || !strings.Contains(string(content), needle) {
				fmt.Fprintln(os.Stderr, "consumer does not import generated prices: "+file)
				os.Exit(1)
			}
		}
		return
	}
	if err := os.WriteFile(path, out.Bytes(), 0644); err != nil {
		panic(err)
	}
	if err := os.WriteFile(docPath, sheet.Bytes(), 0644); err != nil {
		panic(err)
	}
}
