/**
 * Builds `manifest.json`, the real-repository sample for #3150 phase 2. Rules (also in
 * docs/mvp/research/registration-scores.md section 5):
 *
 * - human: created before 2021-03-01, pinned at the last default-branch commit before 2022-06-01
 *   (no agent-assisted coding existed), and that commit is from 2021-11-01 or later so the churn
 *   window has history.
 * - agent: created from 2024-06-01, description says it was written, generated or built entirely by
 *   an AI or agent, pinned at the default branch head on the selection date.
 * - hybrid: created from 2024-01-01, 100 to 8000 stars, an agent adoption file at the repository
 *   root (AGENTS.md, CLAUDE.md, .cursorrules, .cursor, GEMINI.md, .claude), and no agent-only
 *   description; pinned at the head. Anything not clearly human-only or agent-only is hybrid.
 *
 * Candidates come from `gh search repos` (queries below), are shuffled with a seeded generator,
 * and are screened in that order: each is recorded (record.ts) and accepted into the first
 * language x measured-band cell with room; rejections are kept in the manifest with a reason.
 * Rerun: `node --experimental-strip-types flows/register-repository/calibration/select.ts`
 * (needs `gh` auth; results depend on live GitHub search, which is why the manifest pins SHAs).
 */
import { execFileSync } from "node:child_process"
import { appendFileSync, existsSync, readFileSync, writeFileSync } from "node:fs"
import { BANDS, LANGUAGES } from "./fit.ts"
import { type Band, type Label, type Language, type ManifestEntry, recordRepository } from "./record.ts"

export const QUOTA: Record<Label, number> = { human: 5, agent: 3, hybrid: 2 }
const GH_LANGUAGE: Record<Language, string> = { ts: "typescript", python: "python", go: "go", rust: "rust" }
const HUMAN_CREATED_BEFORE = "2021-03-01"
const HUMAN_PIN_BEFORE = "2022-06-01T00:00:00Z"
const HUMAN_PIN_AFTER = "2021-11-01T00:00:00Z"
const AGENT_QUERIES = [
  "written entirely by Claude",
  "100% AI-generated",
  "entirely AI-generated",
  "written by Claude Code",
  "built entirely by AI",
  "vibe coded",
  "generated by Codex",
  "written by AI agents",
  "built autonomously by AI agents"
]
const AGENT_DESCRIPTION =
  /(written|generated|built|coded|created|developed|authored|implemented|made)\s+(entirely|fully|completely|100%|mostly|largely|autonomously)?\s*(by|with|using)\s+(claude|codex|chatgpt|gpt|gemini|cursor|copilot|ai|an ai|llm|an llm)|100%\s*ai|entirely\s+(ai|by ai)|ai[- ]generated|vibe[- ]?coded (app|game|project|tool|version|port|clone)/i
const ADOPTION_ROOT = ["AGENTS.md", "CLAUDE.md", ".cursorrules", ".cursor", "GEMINI.md", ".claude"]
const SEED = 3150

interface Candidate {
  readonly repo: string
  readonly language: Language
  readonly label: Label
  readonly sha: string
  readonly proxy: Band
  readonly evidence: string
}

const gh = (args: ReadonlyArray<string>): any => {
  for (let attempt = 0; attempt < 5; attempt++) {
    try {
      return JSON.parse(execFileSync("gh", args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"], maxBuffer: 64 << 20 }))
    } catch (error) {
      const message = String((error as { stderr?: string }).stderr ?? error)
      if (/rate limit|abuse|secondary/i.test(message)) execFileSync("sleep", ["30"])
      else if (attempt === 4 || /Not Found|409|422|empty/i.test(message)) return undefined
      else execFileSync("sleep", ["3"])
    }
  }
  return undefined
}
const search = (query: ReadonlyArray<string>, limit: number) => {
  execFileSync("sleep", ["2.5"])
  return (gh(["search", "repos", ...query, "--limit", String(limit), "--json", "fullName,description,stargazersCount,createdAt,size,isFork,isArchived"]) ?? []) as ReadonlyArray<
    { fullName: string; description: string | null; stargazersCount: number; createdAt: string; size: number; isFork: boolean; isArchived: boolean }
  >
}
const proxyBand = (kilobytes: number): Band => kilobytes < 800 ? "small" : kilobytes < 8000 ? "medium" : "large"
const head = (repo: string) => {
  const commit = gh(["api", `repos/${repo}/commits?per_page=1`])
  return commit?.[0]?.sha as string | undefined
}

/** Seeded Fisher-Yates so the screening order is reproducible from the same candidate list. */
const shuffle = <T>(items: ReadonlyArray<T>): Array<T> => {
  let state = SEED
  const next = () => {
    state = (state + 0x6d2b79f5) | 0
    let t = Math.imul(state ^ (state >>> 15), 1 | state)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4_294_967_296
  }
  const copy = [...items]
  for (let index = copy.length - 1; index > 0; index--) {
    const other = Math.floor(next() * (index + 1))
    ;[copy[index], copy[other]] = [copy[other]!, copy[index]!]
  }
  return copy
}

const gather = (): ReadonlyArray<Candidate> => {
  const found = new Map<string, Candidate>()
  const seen = new Set<string>()
  for (const language of LANGUAGES) {
    const ghLanguage = GH_LANGUAGE[language]
    for (const range of ["50..200", "200..600", "600..2500", "2500..10000", "10000..40000"]) {
      for (const row of search([`language:${ghLanguage}`, `created:<${HUMAN_CREATED_BEFORE}`, `stars:${range}`, "--sort", "stars"], 40)) {
        if (row.isFork || seen.has(row.fullName) || row.size > 300_000) continue
        seen.add(row.fullName)
        const pin = gh(["api", `repos/${row.fullName}/commits?until=${HUMAN_PIN_BEFORE}&per_page=1`])?.[0]
        const date = pin?.commit?.committer?.date as string | undefined
        if (pin === undefined || date === undefined || date < HUMAN_PIN_AFTER) continue
        found.set(row.fullName, {
          repo: row.fullName, language, label: "human", sha: pin.sha, proxy: proxyBand(row.size),
          evidence: `created ${row.createdAt.slice(0, 10)}; pinned ${date.slice(0, 10)}, before agent-assisted coding`
        })
      }
    }
    for (const phrase of AGENT_QUERIES) {
      for (const sort of ["stars", "updated"]) {
        for (const row of search([`"${phrase}"`, `language:${ghLanguage}`, "--created", ">=2024-06-01", "--sort", sort], 30)) {
          const description = row.description ?? ""
          if (row.isFork || seen.has(row.fullName) || !AGENT_DESCRIPTION.test(description)) continue
          seen.add(row.fullName)
          const sha = head(row.fullName)
          if (sha === undefined) continue
          found.set(row.fullName, {
            repo: row.fullName, language, label: "agent", sha, proxy: proxyBand(row.size),
            evidence: `created ${row.createdAt.slice(0, 10)}; description: ${description.slice(0, 120)}`
          })
        }
      }
    }
    for (const range of ["100..400", "400..1500", "1500..8000"]) {
      for (const row of search([`language:${ghLanguage}`, "--created", ">=2024-01-01", `stars:${range}`, "--sort", "stars"], 40)) {
        if (row.isFork || seen.has(row.fullName) || AGENT_DESCRIPTION.test(row.description ?? "")) continue
        seen.add(row.fullName)
        const root = gh(["api", `repos/${row.fullName}/contents/`]) as ReadonlyArray<{ name: string }> | undefined
        const markers = (root ?? []).map((entry) => entry.name).filter((name) => ADOPTION_ROOT.includes(name))
        const sha = markers.length === 0 ? undefined : head(row.fullName)
        if (sha === undefined) continue
        found.set(row.fullName, {
          repo: row.fullName, language, label: "hybrid", sha, proxy: proxyBand(row.size),
          evidence: `created ${row.createdAt.slice(0, 10)}; ${row.stargazersCount} stars; root has ${markers.join(", ")}`
        })
      }
    }
  }
  return [...found.values()]
}

const CACHE = process.argv[2] ?? "candidates.json"
const OUT = new URL("manifest.json", import.meta.url)
const WORK = process.argv[3] ?? "."
/** One JSON line per screened repository, so an interrupted run resumes where it stopped. */
const PROGRESS = process.argv[4] ?? "progress.jsonl"

const main = async () => {
  const candidates: ReadonlyArray<Candidate> = existsSync(CACHE)
    ? JSON.parse(readFileSync(CACHE, "utf8"))
    : (() => {
      const all = gather()
      writeFileSync(CACHE, JSON.stringify(all, null, 1))
      return all
    })()
  const cell = (language: string, band: string, label: string) => `${language}/${band}/${label}`
  const accepted = new Map<string, ManifestEntry>(), counts = new Map<string, number>()
  const rejected: Array<{ repo: string; label: Label; reason: string }> = []
  const queues = new Map<string, Array<Candidate>>()
  for (const candidate of shuffle(candidates)) {
    const key = cell(candidate.language, candidate.proxy, candidate.label)
    queues.set(key, [...(queues.get(key) ?? []), candidate])
  }
  const replayed = new Set<string>()
  if (existsSync(PROGRESS)) {
    for (const line of readFileSync(PROGRESS, "utf8").split("\n").filter((value) => value !== "")) {
      const saved = JSON.parse(line) as { repo: string; entry?: ManifestEntry; reason?: string; label: Label }
      replayed.add(saved.repo)
      if (saved.entry !== undefined) {
        accepted.set(saved.repo, saved.entry)
        const key = cell(saved.entry.language, saved.entry.band, saved.entry.label)
        counts.set(key, (counts.get(key) ?? 0) + 1)
      } else rejected.push({ repo: saved.repo, label: saved.label, reason: saved.reason! })
    }
    for (const [key, list] of queues) queues.set(key, list.filter((candidate) => !replayed.has(candidate.repo)))
  }
  const save = (value: object) => appendFileSync(PROGRESS, JSON.stringify(value) + "\n")
  const inflight = new Map<string, number>()
  const room = (key: string) => (counts.get(key) ?? 0) + (inflight.get(key) ?? 0) < QUOTA[key.split("/")[2] as Label]
  const worker = async () => {
    for (;;) {
      const key = [...queues.keys()].find((name) => queues.get(name)!.length > 0 && room(name))
      if (key === undefined) {
        if ([...inflight.values()].some((count) => count > 0)) {
          await new Promise((resolve) => setTimeout(resolve, 2000))
          continue
        }
        return
      }
      const candidate = queues.get(key)!.shift()!
      inflight.set(key, (inflight.get(key) ?? 0) + 1)
      const result = await recordRepository({ id: "screen", ...candidate, band: candidate.proxy }, WORK)
      inflight.set(key, inflight.get(key)! - 1)
      if (!result.ok) {
        rejected.push({ repo: candidate.repo, label: candidate.label, reason: result.reason })
        save(rejected.at(-1)!)
        continue
      }
      const { recorded, measuredLanguage } = result
      const measuredKey = cell(candidate.language, recorded.band, candidate.label)
      if (measuredLanguage !== candidate.language) {
        rejected.push({ repo: candidate.repo, label: candidate.label, reason: `dominant source language ${measuredLanguage}` })
        save(rejected.at(-1)!)
      } else if ((counts.get(measuredKey) ?? 0) >= QUOTA[candidate.label]) {
        rejected.push({ repo: candidate.repo, label: candidate.label, reason: `${recorded.band} cell full` })
        save(rejected.at(-1)!)
      } else {
        counts.set(measuredKey, (counts.get(measuredKey) ?? 0) + 1)
        const index = String(counts.get(measuredKey)!).padStart(2, "0")
        const entry: ManifestEntry = {
          id: `${candidate.language}-${recorded.band}-${candidate.label}-${index}`,
          repo: candidate.repo, sha: candidate.sha, language: candidate.language, band: recorded.band,
          label: candidate.label, evidence: candidate.evidence
        }
        accepted.set(candidate.repo, entry)
        save({ repo: candidate.repo, label: candidate.label, entry })
      }
      console.error(`${accepted.size} accepted, ${rejected.length} rejected; last ${candidate.repo} ${recorded.band}`)
    }
  }
  await Promise.all(Array.from({ length: 5 }, worker))
  const entries = [...accepted.values()].sort((a, b) => a.id.localeCompare(b.id))
  const missing = LANGUAGES.flatMap((language) =>
    BANDS.flatMap((band) => (["human", "agent", "hybrid"] as const).map((label) => [cell(language, band, label), QUOTA[label] - (counts.get(cell(language, band, label)) ?? 0)] as const))
  ).filter(([, count]) => count > 0)
  writeFileSync(
    OUT,
    JSON.stringify({ selectedOn: new Date().toISOString().slice(0, 10), seed: SEED, quota: QUOTA, unfilled: Object.fromEntries(missing), entries, rejected }, null, 1) + "\n"
  )
  console.error(`wrote ${entries.length} entries; unfilled ${JSON.stringify(Object.fromEntries(missing))}`)
}
await main()
