package middleware

import (
	"net/http"
	"testing"

	"github.com/stretchr/testify/require"
)

// The member route table, by literal request: the app's install reads, the
// app agent, every TODO and Members route, and a repository's secret writes
// map to their command; anything else is the owner's alone.
func TestInstallMemberCommandRoutes(t *testing.T) {
	for _, tc := range []struct{ method, path, command string }{
		{http.MethodGet, "/api/user", "self"},
		{http.MethodGet, "/api/branches/main/files/src/b.ts", "branch.read"},
		{http.MethodGet, "/api/branches/main/files/.smithers/machine.json", "branch.read"},
		{http.MethodPost, "/api/auth/logout", "self"},
		{http.MethodGet, "/api/install", "install.read"},
		{http.MethodPost, "/api/reviews", "review"},
		{http.MethodGet, "/api/reviews", ""},
		{http.MethodGet, "/api/user/repos", "repo.read"},
		{http.MethodGet, "/api/repos/local-owner/demo/mythical", "repo.read"},
		{http.MethodGet, "/api/repos/local-owner/demo/mythical/events", "repo.read"},
		{http.MethodGet, "/api/repos/local-owner/demo/mythical/items/T3", "repo.read"},
		{http.MethodGet, "/api/github/sync", "sync.read"},
		{http.MethodPost, "/api/github/sync", "sync.retry"},
		{http.MethodGet, "/api/live", "live"},
		{http.MethodPost, "/api/agent/turn/replay", "agent.turn"},
		{http.MethodPost, "/api/agent/turn", "agent.turn"},
		{http.MethodGet, "/api/agent/conversations", "agent.turn"},
		{http.MethodGet, "/api/conversations/main", "agent.turn"},
		{http.MethodGet, "/api/conversations/scratch%2Fben%2Ffeature", "agent.turn"},
		{http.MethodPost, "/api/conversations/main/prompt", "agent.turn"},
		{http.MethodPost, "/api/conversations/scratch%2Fben%2Ffeature/prompt", "agent.turn"},
		{http.MethodGet, "/api/conversations/scratch%2Fben%2Ffeature/view-state", "agent.turn"},
		{http.MethodPut, "/api/conversations/scratch%2Fben%2Ffeature/view-state", "agent.turn"},
		{http.MethodPatch, "/api/conversations/scratch%2Fben%2Ffeature/turns/turn-1", "agent.turn"},
		{http.MethodDelete, "/api/conversations/scratch%2Fben%2Ffeature/turns/turn-1", "agent.turn"},
		{http.MethodPost, "/api/conversations/scratch%2Fben%2Ffeature/turns/turn-1/stop", "agent.turn"},
		{http.MethodPost, "/api/conversations/scratch/ben/feature/prompt", ""},
		{http.MethodGet, "/api/conversations/main/view-state", "agent.turn"},
		{http.MethodPost, "/api/conversations/main/turns/turn-1/stop", "agent.turn"},
		{http.MethodPatch, "/api/conversations/main/turns/turn-1", "agent.turn"},
		{http.MethodDelete, "/api/conversations/main/turns/turn-1", "agent.turn"},
		{http.MethodPatch, "/api/conversations/main/turns/turn-1/output", ""},
		{http.MethodPut, "/api/conversations/main/view-state", "agent.turn"},
		{http.MethodGet, "/api/conversations/main/view-state/ben", ""},
		{http.MethodPost, "/api/agent/conversations/replay", "agent.turn"},
		{http.MethodGet, "/api/user/orgs", "self.read"},
		{http.MethodGet, "/api/user/workspaces", "self.read"},
		{http.MethodPost, "/api/telemetry/errors", "telemetry.report"},
		{http.MethodGet, "/api/issues", "issue.read"},
		{http.MethodGet, "/api/issues/7", "issue.read"},
		{http.MethodGet, "/api/issues/7/comments", ""},
		{http.MethodPost, "/api/issues", ""},
		{http.MethodPost, "/api/todos/12", "todo.control"},
		{http.MethodPatch, "/api/todos/12", "todo.amend"},
		{http.MethodPatch, "/api/todos/T12", ""},
		{http.MethodPatch, "/api/todos/12/answer", ""},
		{http.MethodGet, "/api/todos", "todo.read"},
		{http.MethodGet, "/api/stack", "todo.read"},
		{http.MethodPost, "/api/stack", ""},
		{http.MethodGet, "/api/stack/12", ""},
		{http.MethodGet, "/api/todos/12", "todo.read"},
		{http.MethodPost, "/api/todos", "todo.new"},
		{http.MethodPost, "/api/todos/12/answer", "todo.answer"},
		{http.MethodPost, "/api/todos/12/merge", "merge"},
		{http.MethodGet, "/api/flows", "flows.read"},
		{http.MethodGet, "/api/branches/branch-id/files", "branch.read"},
		{http.MethodGet, "/api/branches/branch-id", "branch.read"},
		{http.MethodGet, "/api/branches/branch-id/diff", "branch.read"},
		{http.MethodPost, "/api/branches/branch-id/diff", ""},
		{http.MethodGet, "/api/branches", "branches.read"},
		{http.MethodGet, "/api/branches/branch-id/files/src/retry.ts", "branch.read"},
		{http.MethodPost, "/api/branches/branch-id/files/src/retry.ts", ""},
		{http.MethodGet, "/api/repos/acme/app/workspaces/branch-id/files/content", "branch.read"},
		{http.MethodPut, "/api/repos/acme/app/workspaces/branch-id/files/content", "branch.join"},
		{http.MethodPut, "/api/repos/acme/app/workspaces/branch-id/files", ""},
		{http.MethodPut, "/api/repos/acme/app/workspaces/branch-id/files/content/extra", ""},
		{http.MethodPost, "/api/flows", ""},
		{http.MethodGet, "/api/flows/todo", ""},
		{http.MethodPost, "/api/repos/owner/demo/workspaces", "branch.join"},
		{http.MethodPost, "/api/repos/owner/demo/workspaces/ws/fork", ""},
		{http.MethodGet, "/api/members", "members.list"},
		{http.MethodPost, "/api/members", "members.write"},
		{http.MethodPatch, "/api/members/alice", "members.write"},
		{http.MethodDelete, "/api/members/alice", "members.write"},
		{http.MethodGet, "/api/todos/T12", ""},
		{http.MethodPost, "/api/todos/12/answer/x", ""},
		{http.MethodPut, "/api/todos/12", ""},
		{http.MethodPut, "/api/install", ""},
		{http.MethodPost, "/api/install/setup/models", ""},
		{http.MethodPost, "/api/model/credential", ""},
		{http.MethodPost, "/api/user/tokens", ""},
		{http.MethodGet, "/api/members/alice", ""},
		{http.MethodGet, "/api/secrets", "secrets.read"},
		{http.MethodPut, "/api/secrets", "secrets.write"},
		{http.MethodDelete, "/api/secrets", "secrets.write"},
		{http.MethodPatch, "/api/secrets/KEY", "secrets.write"},
		{http.MethodDelete, "/api/secrets/KEY", "secrets.write"},
		{http.MethodGet, "/api/external/sessions", ""},
		{http.MethodPost, "/api/repos/acme/app/secrets", "secrets.write"},
		{http.MethodPatch, "/api/repos/acme/app/secrets/API_KEY", "secrets.write"},
		{http.MethodDelete, "/api/repos/acme/app/secrets/API_KEY", "secrets.write"},
		{http.MethodGet, "/api/repos/acme/app/secrets", "secrets.read"},
		{http.MethodGet, "/api/repos/acme/app/agent-environment", "secrets.read"},
		{http.MethodPut, "/api/repos/acme/app/agent-environment", "secrets.write"},
		{http.MethodPut, "/api/repos/acme/app/agent-environment/secrets/API_KEY/x", ""},
		{http.MethodPut, "/api/repos/acme/app/secrets/API_KEY", ""},
		{http.MethodPost, "/api/repos/acme/app/secrets/API_KEY", ""},
		{http.MethodDelete, "/api/repos/acme/app/secrets", ""},
		{http.MethodPatch, "/api/repos/acme/app/secrets/API_KEY/x", ""},
		{http.MethodPut, "/api/repos/acme/app/agent-environment/secrets/API_KEY", "secrets.write"},
		{http.MethodDelete, "/api/repos/acme/app/agent-environment/secrets/API_KEY", "secrets.write"},
		{http.MethodPost, "/api/orgs/acme/secrets", ""},
		{http.MethodDelete, "/api/orgs/acme/secrets/API_KEY", ""},
		{http.MethodPost, "/api/repos/acme/app/variables", ""},
		{http.MethodPost, "/api/user/repos", ""},
		{http.MethodPost, "/api/repos/local-owner/demo/mythical/bootstrap", ""},
		{http.MethodPost, "/api/repos/local-owner/demo/mythical/items/x/merge", ""},
		{http.MethodPut, "/api/repos/local-owner/demo/mythical/lanes", ""},
		{http.MethodGet, "/api/repos/local-owner/demo/mythical/items/x/y", ""},
		{http.MethodGet, "/api/repos/local-owner/demo/contents/README.md", ""},
		{http.MethodGet, "/api/user/keys", "self.read"},
		{http.MethodPost, "/api/auth/sse-ticket", "self.read"},
		{http.MethodPost, "/api/v1/sse/ticket", "self.read"},
		{http.MethodGet, "/api/auth/sse-ticket", ""},
		{http.MethodPost, "/api/auth/sse-ticket/extra", ""},
		{http.MethodGet, "/api/repos/acme/app/agent/sessions/00000000-0000-4000-8000-000000000001/stream", "repo.read"},
		{http.MethodGet, "/api/user/keys/12", "self.read"},
		{http.MethodPost, "/api/user/keys", ""},
		{http.MethodGet, "/api/user/keys/ben", ""},
		{http.MethodPost, "/api/user/workspaces", ""},
		{http.MethodPost, "/api/agent/turn/erase", ""},
		{http.MethodGet, "/api/install/scorecard", "install.scorecard"},
	} {
		require.Equal(t, tc.command, InstallMemberCommand(tc.method, tc.path), "%s %s", tc.method, tc.path)
	}
}
