/** Canonical /runs through the composed install's real run inventory. */
import { chromium, expect } from "@playwright/test"
import { fillComposer } from "../playwright/composer"
const origin = process.env.SMITHERS_CATALOG_ORIGIN!
if (!origin) throw new Error("Run TestCatalogRunsBrowserInstallInventory")
const browser = await chromium.launch({ headless: true })
try {
  const context = await browser.newContext()
  const cookies: Array<{ Name: string; Value: string }> = JSON.parse(process.env.SMITHERS_CATALOG_COOKIES!)
  await context.addCookies(cookies.map(c => ({ name: c.Name, value: c.Value, url: origin })))
  const page = await context.newPage()
  await page.goto(origin)
  const listing = page.waitForResponse(r => new URL(r.url()).pathname === "/api/runs" && r.request().method() === "GET")
  await fillComposer(page, "/runs")
  await page.keyboard.press("Enter")
  const response = await listing
  expect(response.status()).toBe(200)
  const runs: Array<{ id: string; title: string }> = await response.json()
  expect(Array.isArray(runs)).toBe(true)
  for (const run of runs) await expect(page.getByTestId(`card-run:${run.id}`)).toBeVisible({ timeout: 30_000 })
  await expect(page.locator('[data-testid^="card-run:"]')).toHaveCount(runs.length)
  await expect(page.getByTestId("composer-input")).toBeEditable()
  // Canonical lifecycle inputs refuse unknown cards on the real controller; no active run is borrowed.
  for (const operation of ["stop", "retry"]) {
    await fillComposer(page, `/flow.run ${JSON.stringify({ cardId: "absent-run", operation })}`)
    await page.keyboard.press("Enter")
    await expect(page.getByText("That isn't a run card.", { exact: true }).last()).toBeVisible()
    await expect(page.getByTestId("composer-input")).toBeEditable()
  }
  const afterLifecycle = await page.request.get(origin + "/api/runs")
  expect(afterLifecycle.status()).toBe(200)
  expect(await afterLifecycle.json()).toEqual(runs)
  console.log("C-CAT-01 LIFECYCLE PASS: canonical stop/retry refuse absent cards; real install run inventory unchanged")
  const flowRead = page.waitForResponse(r => new URL(r.url()).pathname === "/api/flows" && r.request().method() === "GET")
  await fillComposer(page, "/flows")
  await page.keyboard.press("Enter")
  const flowResponse = await flowRead
  expect(flowResponse.status()).toBe(200)
  // Chromium cannot retrieve this worker response's body through DevTools.
  // Compare the mounted cards with a second authenticated read of the same
  // real install; neither response is intercepted or synthesized.
  const expectedFlows = await page.request.get(origin + "/api/flows")
  expect(expectedFlows.status()).toBe(200)
  const flows: Array<{ name: string }> = await expectedFlows.json()
  expect(Array.isArray(flows)).toBe(true)
  for (const flow of flows) await expect(page.getByTestId(`card-flow:${flow.name}`)).toBeVisible({ timeout: 30_000 })
  await expect(page.locator('[data-testid^="card-flow:"]')).toHaveCount(flows.length)
  await expect(page.getByTestId("composer-input")).toBeEditable()
  const refusedDirectory = await page.request.get(origin + "/api/branches/main/files?path=../private")
  expect(refusedDirectory.status()).toBe(400)
  const refusedRevision = await page.request.get(origin + "/api/branches/main/files?at=" + "a".repeat(40))
  expect(refusedRevision.status()).toBe(400)
  const directoryRead = page.waitForResponse(r => new URL(r.url()).pathname === "/api/branches/main/files" && r.request().method() === "GET")
  await fillComposer(page, "/files")
  await page.keyboard.press("Enter")
  expect((await directoryRead).status()).toBe(200)
  const directory = page.getByTestId("card-files-branch-main-/")
  const openFile = directory.getByRole("button", { name: "JOURNEY.md", exact: true })
  await expect(openFile).toHaveAttribute("data-flow", "file")
  await openFile.click()
  await expect(page.locator('[data-testid^="card-file-"]').last()).toContainText("Add a greeting to JOURNEY.md")
  await expect(page.getByRole("textbox", { name: "JOURNEY.md", exact: true }).last()).toHaveAttribute("aria-readonly", "true")
  console.log("C-CAT-01 FILES PASS: real mirrored directory and canonical scoped file button")
  const fileRead = page.waitForResponse(r => new URL(r.url()).pathname === "/api/branches/main/files/JOURNEY.md" && r.request().method() === "GET")
  await fillComposer(page, "/file JOURNEY.md:1")
  await page.keyboard.press("Enter")
  const fileResponse = await fileRead
  expect(fileResponse.status()).toBe(200)
  await expect(page.locator('[data-testid^="card-file"]').last()).toBeVisible({ timeout: 30_000 })
  await expect(page.locator('[data-testid^="card-file"]').last()).toContainText("Add a greeting to JOURNEY.md")
  await expect(page.getByRole("textbox", { name: "JOURNEY.md", exact: true }).last()).toHaveAttribute("aria-readonly", "true")
  await expect(page.getByTestId("composer-input")).toBeEditable()
  console.log("C-CAT-01 FILE PASS: canonical file door reads the actual mirrored main source")
  const proposalRead = page.waitForResponse(r => new URL(r.url()).pathname === "/api/proposals" && r.request().method() === "GET")
  await fillComposer(page, '/wiki {"operation":"proposal","id":"catalog:proposal"}')
  await page.keyboard.press("Enter")
  expect((await proposalRead).status()).toBe(200)
  const proposal = page.getByTestId("card-proposal:catalog:proposal")
  await expect(proposal).toContainText("Run catalog checks")
  await expect(proposal.getByRole("button", { name: "Make TODO", exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByTestId("card-proposal:catalog:proposal")).toContainText("Run catalog checks")
  await expect(page.locator('[data-testid^="card-file"]').last()).toContainText("Add a greeting to JOURNEY.md")
  await expect(page.getByTestId("composer-input")).toBeEditable()
  console.log("C-CAT-01 PROPOSAL PASS: canonical Wiki door, real proposal read and reload; no proposal mutation")
  console.log(`C-CAT-01 FLOWS PASS: ${flows.length} served flows, composed install, canonical /flows`)
  console.log(`C-CAT-01 RUNS PASS: ${runs.length} served runs, composed install, canonical /runs`)
} finally { await browser.close() }
