//! Port of the guest helper's held-descriptor cleanup, with a shared 2 s
//! startup barrier. No helper subprocess, path-based kill or ignored kill error.
//! Not activated until installed provenance and real root validation exist.
use crate::cgroup_policy::{empty, name_valid};
use crate::drain::{Observation, drain};
use std::ffi::CString;
use std::fs::File;
use std::io::{self, Read, Write};
use std::os::fd::{AsRawFd, FromRawFd, OwnedFd, RawFd};
use std::os::unix::fs::MetadataExt;
use std::time::{Duration, Instant};

fn refusal() -> io::Error {
    io::Error::other("untrusted session cgroup")
}
fn open_at(parent: RawFd, name: &str, flags: i32) -> io::Result<OwnedFd> {
    let name = CString::new(name).map_err(|_| refusal())?;
    let fd = unsafe {
        libc::openat(
            parent,
            name.as_ptr(),
            flags | libc::O_CLOEXEC | libc::O_NOFOLLOW,
        )
    };
    if fd < 0 {
        return Err(io::Error::last_os_error());
    }
    Ok(unsafe { OwnedFd::from_raw_fd(fd) })
}
fn directory(parent: RawFd, name: &str) -> io::Result<OwnedFd> {
    let fd = open_at(parent, name, libc::O_RDONLY | libc::O_DIRECTORY)?;
    let mut info = std::mem::MaybeUninit::<libc::stat>::uninit();
    if unsafe { libc::fstat(fd.as_raw_fd(), info.as_mut_ptr()) } != 0 {
        return Err(io::Error::last_os_error());
    }
    let info = unsafe { info.assume_init() };
    if info.st_uid != 0 || info.st_mode & 0o022 != 0 {
        return Err(refusal());
    }
    Ok(fd)
}
pub struct Sessions {
    parent: OwnedFd,
}
impl Sessions {
    /// Resolve every fixed ancestor without symlinks; require cgroup v2.
    /// This code neither creates directories nor consumes branch paths.
    pub fn open() -> io::Result<Self> {
        if unsafe { libc::geteuid() } != 0 {
            return Err(refusal());
        }
        let mut fd = directory(libc::AT_FDCWD, "/")?;
        for component in ["sys", "fs", "cgroup", "smithers", "sessions"] {
            fd = directory(fd.as_raw_fd(), component)?;
        }
        let mut info = std::mem::MaybeUninit::<libc::statfs>::uninit();
        if unsafe { libc::fstatfs(fd.as_raw_fd(), info.as_mut_ptr()) } != 0 {
            return Err(io::Error::last_os_error());
        }
        if unsafe { info.assume_init() }.f_type != 0x6367_7270 {
            return Err(refusal());
        }
        Ok(Self { parent: fd })
    }
    /// Refuse a detached parent before admission, while cleanup continues to
    /// target only the held original inode. Never adopt a replacement subtree.
    pub(crate) fn recheck(&self) -> io::Result<()> {
        let current = Self::open()?;
        same_directory(&self.parent, &current.parent)
    }
    /// Create an exclusively owned group. IDs are generated by the registry,
    /// never accepted as a path from a remote request.
    pub fn create(&self, id: &str) -> io::Result<Group> {
        self.recheck()?;
        if !name_valid(id) {
            return Err(refusal());
        }
        let name = CString::new(id).map_err(|_| refusal())?;
        if unsafe { libc::mkdirat(self.parent.as_raw_fd(), name.as_ptr(), 0o755) } != 0 {
            return Err(io::Error::last_os_error());
        }
        let fd = directory(self.parent.as_raw_fd(), id)?;
        self.recheck()?;
        Ok(Group { fd })
    }
    pub fn remove(&self, id: &str) -> io::Result<()> {
        if !name_valid(id) {
            return Err(refusal());
        }
        let name = CString::new(id).map_err(|_| refusal())?;
        if unsafe { libc::unlinkat(self.parent.as_raw_fd(), name.as_ptr(), libc::AT_REMOVEDIR) }
            != 0
        {
            return Err(io::Error::last_os_error());
        }
        Ok(())
    }
    /// Kill all children before polling any. One deadline bounds the whole
    /// barrier rather than giving each orphan another independent timeout.
    pub fn startup_barrier(&self) -> io::Result<()> {
        self.recheck()?;
        let started = Instant::now();
        let mut children = Vec::new();
        let mut names = Vec::new();
        // /proc/self/fd targets the held, already validated parent, not a
        // re-resolved member-controlled path. No child path is followed.
        for entry in std::fs::read_dir(format!("/proc/self/fd/{}", self.parent.as_raw_fd()))? {
            let name = entry?.file_name().into_string().map_err(|_| refusal())?;
            if !entry_is_directory(self.parent.as_raw_fd(), &name)? {
                continue;
            }
            if !name_valid(&name) {
                return Err(refusal());
            }
            children.push(directory(self.parent.as_raw_fd(), &name)?);
            names.push(name);
        }
        drain(&mut Handles { children, started }, Duration::from_secs(2))?;
        for name in names {
            self.remove(&name)?;
        }
        self.recheck()
    }
}
fn same_directory(held: &OwnedFd, observed: &OwnedFd) -> io::Result<()> {
    let held = File::from(held.try_clone()?).metadata()?;
    let observed = File::from(observed.try_clone()?).metadata()?;
    if held.dev() != observed.dev() || held.ino() != observed.ino() {
        return Err(refusal());
    }
    Ok(())
}

fn entry_is_directory(parent: RawFd, name: &str) -> io::Result<bool> {
    let name = CString::new(name).map_err(|_| refusal())?;
    let mut info = std::mem::MaybeUninit::<libc::stat>::uninit();
    if unsafe {
        libc::fstatat(
            parent,
            name.as_ptr(),
            info.as_mut_ptr(),
            libc::AT_SYMLINK_NOFOLLOW,
        )
    } != 0
    {
        return Err(io::Error::last_os_error());
    }
    let info = unsafe { info.assume_init() };
    if info.st_mode & libc::S_IFMT == libc::S_IFLNK {
        return Err(refusal());
    }
    Ok(info.st_mode & libc::S_IFMT == libc::S_IFDIR)
}

// The policy owns ordering/deadlines; this adapter alone reads kernel files.
struct Handles {
    children: Vec<OwnedFd>,
    started: Instant,
}
impl Observation for Handles {
    fn count(&self) -> usize {
        self.children.len()
    }
    fn elapsed(&self) -> Duration {
        self.started.elapsed()
    }
    fn kill(&mut self, index: usize) -> io::Result<()> {
        let fd = open_at(
            self.children[index].as_raw_fd(),
            "cgroup.kill",
            libc::O_WRONLY,
        )?;
        File::from(fd).write_all(b"1")
    }
    fn empty(&mut self, index: usize) -> io::Result<bool> {
        let fd = open_at(
            self.children[index].as_raw_fd(),
            "cgroup.events",
            libc::O_RDONLY | libc::O_NONBLOCK,
        )?;
        let mut bytes = vec![];
        File::from(fd).take(4097).read_to_end(&mut bytes)?;
        if bytes.len() > 4096 {
            return Err(refusal());
        }
        empty(std::str::from_utf8(&bytes).map_err(|_| refusal())?)
    }
    fn wait(&mut self) {
        std::thread::sleep(Duration::from_millis(10));
    }
}

/// A group's lifetime is owned independently of its first process. Closing an
/// exec channel must not forget background processes in this descriptor.
pub struct Group {
    fd: OwnedFd,
}
impl Group {
    /// Open before fork; child enrollment then uses only a write syscall.
    pub fn enrollment_fd(&self) -> io::Result<OwnedFd> {
        open_at(self.fd.as_raw_fd(), "cgroup.procs", libc::O_WRONLY)
    }
    pub fn kill_all(groups: &[&Group]) -> io::Result<()> {
        let started = Instant::now();
        let mut children = Vec::with_capacity(groups.len());
        for group in groups {
            children.push(group.fd.try_clone()?);
        }
        drain(&mut Handles { children, started }, Duration::from_secs(5))
    }
}

#[cfg(test)]
mod replacement_tests {
    use super::*;
    // Real openat/read/write syscalls with concurrent pathname replacement.
    // These ordinary files are supplemental descriptor tests, not kernel cgroup
    // or installed-root evidence; the independent reference campaign is required.
    #[test]
    fn cleanup_and_enrollment_remain_on_held_child_during_replacement() {
        for replacement in ["directory", "symlink"] {
            let root = std::env::temp_dir().join(format!(
                "trm06-child-{}-{}-{replacement}",
                std::process::id(),
                std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap()
                    .as_nanos()
            ));
            std::fs::create_dir(&root).unwrap();
            let child = root.join("s-0000000000000001");
            let outside = root.join("outside");
            std::fs::create_dir(&child).unwrap();
            std::fs::create_dir(&outside).unwrap();
            for directory in [&child, &outside] {
                std::fs::write(directory.join("cgroup.kill"), b"0").unwrap();
                std::fs::write(directory.join("cgroup.events"), b"populated 0\n").unwrap();
                std::fs::write(directory.join("cgroup.procs"), b"0").unwrap();
            }
            // Deliberately conflicting replacement population: cleanup must
            // observe the held child, never infer empty from a different path.
            std::fs::write(outside.join("cgroup.events"), b"populated 1\n").unwrap();
            let group = Group {
                fd: OwnedFd::from(File::open(&child).unwrap()),
            };
            let attacker_root = root.clone();
            let (ready, attacked) = std::sync::mpsc::channel();
            let attacker = std::thread::spawn(move || {
                std::fs::rename(&child, attacker_root.join("held-child")).unwrap();
                if replacement == "directory" {
                    std::fs::create_dir(&child).unwrap();
                    for name in ["cgroup.kill", "cgroup.events", "cgroup.procs"] {
                        std::fs::copy(outside.join(name), child.join(name)).unwrap();
                    }
                } else {
                    std::os::unix::fs::symlink(&outside, &child).unwrap();
                }
                ready.send(()).unwrap();
            });
            attacked.recv_timeout(Duration::from_secs(2)).unwrap();
            attacker.join().unwrap();
            Group::kill_all(&[&group]).unwrap();
            File::from(group.enrollment_fd().unwrap())
                .write_all(b"7")
                .unwrap();
            assert_eq!(
                std::fs::read(root.join("held-child/cgroup.kill")).unwrap(),
                b"1"
            );
            assert_eq!(
                std::fs::read(root.join("held-child/cgroup.procs")).unwrap(),
                b"7"
            );
            for directory in [root.join("outside"), root.join("s-0000000000000001")] {
                assert_eq!(std::fs::read(directory.join("cgroup.kill")).unwrap(), b"0");
                assert_eq!(std::fs::read(directory.join("cgroup.procs")).unwrap(), b"0");
                assert_eq!(
                    std::fs::read(directory.join("cgroup.events")).unwrap(),
                    b"populated 1\n"
                );
            }
            std::fs::remove_dir_all(root).unwrap();
        }
    }

    #[test]
    fn raced_control_symlinks_refuse_before_outside_reads_or_writes() {
        for control in ["cgroup.kill", "cgroup.events", "cgroup.procs"] {
            let root = std::env::temp_dir().join(format!(
                "trm06-control-{}-{}-{control}",
                std::process::id(),
                std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap()
                    .as_nanos()
            ));
            std::fs::create_dir(&root).unwrap();
            let sentinel = root.join("outside");
            std::fs::write(&sentinel, b"outside-fixture\0").unwrap();
            let before = std::fs::metadata(&sentinel).unwrap();
            std::fs::write(root.join(control), b"0").unwrap();
            let group = Group {
                fd: OwnedFd::from(File::open(&root).unwrap()),
            };
            let attacker_root = root.clone();
            std::thread::spawn(move || {
                std::fs::remove_file(attacker_root.join(control)).unwrap();
                std::os::unix::fs::symlink(
                    attacker_root.join("outside"),
                    attacker_root.join(control),
                )
                .unwrap();
            })
            .join()
            .unwrap();
            let mut handles = Handles {
                children: vec![group.fd.try_clone().unwrap()],
                started: Instant::now(),
            };
            let error = match control {
                "cgroup.kill" => handles.kill(0).unwrap_err(),
                "cgroup.events" => handles.empty(0).unwrap_err(),
                _ => group.enrollment_fd().unwrap_err(),
            };
            assert_eq!(error.raw_os_error(), Some(libc::ELOOP));
            assert_eq!(std::fs::read(&sentinel).unwrap(), b"outside-fixture\0");
            let after = std::fs::metadata(&sentinel).unwrap();
            assert_eq!(
                (before.ino(), before.uid(), before.mode()),
                (after.ino(), after.uid(), after.mode())
            );
            std::fs::remove_dir_all(root).unwrap();
        }
    }

    #[test]
    fn directory_replacement_does_not_adopt_new_inode() {
        let root = std::env::temp_dir().join(format!(
            "trm06-parent-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir(&root).unwrap();
        let path = root.join("sessions");
        std::fs::create_dir(&path).unwrap();
        let held = OwnedFd::from(File::open(&path).unwrap());
        same_directory(&held, &OwnedFd::from(File::open(&path).unwrap())).unwrap();
        std::fs::rename(&path, root.join("old-sessions")).unwrap();
        std::fs::create_dir(&path).unwrap();
        assert!(same_directory(&held, &OwnedFd::from(File::open(&path).unwrap())).is_err());
        same_directory(
            &held,
            &OwnedFd::from(File::open(root.join("old-sessions")).unwrap()),
        )
        .unwrap();
        std::fs::remove_dir_all(root).unwrap();
    }
}
