/**
 * No shipped Node composition installs an HTTP client that ignores the egress
 * proxy its environment names.
 *
 * `@effect/platform-node` ships `NodeHttpClient.layerUndici`, whose dispatcher
 * is a bare Undici `Agent`. A bare `Agent` dials every origin directly: it does
 * not read `HTTP_PROXY`, `HTTPS_PROXY` or `NO_PROXY`. Provided under a layer
 * that takes `HttpClient` from context — a judge, a model transport, a fetch
 * rule, a host bundle — it also *shadows* whatever proxy-aware client the host
 * built, and the call site reads as correct either way. That is the whole
 * defect: invisible on a developer machine with open egress, fatal inside a
 * microsandbox whose only way out is a proxy, where the request leaves for the
 * origin, the firewall drops it, and the symptom surfaces as
 * `completion_unjudged` far from the composition that chose the client.
 *
 * The replacement is one constructor,
 * `@smthrs/platform-node/EgressHttpClient`'s `layer(environment)`, which routes
 * through the proxy the environment names and is exactly the plain Undici pool
 * when it names none — so an unproxied host is unchanged and there is no reason
 * for a composition to reach past it.
 *
 * Scope is shipped source. Test trees are deliberately outside: a test that
 * names `layerUndici` is pinning a transport it owns end to end, against a
 * loopback server, with no proxy in the picture, and it is exactly where a
 * direct pool should be spelled out. `@effect/platform-node` itself, under
 * `node_modules`, is not read.
 *
 * Run it with `node --test "scripts/repo-contract/*.test.mjs"`.
 */
import assert from "node:assert/strict"
import { mkdirSync, mkdtempSync, readdirSync, readFileSync, realpathSync, rmSync, statSync, symlinkSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join, relative, sep } from "node:path"
import { describe, it } from "node:test"
import ts from "typescript"

import { repoRoot as root } from "../workspace-packages.mjs"

/** The trees that hold shipped source. `scripts/` is absent on purpose: this file names the banned spelling. */
const scanned = ["packages", "apps", "flows", "examples"]

/**
 * Directory names that hold no shipped source wherever they appear, or hold a
 * copy of somebody else's.
 *
 * `build` is deliberately absent. Pruning that name at any depth would drop
 * `packages/smithers/build/` — @smthrs/build-cli, @smthrs/infra and
 * @smthrs/targets, three shipped packages holding one of the very sites this
 * gate exists for, `FetchExecutor.ts`. Generated `build/` output is named by
 * path in {@link skippedPaths} instead.
 */
const skippedDirectories = new Set([
  "node_modules",
  "dist",
  "coverage",
  "test",
  "tests",
  "e2e",
  "fixtures",
  "__fixtures__",
  ".git",
  ".jj",
  ".astro",
  ".cache",
  ".turbo",
  ".vite"
])

/** Generated trees, pruned by repository-relative path so no shipped package sharing a name goes with them. */
const skippedPaths = new Set([
  // Electrobun output: a packaged `.app` holding a bundled copy of this
  // workspace and its dependencies. Gitignored, regenerated by every dev run.
  "apps/app/build"
])

/** Every JavaScript and TypeScript extension Node, Bun or a bundler loads as code. */
const sourceExtension = /\.(?:[cm]?[jt]s|[jt]sx)$/

/** Source files, never a test double and never a declaration. */
export const isSource = (name) =>
  sourceExtension.test(name)
  && !/\.d\.[cm]?ts$/.test(name)
  && !/\.(?:test|spec)\.(?:[cm]?[jt]s|[jt]sx)$/.test(name)

/** Every shipped source file under {@link scanned}, as repository-relative paths. */
export const sources = (repositoryRoot = root) => {
  const found = []
  // Real paths of the directories already walked, so a symlink loop ends.
  const visited = new Set()
  const walk = (directory) => {
    let entries
    try {
      const real = realpathSync(directory)
      if (visited.has(real)) return
      visited.add(real)
      entries = readdirSync(directory, { withFileTypes: true })
    } catch {
      return
    }
    for (const entry of entries) {
      const path = relative(repositoryRoot, join(directory, entry.name)).split(sep).join("/")
      // Git tracks symlinks and every compiler and bundler follows them, so a
      // link is judged by what it points at; the skip lists still match its name.
      let kind = entry
      if (entry.isSymbolicLink()) {
        try {
          kind = statSync(join(directory, entry.name))
        } catch {
          continue
        }
      }
      if (kind.isDirectory()) {
        if (!skippedDirectories.has(entry.name) && !skippedPaths.has(path)) walk(join(directory, entry.name))
      } else if (kind.isFile() && isSource(entry.name)) {
        found.push(path)
      }
    }
  }
  for (const tree of scanned) walk(join(repositoryRoot, tree))
  return found.sort()
}

/**
 * The bare, proxy-blind spellings.
 *
 * `\b` after the name is what keeps `layerUndiciNoDispatcher` out of the ban:
 * that one takes its dispatcher from context, which is how the replacement is
 * built in the first place.
 */
const banned = [
  { pattern: /\blayerUndici\b/, name: "NodeHttpClient.layerUndici" },
  { pattern: /\bmakeDispatcher\b/, name: "NodeHttpClient.makeDispatcher" }
]

/** A string whose whole text is the name: a property key held in a variable. */
const exact = (pattern) => new RegExp(`^${pattern.source.replaceAll("\\b", "")}$`)

const scriptKind = (path) =>
  /\.[jt]sx$/.test(path) ? ts.ScriptKind.TSX : /\.[cm]?js$/.test(path) ? ts.ScriptKind.JS : ts.ScriptKind.TS

/**
 * Every banned spelling in `content` outside a comment, as `line name` pairs.
 *
 * Comments are prose, which may name the banned spelling to explain why it is
 * banned, so they are exempt. The TypeScript parser decides what is a comment:
 * a line-prefix rule exempts code that follows a closing block comment or that
 * starts with `*` inside an expression. Identifiers and computed member names
 * are checked, so `NodeHttpClient["layerUndici"]` fails too, and so does any
 * string whose whole text is a banned name, the key of `NodeHttpClient[k]`. A
 * string that only describes the ban, such as a security-review prompt, is
 * prose like a comment. The raw-text pre-check also passes any file holding a
 * `\u` escape, so an escaped identifier reaches the parser.
 *
 * Known limit: the check reads single literals, not constant folding, so a key
 * assembled at runtime, `NodeHttpClient["layer" + "Undici"]` or a template with
 * a substitution, passes. Review catches that spelling; this gate does not.
 */
export const bannedUses = (path, content) => {
  if (!/layerUndici|makeDispatcher|\\u/.test(content)) return []
  const file = ts.createSourceFile(path, content, ts.ScriptTarget.Latest, true, scriptKind(path))
  const found = []
  const visit = (node) => {
    const named = ts.isIdentifier(node)
      || (ts.isStringLiteralLike(node) && ts.isElementAccessExpression(node.parent) && node.parent.argumentExpression === node)
    const key = ts.isStringLiteralLike(node) && !named
    if (named || key) {
      const text = ts.isIdentifier(node) ? ts.idText(node) : node.text
      for (const { pattern, name } of banned) {
        if (key ? exact(pattern).test(text) : pattern.test(text)) found.push(`${file.getLineAndCharacterOfPosition(node.getStart(file)).line + 1} ${name}`)
      }
    }
    ts.forEachChild(node, visit)
  }
  visit(file)
  return found
}

/**
 * The one file allowed to name them in code: the constructor that wraps them.
 * Anything else added here has to carry the sentence that says why the
 * environment's proxy does not apply to it.
 */
const defines = "packages/smithers/flows/platform-node/src/EgressHttpClient.ts"

describe("the outbound HTTP client shipped compositions install", () => {
  it("reads shipped source from every tree that composes a Node host", () => {
    const found = sources()
    assert.ok(found.length > 500, `only ${found.length} shipped sources found under ${scanned.join(", ")}`)
    for (const tree of scanned) {
      assert.ok(found.some((path) => path.startsWith(`${tree}/`)), `no shipped source found under ${tree}/`)
    }
    // Named files, not a count: a count stays green while a whole package
    // tree silently leaves the scan. Pruning the bare name `build` at any
    // depth is exactly how the first two of these were invisible to this gate,
    // and the first is one of the sites the gate was written for.
    for (const path of [
      "packages/smithers/build/build-cli/src/internal/rules/FetchExecutor.ts",
      "packages/smithers/src/internal/NodeControlHost.ts",
      "flows/repository/jev-checks.ts",
      "apps/app/src/bun/BrowserFetch.ts"
    ]) {
      assert.ok(found.includes(path), `${path} is shipped source this gate never read`)
    }
    // Packaged Electrobun output carries a bundled copy of this workspace.
    assert.deepEqual(found.filter((path) => path.startsWith("apps/app/build/")), [])
  })

  it("installs the environment's client everywhere, and the bare pool nowhere", () => {
    const offenders = []
    let installs = 0
    for (const path of sources()) {
      let content
      try {
        content = readFileSync(join(root, path), "utf8")
      } catch {
        continue
      }
      if (content.includes("EgressHttpClient.layer(") || content.includes("layerEgressHttpClient(")) installs += 1
      if (path === defines) continue
      for (const use of bannedUses(path, content)) offenders.push(`${path}:${use}`)
    }
    // A gate whose subject has vanished is a gate that cannot fail. The
    // replacement has to be installed somewhere for the ban to mean anything.
    assert.ok(installs >= 10, `the environment's client is installed in only ${installs} shipped sources`)
    assert.deepEqual(
      offenders,
      [],
      "a bare Undici pool ignores HTTP_PROXY/HTTPS_PROXY and dials every origin directly, so a host inside a "
        + "default-deny sandbox reaches nothing. Install `EgressHttpClient.layer(environment)` from "
        + "`@smthrs/platform-node`, which is the same plain pool when no proxy is named:\n  "
        + offenders.join("\n  ")
    )
  })
})

describe("the egress gate's own reading", () => {
  it("scans every JavaScript and TypeScript extension, never a declaration or test", () => {
    for (const name of ["a.ts", "a.tsx", "a.mts", "a.cts", "a.js", "a.jsx", "a.mjs", "a.cjs"]) {
      assert.ok(isSource(name), `${name} is shipped source`)
    }
    for (const name of ["a.d.ts", "a.d.mts", "a.d.cts", "a.test.js", "a.spec.cjs", "a.test.tsx", "a.test.mjs", "a.json", "a.md"]) {
      assert.ok(!isSource(name), `${name} is not shipped source`)
    }
  })

  it("exempts comments by parsing, not by line prefix", () => {
    assert.deepEqual(bannedUses("a.ts", "// layerUndici is banned\n/** makeDispatcher too */\nconst x = 1\n"), [])
    assert.deepEqual(bannedUses("a.ts", "/* ok */ Layer.provide(NodeHttpClient.layerUndici)\n"), ["1 NodeHttpClient.layerUndici"])
    assert.deepEqual(bannedUses("a.js", "const n = 2\n  * NodeHttpClient.makeDispatcher().x\n"), ["2 NodeHttpClient.makeDispatcher"])
    assert.deepEqual(bannedUses("a.cjs", "const c = NodeHttpClient[\"layerUndici\"]\n"), ["1 NodeHttpClient.layerUndici"])
    assert.deepEqual(bannedUses("a.jsx", "const c = <X layer={NodeHttpClient.layerUndici} />\n"), ["1 NodeHttpClient.layerUndici"])
    assert.deepEqual(bannedUses("a.ts", "const ok = NodeHttpClient.layerUndiciNoDispatcher\n"), [])
    assert.deepEqual(bannedUses("a.ts", "const prose = \"a bare layerUndici ignores the proxy\"\n"), [])
    assert.deepEqual(bannedUses("a.ts", "const k = \"layerUndici\"\nLayer.provide(NodeHttpClient[k])\n"), ["1 NodeHttpClient.layerUndici"])
    assert.deepEqual(bannedUses("a.ts", "const k = `makeDispatcher`\n"), ["1 NodeHttpClient.makeDispatcher"])
    assert.deepEqual(bannedUses("a.ts", "Layer.provide(NodeHttpClient.layer\\u0055ndici)\n"), ["1 NodeHttpClient.layerUndici"])
  })

  it("reads a symlinked source file and a symlinked directory, and survives a link loop", () => {
    const fixture = mkdtempSync(join(tmpdir(), "egress-gate-"))
    try {
      mkdirSync(join(fixture, "packages/q/src"), { recursive: true })
      mkdirSync(join(fixture, "packages/q/test"), { recursive: true })
      writeFileSync(join(fixture, "packages/q/test/real.ts"), "Layer.provide(NodeHttpClient.layerUndici)\n")
      symlinkSync("../test/real.ts", join(fixture, "packages/q/src/Bad.ts"))
      symlinkSync("../test", join(fixture, "packages/q/src/linked"))
      symlinkSync("..", join(fixture, "packages/q/src/loop"))
      const found = sources(fixture)
      assert.ok(found.includes("packages/q/src/Bad.ts"), found.join(","))
      assert.ok(found.includes("packages/q/src/linked/real.ts"), found.join(","))
      assert.deepEqual(bannedUses("Bad.ts", readFileSync(join(fixture, "packages/q/src/Bad.ts"), "utf8")), [
        "1 NodeHttpClient.layerUndici"
      ])
    } finally {
      rmSync(fixture, { recursive: true, force: true })
    }
  })
})
