import type { Ctx } from "@milkdown/kit/ctx";
import { computeDocDiff } from "@milkdown/kit/plugin/diff";
import { editorViewCtx, parserCtx } from "@milkdown/kit/core";
import type { Node } from "@milkdown/kit/prose/model";
import type { EditorState, Transaction } from "@milkdown/kit/prose/state";

/** Map selection and local undo through the individual peer changes. */
export function externalDocumentTransaction(state: EditorState, next: Node): Transaction | null {
  // Heading ids are generated by Milkdown after parsing; comparing those
  // derived attributes would replace unchanged headings on every update.
  const changes = computeDocDiff(state.doc, next, { ignoreAttrs: { heading: ["id"] } });
  if (changes.length === 0) return null;
  const transaction = state.tr.setMeta("addToHistory", false);
  for (let i = changes.length - 1; i >= 0; i--) {
    const change = changes[i]!;
    transaction.replace(change.fromA, change.toA, next.slice(change.fromB, change.toB));
  }
  return transaction;
}

/** External Markdown updates retain the editor's state, plugins and focus owner. */
export const replaceMarkdown = (markdown: string) => (ctx: Ctx): void => {
  const view = ctx.get(editorViewCtx);
  const next = ctx.get(parserCtx)(markdown);
  if (!next) return;
  const transaction = externalDocumentTransaction(view.state, next);
  if (!transaction) return;
  const focused = view.hasFocus();
  view.dispatch(transaction);
  // Replacing a selected block may replace its DOM. Restore focus only if
  // this editor owned it; a peer update must not take focus from Chat.
  if (focused && !view.hasFocus()) view.focus();
};
