#!/usr/bin/env node
/** Generate the portable Paper record; --check verifies committed bytes. */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { rgbChannels } from "../src/rgbChannels.ts";
import { mixColors } from "../src/mixColors.ts";
import { selectionColor } from "./selectionColor.ts";
import { paperLight, paperDark } from "./paperTokens.ts";
const require = createRequire(import.meta.url);
const shikiManifest = resolve(dirname(require.resolve("@shikijs/themes")), "../package.json");
const { version: shikiVersion } = JSON.parse(readFileSync(shikiManifest, "utf8")) as { version: string };
type UpstreamTheme = { colors: Record<string, string | null>; name: string };
function opaque(value: string | null | undefined, fallback: string): string {
  return value && /^#[\da-f]{6}(?:ff)?$/i.test(value) ? value.slice(0, 7) : fallback;
}
async function load(id: string): Promise<UpstreamTheme> {
  return (await import(pathToFileURL(require.resolve(`@shikijs/themes/${id}`)).href)).default as UpstreamTheme;
}
function terminal(theme: UpstreamTheme, bg: string, text: string, semantic: Record<string, string>) {
  const c = theme.colors;
  // Themes without terminal.ansi* use the corresponding UI semantic seed.
  // Bright fallbacks repeat that mapping; bright black is a text/background
  // midpoint and bright white uses the editor foreground.
  const ansi = (name: string, fallback: string) => opaque(c[`terminal.ansi${name}`], fallback);
  const selection = selectionColor(
    c["terminal.selectionBackground"],
    `rgba(${rgbChannels(semantic.info).join(",")},0.3)`,
  );
  return {
    background: bg,
    foreground: text,
    cursor: text,
    selectionBackground: selection,
    black: ansi("Black", bg),
    red: ansi("Red", semantic.danger),
    green: ansi("Green", semantic.success),
    yellow: ansi("Yellow", semantic.warning),
    blue: ansi("Blue", semantic.info),
    magenta: ansi("Magenta", semantic.brand),
    cyan: ansi("Cyan", semantic.info),
    white: ansi("White", text),
    brightBlack: ansi("BrightBlack", mixColors(text, bg, 0.45)),
    brightRed: ansi("BrightRed", semantic.danger),
    brightGreen: ansi("BrightGreen", semantic.success),
    brightYellow: ansi("BrightYellow", semantic.warning),
    brightBlue: ansi("BrightBlue", semantic.info),
    brightMagenta: ansi("BrightMagenta", semantic.brand),
    brightCyan: ansi("BrightCyan", semantic.info),
    brightWhite: ansi("BrightWhite", text),
  };
}

const literal = (value: unknown, indent = 0): string => {
  const pad = "  ".repeat(indent + 1);
  const close = "  ".repeat(indent);
  if (Array.isArray(value)) {
    return value.length === 0
      ? "[]"
      : `[\n${value.map((entry) => `${pad}${literal(entry, indent + 1)},\n`).join("")}${close}]`;
  }
  if (value !== null && typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) return "{}";
    const body = entries
      .map(([key, entry]) => {
        const name = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
        return `${pad}${name}: ${literal(entry, indent + 1)},\n`;
      })
      .join("");
    return `{\n${body}${close}}`;
  }
  return JSON.stringify(value);
};

const [darkSource, lightSource] = await Promise.all([load("night-owl"), load("night-owl-light")]);
const record = { key: "paper", label: "Paper", light: paperLight, dark: paperDark,
 syntax: { shikiDark: "night-owl", shikiLight: "night-owl-light" },
 terminal: { dark: terminal(darkSource, paperDark.bg, paperDark.text, paperDark),
 light: terminal(lightSource, paperLight.bg, paperLight.text, paperLight) } };
const source = `// Generated by packages/smithers/ui/ui-styleguide/scripts/generate-theme-registry.ts from @shikijs/themes ${shikiVersion}. Do not edit.\nimport type { SmithersTheme } from "../SmithersTheme.ts";\n\nexport const paper: SmithersTheme = ${literal(record)};\n`;
const file = resolve(dirname(fileURLToPath(import.meta.url)), "../src/themes/paper.ts");
if (process.argv.includes("--check")) {
  let current: string | undefined;
  try { current = readFileSync(file, "utf8"); } catch { current = undefined; }
  if (current !== source) { console.error("Generated Paper tokens are stale; run scripts/generate-theme-registry.ts"); process.exit(1); }
} else writeFileSync(file, source);
