/** Generate shipped metadata without invoking a command or importing repository flow bodies. */
import { readFileSync, writeFileSync, renameSync } from "node:fs"
import { resolve } from "node:path"
import { Schema } from "effect"
import { baseFlows, adminFlows, type CommandActions } from "../apps/app/src/mainview/flows/Flows"
import { nameOf } from "../apps/app/src/mainview/flows/registry"

const root = resolve(import.meta.dir, "..")
const actions = new Proxy({ docsAvailable: () => true, debugApi: { available: () => true } }, {
  get: (target, key) => Reflect.get(target, key) ?? (() => undefined)
}) as unknown as CommandActions

export const generateCatalog = () => {
  const entries = [...baseFlows(actions), ...adminFlows(actions)]
  const names = new Set<string>()
  return entries.map(entry => {
    const name = nameOf(entry)
    if (names.has(name)) throw new Error(`Duplicate operation: ${name}`)
    names.add(name)
    const m = entry.metadata
    return { name, slash: m.slash ?? null, cli: m.cli ?? null, journey: m.journey ?? [], group: m.group ?? "",
      visibility: m.visibility ?? "hidden", actors: m.actors ?? [], minimumRole: m.minimumRole ?? "member",
      agent: m.agent ?? "never", summary: m.summary, http: m.http ?? null,
      payload: Schema.toJsonSchemaDocument(entry.input) }
  }).sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0)
}
export type CatalogRow = ReturnType<typeof generateCatalog>[number]
export const generateSkill = (rows: ReadonlyArray<CatalogRow>) =>
  "## Commands\n\n" + rows.filter(row => row.cli !== null && row.actors.includes("external_agent") &&
    (row.visibility === "core" || row.visibility === "advanced"))
    .map(row => `- \`smthrs ${row.cli!.join(" ")}\` — ${row.agent}${row.agent === "confirm" ? "; waits for the person's confirmation" : ""}. ${row.summary}`)
    .join("\n") + "\n"

if (import.meta.main) {
  const args = new Set(process.argv.slice(2))
  for (const arg of args) if (!["--check", "--skill"].includes(arg)) throw new Error(`Unknown option: ${arg}`)
  const rows = generateCatalog()
  const artifact = JSON.stringify({ version: 1, operations: rows }, null, 2) + "\n"
  const cardInput = readFileSync(resolve(root, "packages/rpc/src/CardAction.ts"), "utf8")
  const tags = [...cardInput.matchAll(/^  readonly "([^"]+)":/gm)].map(match => match[1]!)
  for (const tag of tags) if (!rows.some(row => row.name === tag)) throw new Error(`Card command has no Operation: ${tag}`)
  const tagSource = `// Generated by scripts/catalog-mvp.ts; declarations remain the authority.\nimport { z } from "zod"\nexport const CATALOG_TAGS = ${JSON.stringify(tags, null, 2)} as const\nexport const CatalogTagSchema = z.enum(CATALOG_TAGS)\nexport type CatalogTag = z.infer<typeof CatalogTagSchema>\n`
  const outputs = [[resolve(root, "catalog.mvp.json"), artifact], [resolve(root, "packages/smithers/src/internal/backend/catalog.mvp.json"), artifact], [resolve(root, "packages/rpc/src/CatalogTags.ts"), tagSource]]
  if (args.has("--skill")) {
    const path = resolve(root, "packages/smithers/skills/smithers/SKILL.md")
    const current = readFileSync(path, "utf8")
    const before = current.split("\n## Commands\n")[0]!.trimEnd()
    outputs.push([path, before + "\n\n" + generateSkill(rows)])
  }
  for (const [path, content] of outputs) {
    if (args.has("--check")) {
      if (readFileSync(path!, "utf8") !== content) throw new Error(`Catalog drift: ${path}`)
    } else {
      const temporary = `${path}.tmp-${process.pid}`
      writeFileSync(temporary, content!)
      renameSync(temporary, path!)
    }
  }
  // All output is synchronous; imported host modules may own long-lived resources.
  process.exit(0)
}
