/** Host reference from exported command schemas; never invokes a host handler. */
import { definitions } from "../packages/smithers/src/internal/backend/Definitions"

export const generateHostReference = (): string => {
  const rows = Object.entries(definitions).filter(([name]) => name.startsWith("host ")).map(([name, definition]) => {
    const args = Object.entries(definition.args.shape).map(([key, field]) => field.isOptional() ? `[${key}]` : `<${key}>`)
    const options = Object.entries(definition.options.shape).map(([key, field]) => {
      const flag = `--${key} <${key}>`
      return field.isOptional() ? `[${flag}]` : flag
    })
    return `| \`smthrs ${[name, ...args, ...options].join(" ")}\` | ${definition.description} |`
  }).sort()
  return `---\ntitle: "Host commands"\ndescription: "Commands for the self-hosted install."\n---\n\n<!-- Generated by scripts/catalog-mvp.ts from exported CLI definitions. -->\n\n| Command | Purpose |\n| --- | --- |\n${rows.join("\n")}\n\nRepeat \`--origin\` for each public origin. All commands accept \`--verbose\`.\n`
}
