import { installMigrationFixture } from './migration-fixture.mjs'
import assert from "node:assert/strict"
import { spawnSync } from "node:child_process"
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join, resolve } from "node:path"
import { test } from "node:test"

const script = resolve(import.meta.dirname, "commit.mjs")
const copyHygiene = (directory) => {
  installMigrationFixture(directory)
  // Exercise this checkout's production build CLI, rather than an installed release.
  const gateBin = join(directory, ".git/test-bin")
  mkdirSync(gateBin, { recursive: true })
  writeFileSync(join(gateBin, "smthrs"), `#!/bin/sh
exec "${process.execPath}" "${resolve(import.meta.dirname, "../packages/smithers/build/build-cli/src/main.ts")}" "$@"
`, { mode: 0o755 })
  mkdirSync(join(directory, "scripts"), { recursive: true })
  copyFileSync(resolve(import.meta.dirname, "check-tracked-hygiene.mjs"), join(directory, "scripts/check-tracked-hygiene.mjs"))
  rmSync(join(directory, "node_modules"), { recursive: true, force: true })
  rmSync(join(directory, "WORKSPACE.ts"), { force: true })
  symlinkSync(resolve(import.meta.dirname, "../node_modules"), join(directory, "node_modules"), "dir")
  writeFileSync(join(directory, ".gitignore"), "node_modules\n.flows/\n")
  writeFileSync(join(directory, "package.json"), '{"name":"landing-fixture","private":true,"packageManager":"pnpm@11.25.0"}\n')
  writeFileSync(join(directory, "yarn.lock"), "")
  writeFileSync(join(directory, "pnpm-workspace.yaml"), "verifyDepsBeforeRun: false\n")
  mkdirSync(join(directory, ".smithers"), { recursive: true })
  writeFileSync(join(directory, ".smithers/WORKSPACE.ts"), `import { Smithers as S } from "@smthrs/targets"
const packageJson = S.file("//package.json")
export const Workspace = S.Workspace("landing", {
  repository: "git+https://example.invalid/landing.git",
  cache: S.Cache({ directory: ".flows" }),
  runtime: S.Runtime.Node({ version: ">=26.4.0" }),
  packageManager: S.PackageManager.Pnpm({ version: "11.25.0", runtime: S.Runtime.Node({ version: ">=26.4.0" }) }),
  nodeModules: S.Npm.NodeModules({ packageJson }),
})
`)
  writeFileSync(join(directory, "PACKAGE.ts"), `import { Smithers as S } from "@smthrs/targets"
const workflow = (output) => S.GithubCiGen({ workflowName: "Fixture", output, mode: "check", concurrency: "commit", workflowDispatch: false,
  jobs: [{ id: "check", runsOn: "ubuntu-latest", toolchain: S.CiToolchain.Needs({ install: true }), steps: [{ verb: S.Verb.Lint, pattern: "//:targetIndex" }] }] })
export const Package = S.Package({ targets: { driftCi: workflow(".github/workflows/drift.yml"), targetIndex: S.TargetIndex({}), ci: workflow(".github/workflows/ci.yml") } })
`)
  writeFileSync(join(directory, "scripts/PACKAGE.ts"), `import { Smithers as S } from "@smthrs/targets"
export const Package = S.Package({ targets: {
  trackedHygiene: S.Shell.Diff({ shell: "node scripts/check-tracked-hygiene.mjs --projected-tree", sandbox: "none", changes: [] }),
  conflictMarkers: S.Shell.Diff({ shell: "! git grep --no-index -n '^<<<<<<< ' -- . ':!scripts/PACKAGE.ts' ':!node_modules'", sandbox: "none", changes: [] }),
} })
`)
  mkdirSync(join(directory, ".github/workflows"), { recursive: true })
  // Literal, independently specified workflow fixture; never generated by the test.
  const workflowBytes = [
    'name: "Fixture"', 'on:', '  push:', '    branches: ["main"]', '  pull_request:',
    'concurrency:', '  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}-${{ github.sha }}',
    '  cancel-in-progress: false', 'permissions:', '  contents: read', 'jobs:',
    '  "check":', '    runs-on: "ubuntu-latest"', '    steps:', '      - uses: "actions/checkout@11d5960a326750d5838078e36cf38b85af677262"',
    '      - uses: "pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86"',
    '      - id: setup', '        run: "pnpm install --frozen-lockfile --ignore-scripts"',
    "      - if: ${{ !cancelled() && steps.setup.conclusion == 'success' }}",
    `        run: "pnpm exec smthrs lint '//:targetIndex' --verbose"`, ''
  ].join("\n")
  for (const file of ["drift.yml", "ci.yml"]) writeFileSync(join(directory, ".github/workflows", file), workflowBytes)
  const indexed = spawnSync(process.execPath, [resolve(import.meta.dirname, "../packages/smithers/build/build-cli/src/main.ts"), "target", "//:targetIndex", "--write"], { cwd: directory, encoding: "utf8" })
  assert.equal(indexed.status, 0, indexed.stderr + indexed.stdout)

}
const command = (cwd, bin, args, environment = {}) => spawnSync(bin, args, { cwd, encoding: "utf8", env: { ...process.env, ...environment, PATH: `${join(cwd, ".git/test-bin")}:${process.env.PATH}`, HOME: join(cwd, ".git/test-home") } })
const ok = (cwd, bin, args) => {
  const result = command(cwd, bin, args)
  assert.equal(result.status, 0, result.stderr + result.stdout)
  return result.stdout.trim()
}
for (const vcs of ["git", "jj"]) {
  test(`${vcs}: commits all contributors, preserves main, ignores secrets, pushes only on request`, () => {
    const directory = mkdtempSync(join(tmpdir(), "smithers-commit-test-"))
    const remote = mkdtempSync(join(tmpdir(), "smithers-commit-remote-"))
    try {
      copyHygiene(directory)
      ok(directory, "git", ["init", "-b", "main"])
      ok(directory, "git", ["config", "user.name", "Commit test"])
      ok(directory, "git", ["config", "user.email", "test@example.com"])
      writeFileSync(join(directory, ".gitignore"), ".env\nnode_modules\n.flows/\n")
      ok(directory, "git", ["add", "."])
      ok(directory, "git", ["commit", "-m", "initial"])
      ok(remote, "git", ["init", "--bare", "-b", "main"])
      ok(directory, "git", ["remote", "add", "origin", remote])
      if (vcs === "jj") {
        ok(directory, "jj", ["git", "init", "--colocate"])
        ok(directory, "jj", ["config", "set", "--repo", "user.name", "Commit test"])
        ok(directory, "jj", ["config", "set", "--repo", "user.email", "test@example.com"])
      }
      writeFileSync(join(directory, "first.txt"), "first contributor\n")
      writeFileSync(join(directory, "second.txt"), "second contributor\n")
      writeFileSync(join(directory, ".env"), "ignored test data\n")
      ok(directory, "node", [script, "--message", "test: both contributors"])
      assert.equal(ok(directory, "git", ["log", "main", "-1", "--format=%s"]), "test: both contributors")
      assert.match(ok(directory, "git", ["show", "main:first.txt"]), /first contributor/)
      assert.match(ok(directory, "git", ["show", "main:second.txt"]), /second contributor/)
      assert.equal(ok(directory, "git", ["ls-tree", "--name-only", "main", ".env"]), "")
      assert.equal(ok(remote, "git", ["for-each-ref", "refs/heads/main"]), "")
      const before = ok(directory, "git", ["rev-parse", "main"])
      ok(directory, "node", [script, "--push", "--test", "true"])
      assert.equal(ok(remote, "git", ["rev-parse", "main"]), before)
      assert.equal(ok(directory, "git", ["rev-parse", "main"]), before)
      assert.equal(readFileSync(join(directory, ".env"), "utf8"), "ignored test data\n")
      if (vcs === "jj") {
        ok(directory, "jj", ["new"])
        writeFileSync(join(directory, "third.txt"), "unlanded lineage\n")
        const refused = command(directory, "node", [script])
        assert.notEqual(refused.status, 0)
        assert.match(refused.stderr, /must be on main/)
        assert.equal(ok(directory, "git", ["rev-parse", "main"]), before)
      }
    } finally {
      rmSync(directory, { recursive: true, force: true })
      rmSync(remote, { recursive: true, force: true })
    }
  })
  for (const finding of ["scaffold", "dangling", "untracked", "deleted"]) {
    test(`${vcs}: ${finding} hygiene failure prevents commit and requested push`, () => {
      const directory = mkdtempSync(join(tmpdir(), "smithers-commit-hygiene-test-"))
      const remote = mkdtempSync(join(tmpdir(), "smithers-commit-hygiene-remote-"))
      try {
        copyHygiene(directory)
        ok(directory, "git", ["init", "-b", "main"])
        ok(directory, "git", ["config", "user.name", "Commit test"])
        ok(directory, "git", ["config", "user.email", "test@example.com"])
        writeFileSync(join(directory, "PACKAGE.ts"), "const target = { paths: ['source.ts'] }\n")
        writeFileSync(join(directory, "source.ts"), "export const value = 1\n")
        ok(directory, "git", ["add", "."])
        ok(directory, "git", ["commit", "-m", "initial"])
        ok(remote, "git", ["init", "--bare", "-b", "main"])
        ok(directory, "git", ["remote", "add", "origin", remote])
        ok(directory, "git", ["push", "origin", "main"])
        if (vcs === "jj") {
          ok(directory, "jj", ["git", "init", "--colocate"])
          ok(directory, "jj", ["config", "set", "--repo", "user.name", "Commit test"])
          ok(directory, "jj", ["config", "set", "--repo", "user.email", "test@example.com"])
        }
        if (finding === "deleted") {
          rmSync(join(directory, "source.ts"))
        } else if (finding === "untracked") {
          writeFileSync(join(directory, "fresh.ts"), `export const path = 'scratchpad/${"lanes"}/a'\n`)
        } else if (finding === "scaffold") {
          writeFileSync(join(directory, "source.ts"), `export const path = 'scratchpad/${"lanes"}/a'\n`)
        } else {
          writeFileSync(join(directory, "PACKAGE.ts"), "const target = { paths: ['deleted.ts'] }\n")
        }
        const before = ok(directory, "git", ["rev-parse", "main"])
        const stagedBefore = ok(directory, "git", ["diff", "--cached"])
        const parentBefore = vcs === "jj" ? ok(directory, "jj", ["log", "-r", "@-", "--no-graph", "-T", "commit_id"]) : null
        const refused = command(directory, process.execPath, [script, "--message", "must not commit", "--push", "--test", "true"])
        assert.notEqual(refused.status, 0)
        assert.match(refused.stderr, finding === "deleted"
          ? /PACKAGE\.ts:1: dangling: paths names "source\.ts", which no tracked file matches/
          : finding === "dangling"
          ? /PACKAGE\.ts:1: dangling: paths names "deleted\.ts", which no tracked file matches/
          : finding === "untracked" ? /fresh\.ts:1: scaffold: lane scaffolding/ : /source\.ts:1: scaffold: lane scaffolding/)
        assert.match(refused.stderr, /tracked hygiene: 1 finding\(s\)/)
        assert.equal(ok(directory, "git", ["rev-parse", "main"]), before)
        assert.equal(ok(remote, "git", ["rev-parse", "main"]), before)
        assert.equal(ok(directory, "git", ["diff", "--cached"]), stagedBefore)
        if (vcs === "jj") {
          assert.equal(ok(directory, "jj", ["log", "-r", "@-", "--no-graph", "-T", "commit_id"]), parentBefore)
        }
        // A subsequent clean invocation proves the failed preflight released its lock.
        writeFileSync(join(directory, "PACKAGE.ts"), "const target = { paths: ['source.ts'] }\n")
        writeFileSync(join(directory, "source.ts"), "export const value = 1\n")
        if (finding === "untracked") rmSync(join(directory, "fresh.ts"))
        ok(directory, process.execPath, [script])
        assert.equal(ok(directory, "git", ["rev-parse", "main"]), before)
      } finally {
        rmSync(directory, { recursive: true, force: true })
        rmSync(remote, { recursive: true, force: true })
      }
    })
  }
}

for (const vcs of ["git", "jj"]) {
  for (const scenario of ["failure", "pipeline", "missing", "success", "waiver", "rejected", "moved", "repeat", "credentials"]) {
    test(`${vcs}: landing gate ${scenario}`, () => {
      const directory = mkdtempSync(join(tmpdir(), "smithers-landgate-"))
      const remote = mkdtempSync(join(tmpdir(), "smithers-landgate-remote-"))
      try {
        copyHygiene(directory)
        ok(directory, "git", ["init", "-b", "main"])
        ok(directory, "git", ["config", "user.name", "Commit test"])
        ok(directory, "git", ["config", "user.email", "test@example.com"])
        ok(directory, "git", ["add", "."])
        ok(directory, "git", ["commit", "-m", "initial"])
        ok(remote, "git", ["init", "--bare", "-b", "main"])
        ok(directory, "git", ["remote", "add", "origin", remote])
        ok(directory, "git", ["push", "origin", "main"])
        const before = ok(remote, "git", ["rev-parse", "main"])
        if (vcs === "jj") {
          ok(directory, "jj", ["git", "init", "--colocate"])
          ok(directory, "jj", ["config", "set", "--repo", "user.name", "Commit test"])
          ok(directory, "jj", ["config", "set", "--repo", "user.email", "test@example.com"])
        }
        if (vcs === "jj") ok(directory, "jj", ["bookmark", "track", "main", "--remote", "origin"])
        writeFileSync(join(directory, "change.txt"), "candidate\n")
        // Advance the actual remote from receive hooks, without a competing checkout.
        // pre-receive rejects the stale candidate; post-receive removes a pushed
        // candidate while returning success, exercising the fetched-main check.
        if (scenario === "rejected" || scenario === "moved") {
          const hook = scenario === "rejected" ? "pre-receive" : "post-receive"
          const tree = ok(remote, "git", ["rev-parse", `${before}^{tree}`])
          writeFileSync(join(remote, "hooks", hook), `#!/bin/sh
export GIT_AUTHOR_NAME=Remote GIT_AUTHOR_EMAIL=remote@example.com
export GIT_COMMITTER_NAME=Remote GIT_COMMITTER_EMAIL=remote@example.com
unset GIT_QUARANTINE_PATH
other=$(echo moved | git commit-tree ${tree} -p ${before})
git update-ref refs/heads/main "$other"
${scenario === "rejected" ? "exit 1" : ""}
`, { mode: 0o755 })
        }
        const testArgs = scenario === "missing" ? [] :
          scenario === "waiver" ? ["--no-test", "manual recovery"] :
          scenario === "credentials" ? ["--test", `node -e 'for (const key of ["GH_TOKEN", "GITHUB_TOKEN", "SMITHERS_GITHUB_PROXY"]) if (process.env[key] !== undefined) throw Error("credential leaked"); try { require("node:fs").readFileSync(require("node:path").join(require("node:os").homedir(), ".config/issue-claim/app.json")); process.exit(1) } catch (error) { if (error.code !== "ENOENT" && error.code !== "EACCES") throw error }'`] :
          scenario === "failure" ? ["--test", "exit 7"] :
          scenario === "pipeline" ? ["--test", "false | cat"] :
          scenario === "repeat" ? ["--test", "true", "--test", "exit 8"] :
          ["--test", "true", "--test", "printf passed"]
        const result = command(directory, process.execPath, [script, "--push", ...testArgs], scenario === "credentials" ? { GH_TOKEN: "fixture-canary", GITHUB_TOKEN: "fixture-canary", SMITHERS_GITHUB_PROXY: "fixture-canary" } : {})
        if (["success", "waiver", "credentials"].includes(scenario)) {
          assert.equal(result.status, 0, result.stderr + result.stdout)
          const sha = ok(remote, "git", ["rev-parse", "main"])
          assert.match(result.stdout, new RegExp(`LANDED ${sha}(?:\\n|$)`))
          assert.equal(ok(directory, "git", ["rev-parse", "refs/remotes/origin/main"]), sha)
          assert.match(ok(remote, "git", ["log", "-1", "--format=%B"]), scenario === "waiver"
            ? /Landing-Tests: none \(manual recovery\)/
            : scenario === "credentials" ? /Landing-Tests: node -e/ : /Landing-Tests: true; printf passed/)
        } else {
          assert.notEqual(result.status, 0)
          assert.match(result.stderr, /NOT LANDED/)
          assert.doesNotMatch(result.stdout, /^LANDED /m)
          if (["failure", "pipeline", "repeat"].includes(scenario)) {
            assert.match(result.stderr, /Test command failed:/)
            assert.match(result.stderr, scenario === "pipeline" ? /false \| cat/ : scenario === "repeat" ? /exit 8/ : /exit 7/)
          }
          if (scenario === "missing") assert.match(result.stderr, /--test/)
          if (["rejected", "moved"].includes(scenario)) {
            assert.notEqual(ok(remote, "git", ["rev-parse", "main"]), before)
            if (scenario === "moved") assert.equal(ok(directory, "git", ["rev-parse", "refs/remotes/origin/main"]), ok(remote, "git", ["rev-parse", "main"]))
          } else {
            assert.equal(ok(remote, "git", ["rev-parse", "main"]), before)
            assert.equal(ok(directory, "git", ["rev-parse", "main"]), before)
            assert.equal(ok(directory, "git", ["diff", "--cached"]), "")
            if (vcs === "jj") assert.equal(ok(directory, "jj", ["log", "-r", "@-", "--no-graph", "-T", "commit_id"]), before)
          }
        }
      } finally {
        rmSync(directory, { recursive: true, force: true })
        rmSync(remote, { recursive: true, force: true })
      }
    })
  }
}

for (const gate of ["driftCi", "targetIndex", "ci", "trackedHygiene", "conflictMarkers"]) {
  test(`git: mandatory ${gate} refuses --no-test before publication`, () => {
    const directory = mkdtempSync(join(tmpdir(), "smithers-drift-refusal-"))
    try {
      copyHygiene(directory)
      ok(directory, "git", ["init", "-b", "main"])
      ok(directory, "git", ["config", "user.name", "Commit test"])
      ok(directory, "git", ["config", "user.email", "test@example.com"])
      ok(directory, "git", ["add", "."])
      ok(directory, "git", ["commit", "-m", "initial"])
      const before = ok(directory, "git", ["rev-parse", "HEAD"])
      if (gate === "targetIndex") writeFileSync(join(directory, ".smithers/target-index.json"), "[]\n")
      else if (gate === "trackedHygiene") writeFileSync(join(directory, "leak.ts"), `export const leak = 'scratchpad/${"lanes"}/a'\n`)
      else if (gate === "conflictMarkers") writeFileSync(join(directory, "marker.txt"), "<<<<<<< broken\n")
      else writeFileSync(join(directory, ".github/workflows", gate === "driftCi" ? "drift.yml" : "ci.yml"), "name: Stale\n")
      const result = command(directory, process.execPath, [script, "--push", "--no-test", "manual recovery"])
      assert.notEqual(result.status, 0)
      assert.match(result.stderr, /NOT LANDED/)
      assert.doesNotMatch(result.stdout, /^LANDED /m)
      assert.equal(ok(directory, "git", ["rev-parse", "HEAD"]), before)
      assert.equal(ok(directory, "git", ["diff", "--cached"]), "")
    } finally { rmSync(directory, { recursive: true, force: true }) }
  })
}

test("git: credential store refuses before tests, gates and push", () => {
  const directory = mkdtempSync(join(tmpdir(), "smithers-credential-refusal-"))
  try {
    copyHygiene(directory)
    ok(directory, "git", ["init", "-b", "main"])
    const home = join(directory, ".git/test-home")
    mkdirSync(join(home, ".config/issue-claim"), { recursive: true })
    const result = command(directory, process.execPath, [script, "--push", "--test", "touch attempted"])
    assert.notEqual(result.status, 0)
    assert.match(result.stderr, /isolated home/)
    assert.throws(() => readFileSync(join(directory, "attempted")))
    assert.doesNotMatch(result.stdout, /^LANDED /m)
  } finally { rmSync(directory, { recursive: true, force: true }) }
})
