import assert from "node:assert/strict"
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join, resolve } from "node:path"
import { test } from "node:test"
import { checkout, command, fixtureEnv, ok, pending, recordEvidence, schemaFixture } from "./migration-fixture.mjs"
const script = resolve(import.meta.dirname, "renumber-migration.mjs")
const path = "packages/backend/db/product/migrations/0999_widget.sql"
// Execute the production default target shell, not a reduced replacement.
const declaration = readFileSync(resolve(import.meta.dirname,"../PACKAGE.ts"),"utf8")
const defaultShell = JSON.parse(/const backendGo = Smithers\.Shell\.Test\(\{\s*shell: (".*")/.exec(declaration)[1])
const env = { ...fixtureEnv }
for (const key of ["DATABASE_URL", "SMITHERS_TEST_DATABASE_URL", "SMITHERS_REQUIRE_DATABASE_TESTS"]) delete env[key]
const snapshot = directory => {
 const files = {}
 const visit = rel => {for (const f of readdirSync(join(directory, rel), { withFileTypes: true })) {
  if (f.name === ".git" || f.name === ".jj") continue
  const p = join(rel, f.name)
  if (f.isDirectory()) visit(p); else files[p] = readFileSync(join(directory, p)).toString("base64")
 }}
 visit("")
 return files
}
for (const vcs of ["git", "jj"]) {
 test(`${vcs}: quoted CSV reservation is converted`, () => {
  const dir = mkdtempSync(join(tmpdir(), "renumber-quoted-"))
  try {
   schemaFixture(dir); checkout(dir,vcs); pending(dir)
   writeFileSync(join(dir,"packages/backend/db/ownership.csv"), 'table,target_owner,status\nbase,product,installed\nwidget,product,"planned:T-FIX-01 owner:smithers-8a"\n')
   ok(dir,process.execPath,[script,path],env)
   assert.equal(readFileSync(join(dir,"packages/backend/db/ownership.csv"),"utf8"),"table,target_owner,status\nbase,product,installed\nwidget,product,installed:T-FIX-01 owner:smithers-8a\n")
  } finally {rmSync(dir,{recursive:true,force:true})}
 })
 test(`${vcs}: production renumber assigns 0002, converts reservation and uses pinned generator`, () => {
  const dir = mkdtempSync(join(tmpdir(), "renumber-fixture-"))
  try {
   schemaFixture(dir); checkout(dir, vcs); pending(dir)
   const baseline = readFileSync(join(dir, "packages/backend/db/product/migrations/0001_base.sql"))
   ok(dir, process.execPath, [script, path], env)
   // Oracles: spec.md §21.3 / C-PRC-02 step 4, literal fixture inventory 0001.
   assert.deepEqual(readdirSync(join(dir, "packages/backend/db/product/migrations")), ["0001_base.sql", "0002_widget.sql"])
   assert.match(readFileSync(join(dir, "packages/backend/db/product/migrate.go"), "utf8"), /\{2, "migrations\/0002_widget.sql"\}/)
   assert.equal(readFileSync(join(dir, "packages/backend/internal/db/models.go"), "utf8"),
    "// Code generated by sqlc. DO NOT EDIT.\n// versions:\n//   sqlc v1.30.0\n\npackage db\n\ntype Base struct {\n\tID int64\n}\n\ntype Widget struct {\n\tID int64\n}\n")
   assert.match(readFileSync(join(dir, "packages/backend/db/ownership.csv"), "utf8"), /widget,product,installed:T-FIX-01 owner:smithers-8a/)
   assert.deepEqual(readFileSync(join(dir, "packages/backend/db/product/migrations/0001_base.sql")), baseline)
   const before = snapshot(dir)
   const refused = command(dir, process.execPath, [script, "packages/backend/db/product/migrations/0001_base.sql"], env)
   assert.notEqual(refused.status, 0)
   assert.match(refused.stderr, /Refusing to renumber landed migration/)
   const after=snapshot(dir)
   recordEvidence(`${vcs}-renumber-and-landed-refusal`,{before,after,refused})
   assert.deepEqual(after, before)
  } finally {rmSync(dir, { recursive: true, force: true })}
 })
 for (const failure of ["missing origin", "shadow origin", "changed landed", "other reservation", "wrong sqlc", "invalid inventory", "generation failure", "unused conversion"]) {
  test(`${vcs}: ${failure} is refused`, () => {
   const dir = mkdtempSync(join(tmpdir(), "renumber-refusal-"))
   try {
    schemaFixture(dir); checkout(dir, vcs); pending(dir)
    if (failure === "missing origin" || failure === "shadow origin") ok(dir, "git", ["update-ref", "-d", "refs/remotes/origin/main"])
    if (failure === "shadow origin") ok(dir, "git", ["branch", "origin/main"])
    if (failure === "changed landed") writeFileSync(join(dir, "packages/backend/db/product/migrations/0001_base.sql"), "SELECT 1;\n")
    if (failure === "other reservation") writeFileSync(join(dir, path), "-- Ticket: T-FIX-02\nCREATE TABLE widget (id bigint);\n")
    if (failure === "invalid inventory") writeFileSync(join(dir, "packages/backend/db/product/migrations/0003_gap.sql"), "SELECT 1;")
    if (failure === "generation failure") writeFileSync(join(dir,path),"-- Ticket: T-FIX-01\nCREATE TABLE widget (id bigint PRIMARY KEY,);\n")
    if (failure === "unused conversion") writeFileSync(join(dir,"packages/backend/db/ownership.csv"),"table,target_owner,status\nbase,product,installed\nwidget,product,planned:T-FIX-01 owner:smithers-8a\nunused,product,planned:T-FIX-01 owner:smithers-8a\n")
    const before = snapshot(dir)
    const badEnv = failure === "wrong sqlc" ? { ...env, PATH: "/usr/bin:/bin" } : env
    const result = command(dir, process.execPath, [script, path], badEnv)
    recordEvidence(`${vcs}-refusal-${failure}`,{before,after:snapshot(dir),result})
    assert.notEqual(result.status, 0, result.stdout + result.stderr)
    if (failure === "other reservation") assert.match(result.stdout + result.stderr, /reserved for T-FIX-01/)
    assert.deepEqual(snapshot(dir), before)
   } finally {rmSync(dir, { recursive: true, force: true })}
  })
 }
}

// Simulate the kernel UID observation in a child process; no privileged process
// or credentials are needed to prove refusal precedes repository/tool access.
test("C-PRC-02/generator-uid-before-repository-use", () => {
 const dir = mkdtempSync(join(tmpdir(), "renumber-uid-"))
 try {
  schemaFixture(dir); checkout(dir,"git"); pending(dir)
  const preload=join(dir,"uid.mjs")
  writeFileSync(preload,"process.getuid = () => 0;\n")
  const before=snapshot(dir)
  const result=command(dir,process.execPath,["--import",preload,script,"does-not-exist.sql"],env)
  recordEvidence("generator-uid-before-repository-use",{before,after:snapshot(dir),result})
  assert.notEqual(result.status,0)
  assert.match(result.stderr,/must run as an unprivileged machine user/)
  assert.deepEqual(snapshot(dir),before)
 } finally {rmSync(dir,{recursive:true,force:true})}
})

for (const [name,sql,rows,want] of [
 ["duplicate numbers","SELECT 1;",null,"duplicate migration number 0001"],
 ["gap","SELECT 1;",null,"gap: no migration numbered 0002"],
 ["registry parity","-- Ticket: T-FIX-01\nCREATE TABLE widget (id bigint);",null,"2 embedded files, 1 registry entries"],
 ["duplicate create","CREATE TABLE base (id bigint);",null,"base is created by both"],
 ["duplicate if not exists","CREATE TABLE IF NOT EXISTS base (id bigint);",null,"base is created by both"],
 ["unowned","CREATE TABLE ghost (id bigint);",null,"ghost (created by 0002_widget.sql) has no row"],
 ["dropped ownership","DROP TABLE base;",null,"product table base that no migration leaves installed"],
 ["wrong reservation","-- Ticket: T-FIX-02\nCREATE TABLE widget (id bigint);",null,"reserved for T-FIX-01"],
 ["partition parent missing","CREATE TABLE parent (id bigint) PARTITION BY RANGE (id); CREATE TABLE child PARTITION OF parent FOR VALUES FROM (0) TO (10);",null,"parent (created by 0002_widget.sql) has no row"],
 ["partition valid","CREATE TABLE parent (id bigint) PARTITION BY RANGE (id); CREATE TABLE child PARTITION OF parent FOR VALUES FROM (0) TO (10);","table,target_owner,status\nbase,product,installed\nparent,product,installed\n",null],
]) {
 test(`default Go invocation and selected gate: ${name}`,()=>{
  const dir=mkdtempSync(join(tmpdir(),"migration-gate-process-"))
  try {
   schemaFixture(dir); checkout(dir,"git")
   const migrationName=name==="duplicate numbers" ? "0001_widget.sql" : name==="gap" ? "0003_widget.sql" : "0002_widget.sql"
   pending(dir,migrationName)
   writeFileSync(join(dir,"packages/backend/db/product/migrations",migrationName),sql)
   if (rows) writeFileSync(join(dir,"packages/backend/db/ownership.csv"),rows)
   if (name==="registry parity") {
    const path=join(dir,"packages/backend/db/product/migrate.go")
    writeFileSync(path,readFileSync(path,"utf8").replace(' {2, "migrations/0002_widget.sql"},',""))
   }
   const unavailable = join(dir,"unavailable-postgres")
   mkdirSync(unavailable)
   const calls = join(unavailable,"calls")
   for (const bin of ["postgres","psql","initdb","pg_ctl"]) writeFileSync(join(unavailable,bin),`#!/bin/sh\necho called >> "${calls}"\nexit 99\n`,{mode:0o755})
   const noDbEnv = {...env, PATH:`${unavailable}:${env.PATH}`, SMITHERS_POSTGRES_TEST_BIN:unavailable}
   const results=[]
   for (const [bin,args] of [["/bin/sh",["-c",defaultShell]],["go",["test","-run","TestMigrationGate|TestMigrationRegistry","./packages/backend/db/product/"]]]) {
    const result=command(dir,bin,args,noDbEnv);results.push({bin,args,result})
    if (want) {assert.notEqual(result.status,0);assert.ok((result.stdout+result.stderr).includes(want),result.stdout+result.stderr)}
    else assert.equal(result.status,0,result.stdout+result.stderr)
   }
   assert.equal(existsSync(calls),false,"PostgreSQL must remain unavailable and unused")
   recordEvidence(`gate-${name}`,{fixture:snapshot(dir),results})
  } finally {rmSync(dir,{recursive:true,force:true})}
 })
}
