/*
 * Every flow name the app declares, as a type.
 *
 * The card seam used to take `(name: string, args?: string)`, so
 * `"targets.select"` compiled exactly as readily as `"target.select"` and the
 * mistake only surfaced as a button that did nothing. The names are literals
 * in the entries modules and nowhere else, so this module lists them once and
 * derives the union; FlowName.test.ts holds the list and the registry to each
 * other, in both directions, by reading the entries modules as text.
 *
 * A flow declared at RUNTIME (a repository's flow leaf, entries/flow.ts) is
 * not here: its name arrives with a projection. A caller holding such a name
 * has a plain string and dispatches it as one.
 */

/**
 * Flow names persisted rows may still carry (a message's action, a saved
 * sign-in prompt) under the name a flow had before mvp.md Appendix A renamed
 * it. Decoding maps each to the flow that answers today, so an old row's
 * button still runs; nothing writes these names.
 */
export const RENAMED_FLOWS: Readonly<Record<string, string>> = {
  "prs": "pr", "prs.list": "pr", "prs.view": "pr",
  "box.list": "branches",
  "box.open": "branch",
  "box.view": "branch",
  "flow.run.stop": "flow.run",
  "flow.run.retry": "flow.run",
  "flow.run.stop-all": "flow.run",
  "change.view": "diff",
  "change.diff": "diff",
  "change.pins": "diff",
  "change.checks": "diff",
  "files.open-diff": "diff",

  "files.list": "files",
  "repo.tree": "files",
  "box.files": "files",
  "box.file": "file",
  "files.read": "file",
  "proposal": "wiki",
  "terminal.send": "terminal",
  "flow.list": "flows",
  "settings.address": "settings",
  "settings.capacity": "settings",
  "settings.parallel": "settings",
  "settings.preapprove-default": "settings",
  "settings.daily-admissions": "settings",
  "settings.obsidian": "settings",
  "settings.model-key": "settings",
  "settings.setup": "settings",
  "settings.fast-model": "settings",
  "issue.implement": "todo.from-issue",
  "history.show": "stack",
  "appearance.dark-mode": "theme",
  "chat.stop": "stop",
  "search.open": "search",
  "auth.sign-in": "sign-in",
  "auth.sign-out": "sign-out",
  "chat.commands": "help",
  "branches.list": "branches",
  "agent.list": "agents",
  "secrets.set": "secrets",
  "secrets.delete": "secrets",
  "secrets.scope": "secrets",
  "secrets.bind": "secrets",
  "secrets.list": "secrets",
  "flow.create": "flow.new",
  "model": "agents",
  "agent.open": "agent",
  "agent.codex": "agents",
  "agent.claude": "agents",
  "agent.model": "model.assign",
  "debug.api": "debug-api",
  "debug.seams": "debug.backend",
  "run.view": "runs.trace.view",
  "context.inspect": "run.inspect",
  "runs.attention": "runs",
  "approvals.open": "runs",
  "approvals.list": "runs",
  "secrets.connect": "settings",
  "secrets.connect.codex": "settings",
  "secrets.connections": "settings",
  "secrets.move": "settings",
  "secrets.revoke": "settings",
  "github.app": "github",
  "github.reconcile": "github",
  "github.app.choose": "github",
  "github.app.open": "github",
  "github.retry": "github",
  "docs.read": "docs",
  "prs.triage": "review",
  "env.view": "settings",
  "env.set": "settings",
  "env.remove-token": "settings"
}
export const currentFlowName = (name: string): string => RENAMED_FLOWS[name] ?? name

/** Every flow name declared under flows/entries, in sorted order. */
export const FLOW_NAMES = [
  "todo.preapprove",
  "todo.unapprove",
  "image.add",
  "todo.return-to-item",
  "todo.keep-moved",
  "branch.bring-in",
  "branch.discard-foreign",
  "file.compare",
  "file.reapply",
  "file.restore-deleted",
  "file.follow-rename",
  "branch.rebase-now",
  "learning.accept",
  "learning.dismiss",
  "todo.takeover",
  "merge.confirm",
  "order.ok",
  "main.reset-to-github",
  "settings.model.set",
  "code.hover",
  "code.definition",
  "code.diagnostics",

  "agent",
  "agent.edit",
  "monitor",
  "stack",
  "stack.move",
  "merge",
  "background.retry",
  "background.dismiss",
  "github",
  "notifications.allow",
  "settings",
  "members",
  "members.add",
  "members.role",
  "members.remove",
  "help",
  "account.show",
  "admin.devtools",
  "admin.reset",
  "admin.reset.ask",
  "admin.reset.cancel",
  "agents",
  "model.list",
  "model.new",
  "model.edit",
  "model.save",
  "model.show",
  "model.remove",
  "model.test",
  "model.assign",
  "app.hint.dismiss",
  "theme",
  "approval.approve",
  "approval.deny",
  "auth.email",
  "auth.prompt",
  "sign-in",
  "sign-out",
  "billing.balance",
  "billing.plans",
  "billing.portal",
  "billing.upgrade",
  "branch",
  "box.delete",
  "box.egress",
  "box.facet",
  "box.images",
  "box.resume",
  "box.services",
  "box.session.destroy",
  "box.suspend",
  "branches",
  "branch.fork",
  "branch.archive",
  "branch.add-to-stack",
  "branch.rebase",
  "terminal",
  "terminal.watch",
  "ssh",
  "browser.open",
  "card.dismiss",
  "card.history.back",
  "card.history.forward",
  "card.maximize",
  "card.minimize",
  "change.facet",
  "change.resolve",
  "chat",
  "chat.copy-message",
  "chat.dictate",
  "chat.open",
  "chat.queue",
  "chat.queue.edit",
  "chat.queue.remove",
  "chat.queue.restore",
  "chat.reload",
  "chat.retry",
  "chat.send",
  "stop",
  "cloud.prompt",
  "cloud.sign-in",
  "cloud.sign-out",
  "debug.backend",
  "debug.errors",
  "debug.events",
  "debug.net",
  "debug.reset",
  "debug.snapshot",
  "debug.verbose",
  "debug-api",
  "docs",
  "egress.allow",
  "egress.session",
  "findings.not-useful",
  "findings.please-fix",
  "flow",
  "flow.new",
  "flow.edit",
  "flow.plan",
  "flow.plan.select",
  "flow.plan.tab",
  "flow.run",
  "flow.source",
  "flows",
  "form.set",
  "form.submit",
  "frame.back",
  "frame.forward",
  "github.mirror-sync",
  "github.mirror.retry-ref",
  "history.bootstrap",
  "input.mode",
  "issue.add-flow",
  "issue.flows",
  "todo.from-issue",
  "issue.poc",
  "issue.repro",
  "issues.close",
  "issues.comment",
  "issues.create",
  "issues.list",
  "issues.reopen",
  "issues.view",
  "palette.actions",
  "palette.open",
  "palette.recent",
  "prs.review",
  "prs.tab",
  "review",
  "repo.choose",
  "repo.create",
  "repo.overview",
  "repo.select",
  "repo.update",
  "repos.import",
  "repos.import.retry",
  "review.ack",
  "review.done",
  "review.reopen",
  "review.request",
  "review.since-mine",
  "review.unrequest",
  "run",
  "run.inspect",
  "runs",
  "runs.coding.select",
  "runs.events",
  "runs.graph.follow",
  "runs.graph.execution",
  "runs.graph.select",
  "runs.graph.tab",
  "runs.list",
  "runs.logs",
  "runs.open",
  "runs.rerun",
  "runs.resume",
  "runs.continue",
  "runs.signal",
  "runs.steps",
  "runs.trace.filter",
  "runs.trace.live",
  "runs.trace.select",
  "runs.trace.view",
  "search",
  "secrets",
  "storage.recovery",
  "storage.recovery.export",
  "storage.recovery.reset",
  "sync.ops.show-more",
  "todo",
  "draft.discard",
  "confirm.cancel",
  "todo.new",
  "todo.answer",
  "todo.steer",
  "todo.amend",
  "todo.stop",
  "todo.resume",
  "todo.retry",
  "todo.retry-current-flow",
  "todo.drop",
  "wiki.save",
  "toast.dismiss",
  "triggers.approve",
  "triggers.list",
  "triggers.pause",
  "triggers.register",
  "triggers.resume",
  "triggers.run",
  "wiki",
  "wiki.page",
  "issue",
  "issues",
  "issue.new",
  "issue.comment",
  "file",
  "files",
  "file.restore",
  "diff",
  "pr",
  "wiki.attach",
  "wiki.backlinks",
  "wiki.card.select",
  "wiki.card.view",
  "wiki.cloud",
  "wiki.cloud.delete",
  "wiki.cloud.new",
  "wiki.cloud.open",
  "wiki.cloud.rename",
  "wiki.create",
  "wiki.delete",
  "wiki.delete.cancel",
  "wiki.delete.confirm",
  "wiki.edit",
  "wiki.graph",
  "wiki.heading",
  "wiki.history",
  "wiki.new-note",
  "wiki.open",
  "wiki.pane",
  "wiki.select",
  "wiki.space",
  "wiki.sync",
  "wiki.view",
] as const

/** The name of one declared flow: what the card seam and the tabs may raise. */
export type FlowName = (typeof FLOW_NAMES)[number]
