// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActivityBySourceKey = `-- name: GetActivityBySourceKey :one
SELECT id, branch_id, seq, at, actor, asked_by, kind, summary, burst_id, snapshot_before, snapshot_after, files, github, source_key FROM activity WHERE branch_id = $1 AND source_key = $2
`

type GetActivityBySourceKeyParams struct {
	BranchID  string      `json:"branch_id"`
	SourceKey pgtype.Text `json:"source_key"`
}

func (q *Queries) GetActivityBySourceKey(ctx context.Context, arg GetActivityBySourceKeyParams) (Activity, error) {
	row := q.db.QueryRow(ctx, getActivityBySourceKey, arg.BranchID, arg.SourceKey)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Seq,
		&i.At,
		&i.Actor,
		&i.AskedBy,
		&i.Kind,
		&i.Summary,
		&i.BurstID,
		&i.SnapshotBefore,
		&i.SnapshotAfter,
		&i.Files,
		&i.Github,
		&i.SourceKey,
	)
	return i, err
}

const insertActivity = `-- name: InsertActivity :one
INSERT INTO activity (branch_id, seq, actor, asked_by, kind, summary, source_key)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, branch_id, seq, at, actor, asked_by, kind, summary, burst_id, snapshot_before, snapshot_after, files, github, source_key
`

type InsertActivityParams struct {
	BranchID  string          `json:"branch_id"`
	Seq       int64           `json:"seq"`
	Actor     json.RawMessage `json:"actor"`
	AskedBy   []byte          `json:"asked_by"`
	Kind      string          `json:"kind"`
	Summary   json.RawMessage `json:"summary"`
	SourceKey pgtype.Text     `json:"source_key"`
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, insertActivity,
		arg.BranchID,
		arg.Seq,
		arg.Actor,
		arg.AskedBy,
		arg.Kind,
		arg.Summary,
		arg.SourceKey,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Seq,
		&i.At,
		&i.Actor,
		&i.AskedBy,
		&i.Kind,
		&i.Summary,
		&i.BurstID,
		&i.SnapshotBefore,
		&i.SnapshotAfter,
		&i.Files,
		&i.Github,
		&i.SourceKey,
	)
	return i, err
}

const listBranchActivity = `-- name: ListBranchActivity :many
SELECT id, branch_id, seq, at, actor, asked_by, kind, summary, burst_id, snapshot_before, snapshot_after, files, github, source_key FROM (
    SELECT id, branch_id, seq, at, actor, asked_by, kind, summary, burst_id, snapshot_before, snapshot_after, files, github, source_key FROM activity WHERE branch_id = $1 ORDER BY seq DESC LIMIT $2
) newest
ORDER BY seq
`

type ListBranchActivityParams struct {
	BranchID string `json:"branch_id"`
	RowLimit int32  `json:"row_limit"`
}

// The branch's newest entries, oldest first.
func (q *Queries) ListBranchActivity(ctx context.Context, arg ListBranchActivityParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listBranchActivity, arg.BranchID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Seq,
			&i.At,
			&i.Actor,
			&i.AskedBy,
			&i.Kind,
			&i.Summary,
			&i.BurstID,
			&i.SnapshotBefore,
			&i.SnapshotAfter,
			&i.Files,
			&i.Github,
			&i.SourceKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBranchForActivity = `-- name: LockBranchForActivity :one

SELECT branch_id::text AS id FROM todos WHERE branch_id = $1::uuid FOR UPDATE
`

// Branch activity (spec §3, §7.2; services/activity.go is the only writer).
// Serializes a branch's activity writers, so seq is gap-free in commit order.
func (q *Queries) LockBranchForActivity(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockBranchForActivity, id)
	err := row.Scan(&id)
	return id, err
}

const nextActivitySeq = `-- name: NextActivitySeq :one
SELECT (COALESCE(MAX(seq), 0) + 1)::bigint AS seq FROM activity WHERE branch_id = $1
`

func (q *Queries) NextActivitySeq(ctx context.Context, branchID string) (int64, error) {
	row := q.db.QueryRow(ctx, nextActivitySeq, branchID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}
