// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_manage.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminBlockUserLoginForErasure = `-- name: AdminBlockUserLoginForErasure :execrows
UPDATE users SET prohibit_login = true, updated_at = now()
WHERE id = $1::bigint AND NOT prohibit_login
`

// Blocks sign-in and every authenticated request (middleware checks
// prohibit_login) while the erase tears down owned resources; the account
// stays active so repository services still resolve it. The final sweep
// deletes its sessions.
func (q *Queries) AdminBlockUserLoginForErasure(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, adminBlockUserLoginForErasure, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminCountUserLiveResources = `-- name: AdminCountUserLiveResources :one
SELECT
  (SELECT count(*) FROM repositories r WHERE r.user_id = $1::bigint)::bigint AS repositories,
  (SELECT count(*) FROM workspaces w WHERE w.user_id = $1::bigint AND w.deleted_at IS NULL)::bigint AS workspaces
`

type AdminCountUserLiveResourcesRow struct {
	Repositories int64 `json:"repositories"`
	Workspaces   int64 `json:"workspaces"`
}

func (q *Queries) AdminCountUserLiveResources(ctx context.Context, userID int64) (AdminCountUserLiveResourcesRow, error) {
	row := q.db.QueryRow(ctx, adminCountUserLiveResources, userID)
	var i AdminCountUserLiveResourcesRow
	err := row.Scan(&i.Repositories, &i.Workspaces)
	return i, err
}

const adminDeleteUserChatTurns = `-- name: AdminDeleteUserChatTurns :execrows
DELETE FROM chat_turns WHERE user_id = $1::bigint OR repository_id = ANY($2::bigint[])
`

type AdminDeleteUserChatTurnsParams struct {
	UserID        int64   `json:"user_id"`
	RepositoryIds []int64 `json:"repository_ids"`
}

func (q *Queries) AdminDeleteUserChatTurns(ctx context.Context, arg AdminDeleteUserChatTurnsParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteUserChatTurns, arg.UserID, arg.RepositoryIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteUserIssueStateFacts = `-- name: AdminDeleteUserIssueStateFacts :execrows
DELETE FROM issue_state_facts WHERE audience_user_id = $1::bigint
`

func (q *Queries) AdminDeleteUserIssueStateFacts(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteUserIssueStateFacts, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteUserNotificationFacts = `-- name: AdminDeleteUserNotificationFacts :execrows
DELETE FROM notification_facts WHERE user_id = $1::bigint
`

func (q *Queries) AdminDeleteUserNotificationFacts(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteUserNotificationFacts, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminExportComments = `-- name: AdminExportComments :one
SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY x.created_at, x.id), '[]'::jsonb)::jsonb AS items FROM (
  SELECT c.id, 'issue' AS parent, COALESCE(ou.username, o.name) || '/' || r.name AS repository, i.number,
    '' AS path, 0::bigint AS line, c.body, c.created_at, c.updated_at
  FROM issue_comments c
  JOIN issues i ON i.id = c.issue_id
  JOIN repositories r ON r.id = i.repository_id
  LEFT JOIN users ou ON ou.id = r.user_id
  LEFT JOIN organizations o ON o.id = r.org_id
  WHERE c.user_id = $1::bigint
  UNION ALL
  SELECT c.id, 'landing_request', COALESCE(ou.username, o.name) || '/' || r.name, l.number,
    c.path, c.line, c.body, c.created_at, c.updated_at
  FROM landing_request_comments c
  JOIN landing_requests l ON l.id = c.landing_request_id
  JOIN repositories r ON r.id = l.repository_id
  LEFT JOIN users ou ON ou.id = r.user_id
  LEFT JOIN organizations o ON o.id = r.org_id
  WHERE c.user_id = $1::bigint
) x
`

// Comments the user wrote on issues and landing requests.
func (q *Queries) AdminExportComments(ctx context.Context, userID int64) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, adminExportComments, userID)
	var items json.RawMessage
	err := row.Scan(&items)
	return items, err
}

const adminExportIssues = `-- name: AdminExportIssues :one
SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY x.id), '[]'::jsonb)::jsonb AS items FROM (
  SELECT i.id, COALESCE(ou.username, o.name) || '/' || r.name AS repository, i.number, i.title, i.body, i.state,
    i.author_id = $1::bigint AS authored, i.created_at, i.updated_at, i.closed_at
  FROM issues i
  JOIN repositories r ON r.id = i.repository_id
  LEFT JOIN users ou ON ou.id = r.user_id
  LEFT JOIN organizations o ON o.id = r.org_id
  WHERE i.author_id = $1::bigint OR r.user_id = $1::bigint
) x
`

// Issues the user wrote anywhere, and every issue in the user's repositories.
func (q *Queries) AdminExportIssues(ctx context.Context, userID int64) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, adminExportIssues, userID)
	var items json.RawMessage
	err := row.Scan(&items)
	return items, err
}

const adminExportLandingRequests = `-- name: AdminExportLandingRequests :one
SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY x.id), '[]'::jsonb)::jsonb AS items FROM (
  SELECT l.id, COALESCE(ou.username, o.name) || '/' || r.name AS repository, l.number, l.title, l.body, l.state,
    l.target_bookmark, l.source_bookmark, l.author_id = $1::bigint AS authored,
    l.created_at, l.updated_at, l.closed_at, l.merged_at
  FROM landing_requests l
  JOIN repositories r ON r.id = l.repository_id
  LEFT JOIN users ou ON ou.id = r.user_id
  LEFT JOIN organizations o ON o.id = r.org_id
  WHERE l.author_id = $1::bigint OR r.user_id = $1::bigint
) x
`

// Landing requests the user opened anywhere, and every one in the user's repositories.
func (q *Queries) AdminExportLandingRequests(ctx context.Context, userID int64) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, adminExportLandingRequests, userID)
	var items json.RawMessage
	err := row.Scan(&items)
	return items, err
}

const adminExportProfile = `-- name: AdminExportProfile :one
SELECT to_jsonb(p)::jsonb AS item FROM (
  SELECT u.id, u.username, u.email, u.display_name, u.bio, u.avatar_url, u.wallet_address, u.created_at,
    COALESCE((SELECT jsonb_agg(jsonb_build_object('name', k.name, 'fingerprint', k.fingerprint, 'public_key', k.public_key, 'created_at', k.created_at) ORDER BY k.id)
      FROM ssh_keys k WHERE k.user_id = u.id), '[]'::jsonb) AS ssh_keys
  FROM users u WHERE u.id = $1::bigint
) p
`

// Account export: the profile the user entered and the keys it signs in with.
func (q *Queries) AdminExportProfile(ctx context.Context, userID int64) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, adminExportProfile, userID)
	var item json.RawMessage
	err := row.Scan(&item)
	return item, err
}

const adminExportRepositories = `-- name: AdminExportRepositories :one
SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY x.name), '[]'::jsonb)::jsonb AS items FROM (
  SELECT r.id, r.name, r.description, r.is_public, r.default_bookmark, r.created_at, r.updated_at
  FROM repositories r WHERE r.user_id = $1::bigint
) x
`

func (q *Queries) AdminExportRepositories(ctx context.Context, userID int64) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, adminExportRepositories, userID)
	var items json.RawMessage
	err := row.Scan(&items)
	return items, err
}

const adminExportRuns = `-- name: AdminExportRuns :one
SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY x.created_at, x.id), '[]'::jsonb)::jsonb AS items FROM (
  SELECT w.id::text AS id, 'workflow_run' AS kind, r.name AS repository, d.name AS title, w.status::text AS status,
    w.trigger_event::text AS trigger_event, w.trigger_ref::text AS trigger_ref, w.trigger_commit_sha::text AS commit_sha,
    w.created_at, w.started_at, w.completed_at AS finished_at
  FROM workflow_runs w
  JOIN repositories r ON r.id = w.repository_id
  JOIN workflow_definitions d ON d.id = w.workflow_definition_id
  WHERE r.user_id = $1::bigint
  UNION ALL
  SELECT s.id::text, 'agent_session', COALESCE(ou.username, o.name) || '/' || r.name, s.title::text, s.status::text,
    '', '', '', s.created_at, s.started_at, s.finished_at
  FROM agent_sessions s
  JOIN repositories r ON r.id = s.repository_id
  LEFT JOIN users ou ON ou.id = r.user_id
  LEFT JOIN organizations o ON o.id = r.org_id
  WHERE s.user_id = $1::bigint AND s.deleted_at IS NULL
) x
`

// Run metadata: workflow runs in the user's repositories and the user's
// agent sessions. Logs and tokens are not part of the metadata.
func (q *Queries) AdminExportRuns(ctx context.Context, userID int64) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, adminExportRuns, userID)
	var items json.RawMessage
	err := row.Scan(&items)
	return items, err
}

const adminFindErasedUser = `-- name: AdminFindErasedUser :one
SELECT id, username, lower_username, email, lower_email, display_name, bio, search_vector, avatar_url, wallet_address, user_type, is_active, is_admin, prohibit_login, email_notifications_enabled, last_login_at, deleted_at, created_at, updated_at, is_synthetic FROM users
WHERE lower_username LIKE $1::text || '%'
AND deleted_at IS NOT NULL AND NOT is_active
AND created_at < $2::timestamptz
ORDER BY id DESC LIMIT 1
`

type AdminFindErasedUserParams struct {
	TombstonePrefix string    `json:"tombstone_prefix"`
	CreatedBefore   time.Time `json:"created_before"`
}

// The newest tombstone for a username whose account existed before the
// deletion request, so a retry never resolves to a later holder of the name.
func (q *Queries) AdminFindErasedUser(ctx context.Context, arg AdminFindErasedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, adminFindErasedUser, arg.TombstonePrefix, arg.CreatedBefore)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.LowerUsername,
		&i.Email,
		&i.LowerEmail,
		&i.DisplayName,
		&i.Bio,
		&i.SearchVector,
		&i.AvatarUrl,
		&i.WalletAddress,
		&i.UserType,
		&i.IsActive,
		&i.IsAdmin,
		&i.ProhibitLogin,
		&i.EmailNotificationsEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSynthetic,
	)
	return i, err
}

const adminGetUserForErasure = `-- name: AdminGetUserForErasure :one
SELECT id, username, lower_username, email, lower_email, display_name, bio, search_vector, avatar_url, wallet_address, user_type, is_active, is_admin, prohibit_login, email_notifications_enabled, last_login_at, deleted_at, created_at, updated_at, is_synthetic FROM users WHERE lower_username = $1
`

// Unlike GetUserByLowerUsername this also finds a suspended user, so an erase
// interrupted after suspension can resume.
func (q *Queries) AdminGetUserForErasure(ctx context.Context, lowerUsername string) (User, error) {
	row := q.db.QueryRow(ctx, adminGetUserForErasure, lowerUsername)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.LowerUsername,
		&i.Email,
		&i.LowerEmail,
		&i.DisplayName,
		&i.Bio,
		&i.SearchVector,
		&i.AvatarUrl,
		&i.WalletAddress,
		&i.UserType,
		&i.IsActive,
		&i.IsAdmin,
		&i.ProhibitLogin,
		&i.EmailNotificationsEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSynthetic,
	)
	return i, err
}

const adminGetUserForSuspension = `-- name: AdminGetUserForSuspension :one
SELECT id, username, lower_username, email, lower_email, display_name, bio, search_vector, avatar_url, wallet_address, user_type, is_active, is_admin, prohibit_login, email_notifications_enabled, last_login_at, deleted_at, created_at, updated_at, is_synthetic FROM users
WHERE lower_username = $1
AND deleted_at IS NULL
`

func (q *Queries) AdminGetUserForSuspension(ctx context.Context, lowerUsername string) (User, error) {
	row := q.db.QueryRow(ctx, adminGetUserForSuspension, lowerUsername)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.LowerUsername,
		&i.Email,
		&i.LowerEmail,
		&i.DisplayName,
		&i.Bio,
		&i.SearchVector,
		&i.AvatarUrl,
		&i.WalletAddress,
		&i.UserType,
		&i.IsActive,
		&i.IsAdmin,
		&i.ProhibitLogin,
		&i.EmailNotificationsEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSynthetic,
	)
	return i, err
}

const adminListAgentSessions = `-- name: AdminListAgentSessions :many

SELECT s.id, s.repository_id, s.user_id, s.workflow_run_id, s.title, s.status, s.metadata, s.workspace_id, s.started_at, s.finished_at, s.created_at, s.updated_at, s.deleted_at, u.username AS username,
       (COALESCE(ru.username, o.name, '') || '/' || r.name)::text AS repository
FROM agent_sessions s JOIN users u ON u.id = s.user_id
JOIN repositories r ON r.id = s.repository_id
LEFT JOIN users ru ON ru.id = r.user_id LEFT JOIN organizations o ON o.id = r.org_id
WHERE s.deleted_at IS NULL AND ($1::text = 'all' OR s.status = $1)
AND ($2::boolean OR NOT u.is_synthetic)
ORDER BY s.created_at DESC, s.id DESC LIMIT $3::int
`

type AdminListAgentSessionsParams struct {
	Status           string `json:"status"`
	IncludeSynthetic bool   `json:"include_synthetic"`
	RowLimit         int32  `json:"row_limit"`
}

type AdminListAgentSessionsRow struct {
	AgentSession AgentSession `json:"agent_session"`
	Username     string       `json:"username"`
	Repository   string       `json:"repository"`
}

// Product queries extracted from the transitional Plue source.
func (q *Queries) AdminListAgentSessions(ctx context.Context, arg AdminListAgentSessionsParams) ([]AdminListAgentSessionsRow, error) {
	rows, err := q.db.Query(ctx, adminListAgentSessions, arg.Status, arg.IncludeSynthetic, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListAgentSessionsRow{}
	for rows.Next() {
		var i AdminListAgentSessionsRow
		if err := rows.Scan(
			&i.AgentSession.ID,
			&i.AgentSession.RepositoryID,
			&i.AgentSession.UserID,
			&i.AgentSession.WorkflowRunID,
			&i.AgentSession.Title,
			&i.AgentSession.Status,
			&i.AgentSession.Metadata,
			&i.AgentSession.WorkspaceID,
			&i.AgentSession.StartedAt,
			&i.AgentSession.FinishedAt,
			&i.AgentSession.CreatedAt,
			&i.AgentSession.UpdatedAt,
			&i.AgentSession.DeletedAt,
			&i.Username,
			&i.Repository,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListErasureSnapshots = `-- name: AdminListErasureSnapshots :many
SELECT s.id, s.repository_id, s.user_id FROM workspace_snapshots s
WHERE s.user_id = $1::bigint OR s.repository_id IN (SELECT r.id FROM repositories r WHERE r.user_id = $1::bigint)
ORDER BY s.created_at, s.id
`

type AdminListErasureSnapshotsRow struct {
	ID           string `json:"id"`
	RepositoryID int64  `json:"repository_id"`
	UserID       int64  `json:"user_id"`
}

// Stored snapshots owned by the user or kept inside the user's repositories.
func (q *Queries) AdminListErasureSnapshots(ctx context.Context, userID int64) ([]AdminListErasureSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, adminListErasureSnapshots, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListErasureSnapshotsRow{}
	for rows.Next() {
		var i AdminListErasureSnapshotsRow
		if err := rows.Scan(&i.ID, &i.RepositoryID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListErasureWorkspaces = `-- name: AdminListErasureWorkspaces :many
SELECT w.id, w.repository_id, w.user_id FROM workspaces w
WHERE w.deleted_at IS NULL
AND (w.user_id = $1::bigint OR w.repository_id IN (SELECT r.id FROM repositories r WHERE r.user_id = $1::bigint))
ORDER BY w.created_at, w.id
`

type AdminListErasureWorkspacesRow struct {
	ID           string `json:"id"`
	RepositoryID int64  `json:"repository_id"`
	UserID       int64  `json:"user_id"`
}

// Live workspaces owned by the user or running inside the user's repositories.
func (q *Queries) AdminListErasureWorkspaces(ctx context.Context, userID int64) ([]AdminListErasureWorkspacesRow, error) {
	rows, err := q.db.Query(ctx, adminListErasureWorkspaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListErasureWorkspacesRow{}
	for rows.Next() {
		var i AdminListErasureWorkspacesRow
		if err := rows.Scan(&i.ID, &i.RepositoryID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListTokens = `-- name: AdminListTokens :many
SELECT t.id, t.name, u.username, t.scopes, t.last_used_at, t.expires_at, t.created_at
FROM access_tokens t JOIN users u ON u.id = t.user_id
WHERE ($1::int = 0 OR COALESCE(t.last_used_at, t.created_at) < now() - make_interval(days => $1::int))
AND ($2::text = '' OR $2 = ANY(regexp_split_to_array(t.scopes, '[,[:space:]]+')))
AND ($3::int = 0 OR (t.expires_at >= now() AND t.expires_at <= now() + make_interval(days => $3::int)))
ORDER BY t.created_at DESC, t.id DESC LIMIT $4::int
`

type AdminListTokensParams struct {
	UnusedDays   int32  `json:"unused_days"`
	Scope        string `json:"scope"`
	ExpiringDays int32  `json:"expiring_days"`
	RowLimit     int32  `json:"row_limit"`
}

type AdminListTokensRow struct {
	ID         int64              `json:"id"`
	Name       string             `json:"name"`
	Username   string             `json:"username"`
	Scopes     string             `json:"scopes"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

func (q *Queries) AdminListTokens(ctx context.Context, arg AdminListTokensParams) ([]AdminListTokensRow, error) {
	rows, err := q.db.Query(ctx, adminListTokens,
		arg.UnusedDays,
		arg.Scope,
		arg.ExpiringDays,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListTokensRow{}
	for rows.Next() {
		var i AdminListTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Scopes,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUserCascadeReferences = `-- name: AdminListUserCascadeReferences :many
SELECT c.conrelid::regclass::text AS table_name, a.attname::text AS column_name
FROM pg_catalog.pg_constraint c
JOIN pg_catalog.pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = c.conkey[1]
WHERE c.contype = 'f' AND c.confrelid = 'public.users'::regclass
AND c.confdeltype = 'c' AND cardinality(c.conkey) = 1
ORDER BY 1, 2
`

type AdminListUserCascadeReferencesRow struct {
	TableName  string `json:"table_name"`
	ColumnName string `json:"column_name"`
}

// Every single-column foreign key that deletes its row with the user: the
// data the schema declares the user owns.
func (q *Queries) AdminListUserCascadeReferences(ctx context.Context) ([]AdminListUserCascadeReferencesRow, error) {
	rows, err := q.db.Query(ctx, adminListUserCascadeReferences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUserCascadeReferencesRow{}
	for rows.Next() {
		var i AdminListUserCascadeReferencesRow
		if err := rows.Scan(&i.TableName, &i.ColumnName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUserRepositories = `-- name: AdminListUserRepositories :many
SELECT id, name FROM repositories WHERE user_id = $1::bigint ORDER BY id
`

type AdminListUserRepositoriesRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) AdminListUserRepositories(ctx context.Context, userID int64) ([]AdminListUserRepositoriesRow, error) {
	rows, err := q.db.Query(ctx, adminListUserRepositories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUserRepositoriesRow{}
	for rows.Next() {
		var i AdminListUserRepositoriesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListWorkspaces = `-- name: AdminListWorkspaces :many
SELECT w.id, w.repository_id, w.user_id, w.name, w.is_fork, w.parent_workspace_id, w.target_bookmark, w.source_snapshot_id, w.kind, w.environment_source, w.environment_revision, w.environment_closure_hash, w.agent_session_id, w.head_push_token_id, w.environment_image, w.desktop_session_id, w.desktop_session_token_hash, w.desktop_session_expires_at, w.vm_id, w.provisioning_generation, w.status, w.failure_code, w.failure_message, w.provisioning_stage, w.last_activity_at, w.idle_timeout_secs, w.suspended_at, w.started_at, w.resumed_at, w.head_change_id, w.head_commit_id, w.ahead, w.behind, w.last_accessed_at, w.deleted_at, w.created_at, w.updated_at, w.rebuild_required_at, w.client_lease_secs, w.client_lease_expires_at, w.source_commit, w.vcpu_count, w.memory_mb, w.disk_mb, u.username AS owner,
       (COALESCE(ru.username, o.name, '') || '/' || r.name)::text AS repository
FROM workspaces w JOIN users u ON u.id = w.user_id
JOIN repositories r ON r.id = w.repository_id
LEFT JOIN users ru ON ru.id = r.user_id LEFT JOIN organizations o ON o.id = r.org_id
WHERE w.deleted_at IS NULL
AND ($1::text = '' OR w.status = $1)
AND ($2::text = '' OR w.kind = $2)
AND ($3::text = '' OR u.lower_username = lower($3))
AND ($4::boolean OR NOT u.is_synthetic)
ORDER BY w.created_at DESC, w.id DESC LIMIT $5::int
`

type AdminListWorkspacesParams struct {
	Status           string `json:"status"`
	Kind             string `json:"kind"`
	Owner            string `json:"owner"`
	IncludeSynthetic bool   `json:"include_synthetic"`
	RowLimit         int32  `json:"row_limit"`
}

type AdminListWorkspacesRow struct {
	Workspace  Workspace `json:"workspace"`
	Owner      string    `json:"owner"`
	Repository string    `json:"repository"`
}

func (q *Queries) AdminListWorkspaces(ctx context.Context, arg AdminListWorkspacesParams) ([]AdminListWorkspacesRow, error) {
	rows, err := q.db.Query(ctx, adminListWorkspaces,
		arg.Status,
		arg.Kind,
		arg.Owner,
		arg.IncludeSynthetic,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListWorkspacesRow{}
	for rows.Next() {
		var i AdminListWorkspacesRow
		if err := rows.Scan(
			&i.Workspace.ID,
			&i.Workspace.RepositoryID,
			&i.Workspace.UserID,
			&i.Workspace.Name,
			&i.Workspace.IsFork,
			&i.Workspace.ParentWorkspaceID,
			&i.Workspace.TargetBookmark,
			&i.Workspace.SourceSnapshotID,
			&i.Workspace.Kind,
			&i.Workspace.EnvironmentSource,
			&i.Workspace.EnvironmentRevision,
			&i.Workspace.EnvironmentClosureHash,
			&i.Workspace.AgentSessionID,
			&i.Workspace.HeadPushTokenID,
			&i.Workspace.EnvironmentImage,
			&i.Workspace.DesktopSessionID,
			&i.Workspace.DesktopSessionTokenHash,
			&i.Workspace.DesktopSessionExpiresAt,
			&i.Workspace.VmID,
			&i.Workspace.ProvisioningGeneration,
			&i.Workspace.Status,
			&i.Workspace.FailureCode,
			&i.Workspace.FailureMessage,
			&i.Workspace.ProvisioningStage,
			&i.Workspace.LastActivityAt,
			&i.Workspace.IdleTimeoutSecs,
			&i.Workspace.SuspendedAt,
			&i.Workspace.StartedAt,
			&i.Workspace.ResumedAt,
			&i.Workspace.HeadChangeID,
			&i.Workspace.HeadCommitID,
			&i.Workspace.Ahead,
			&i.Workspace.Behind,
			&i.Workspace.LastAccessedAt,
			&i.Workspace.DeletedAt,
			&i.Workspace.CreatedAt,
			&i.Workspace.UpdatedAt,
			&i.Workspace.RebuildRequiredAt,
			&i.Workspace.ClientLeaseSecs,
			&i.Workspace.ClientLeaseExpiresAt,
			&i.Workspace.SourceCommit,
			&i.Workspace.VcpuCount,
			&i.Workspace.MemoryMb,
			&i.Workspace.DiskMb,
			&i.Owner,
			&i.Repository,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminScrubUserAuditActor = `-- name: AdminScrubUserAuditActor :execrows
UPDATE audit_log SET actor_name = $1::text
WHERE actor_id = $2::bigint AND actor_name <> $1::text
`

type AdminScrubUserAuditActorParams struct {
	Tombstone string `json:"tombstone"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) AdminScrubUserAuditActor(ctx context.Context, arg AdminScrubUserAuditActorParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminScrubUserAuditActor, arg.Tombstone, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminScrubUserAuditDetail = `-- name: AdminScrubUserAuditDetail :execrows
UPDATE audit_log SET
  metadata = '{}'::jsonb,
  ip_address = CASE WHEN actor_id = $1::bigint THEN '' ELSE ip_address END
WHERE (actor_id = $1::bigint OR (target_type = 'user' AND target_id = $1::bigint))
AND event_type NOT LIKE 'admin.user.erase%'
AND (metadata <> '{}'::jsonb OR (actor_id = $1::bigint AND ip_address <> ''))
`

// Retained audit rows keep their ids, event types and timestamps; the
// metadata (usernames, emails) and the user's own address go. Erase receipts
// carry only the operator and request date and are kept whole.
func (q *Queries) AdminScrubUserAuditDetail(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, adminScrubUserAuditDetail, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminScrubUserAuditTarget = `-- name: AdminScrubUserAuditTarget :execrows
UPDATE audit_log SET target_name = $1::text
WHERE target_type = 'user' AND target_id = $2::bigint AND target_name <> $1::text
`

type AdminScrubUserAuditTargetParams struct {
	Tombstone string `json:"tombstone"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) AdminScrubUserAuditTarget(ctx context.Context, arg AdminScrubUserAuditTargetParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminScrubUserAuditTarget, arg.Tombstone, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminScrubUserBillingIdentity = `-- name: AdminScrubUserBillingIdentity :execrows
UPDATE billing_accounts SET stripe_customer_email = '', stripe_customer_name = '', updated_at = now()
WHERE owner_type = 'user' AND owner_id = $1::bigint
AND (stripe_customer_email <> '' OR stripe_customer_name <> '')
`

// Billing accounts stay for tax and invoices; the Stripe customer id is the
// key, the cached name and email are identity.
func (q *Queries) AdminScrubUserBillingIdentity(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, adminScrubUserBillingIdentity, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminScrubUserPushEvents = `-- name: AdminScrubUserPushEvents :execrows
UPDATE repo_push_events SET pusher_login = $1::text, updated_at = now()
WHERE pusher_id = $2::bigint AND pusher_login <> $1::text
`

type AdminScrubUserPushEventsParams struct {
	Tombstone string `json:"tombstone"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) AdminScrubUserPushEvents(ctx context.Context, arg AdminScrubUserPushEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminScrubUserPushEvents, arg.Tombstone, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminScrubUserWikiRevisions = `-- name: AdminScrubUserWikiRevisions :execrows
UPDATE wiki_page_revisions SET author_username = $1::text
WHERE author_id = $2::bigint AND author_username <> $1::text
`

type AdminScrubUserWikiRevisionsParams struct {
	Tombstone string `json:"tombstone"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) AdminScrubUserWikiRevisions(ctx context.Context, arg AdminScrubUserWikiRevisionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminScrubUserWikiRevisions, arg.Tombstone, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminTombstoneUser = `-- name: AdminTombstoneUser :execrows
UPDATE users SET
  username = $1::text, lower_username = $1::text,
  email = NULL, lower_email = NULL, display_name = 'Deleted user', bio = '',
  avatar_url = '', wallet_address = NULL, is_active = false, is_admin = false,
  prohibit_login = true, email_notifications_enabled = false, last_login_at = NULL,
  deleted_at = COALESCE(deleted_at, now()), updated_at = now()
WHERE id = $2::bigint
`

type AdminTombstoneUserParams struct {
	Tombstone string `json:"tombstone"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) AdminTombstoneUser(ctx context.Context, arg AdminTombstoneUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminTombstoneUser, arg.Tombstone, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failNeverStartedAgentSessionRaw = `-- name: FailNeverStartedAgentSessionRaw :one
WITH failed_session AS (
    UPDATE agent_sessions s SET status = 'failed', finished_at = now(), updated_at = now(),
    metadata = metadata || '{"failure_reason":"never_started"}'::jsonb
    WHERE s.id = $1 AND s.status = 'active' AND s.started_at IS NULL
    AND s.workflow_run_id IS NOT DISTINCT FROM $2::bigint
    AND s.deleted_at IS NULL AND COALESCE(
        (SELECT wr.created_at FROM workflow_runs wr WHERE wr.id = s.workflow_run_id), s.created_at
    ) < $3::timestamptz
    RETURNING s.id, s.repository_id, s.user_id, s.workflow_run_id, s.title, s.status, s.metadata, s.workspace_id, s.started_at, s.finished_at, s.created_at, s.updated_at, s.deleted_at
), failed_tasks AS (
    UPDATE workflow_tasks wt
    SET status = 'failed', last_error = 'never_started', finished_at = now(), updated_at = now()
    WHERE wt.workflow_run_id IN (SELECT workflow_run_id FROM failed_session)
      AND wt.status IN ('pending', 'assigned', 'running')
), failed_steps AS (
    UPDATE workflow_steps ws SET status = 'failure', completed_at = now(), updated_at = now()
    WHERE ws.workflow_run_id IN (SELECT workflow_run_id FROM failed_session)
      AND ws.status IN ('queued', 'running')
), failed_run AS (
    UPDATE workflow_runs wr SET status = 'failure', completed_at = now(), updated_at = now()
    WHERE wr.id IN (SELECT workflow_run_id FROM failed_session)
      AND wr.status IN ('queued', 'running')
)
SELECT id, repository_id, user_id, workflow_run_id, title, status, metadata, workspace_id, started_at, finished_at, created_at, updated_at, deleted_at FROM failed_session
`

type FailNeverStartedAgentSessionRawParams struct {
	ID            string      `json:"id"`
	WorkflowRunID pgtype.Int8 `json:"workflow_run_id"`
	Cutoff        time.Time   `json:"cutoff"`
}

type FailNeverStartedAgentSessionRawRow struct {
	ID            string             `json:"id"`
	RepositoryID  int64              `json:"repository_id"`
	UserID        int64              `json:"user_id"`
	WorkflowRunID pgtype.Int8        `json:"workflow_run_id"`
	Title         string             `json:"title"`
	Status        string             `json:"status"`
	Metadata      json.RawMessage    `json:"metadata"`
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

// Release an abandoned admission and its unfinished work atomically with the
// session failure; any failed write leaves the session eligible for retry.
func (q *Queries) FailNeverStartedAgentSessionRaw(ctx context.Context, arg FailNeverStartedAgentSessionRawParams) (FailNeverStartedAgentSessionRawRow, error) {
	row := q.db.QueryRow(ctx, failNeverStartedAgentSessionRaw, arg.ID, arg.WorkflowRunID, arg.Cutoff)
	var i FailNeverStartedAgentSessionRawRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.UserID,
		&i.WorkflowRunID,
		&i.Title,
		&i.Status,
		&i.Metadata,
		&i.WorkspaceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listNeverStartedAgentSessions = `-- name: ListNeverStartedAgentSessions :many
SELECT s.id, s.repository_id, s.user_id, s.workflow_run_id, s.title, s.status, s.metadata, s.workspace_id, s.started_at, s.finished_at, s.created_at, s.updated_at, s.deleted_at FROM agent_sessions s
LEFT JOIN workflow_runs wr ON wr.id = s.workflow_run_id
WHERE s.status = 'active' AND s.started_at IS NULL
AND s.deleted_at IS NULL AND COALESCE(wr.created_at, s.created_at) < $1::timestamptz
ORDER BY COALESCE(wr.created_at, s.created_at), s.id LIMIT 200
`

// A re-dispatched session gets a fresh provisioning deadline from its run.
func (q *Queries) ListNeverStartedAgentSessions(ctx context.Context, cutoff time.Time) ([]AgentSession, error) {
	rows, err := q.db.Query(ctx, listNeverStartedAgentSessions, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentSession{}
	for rows.Next() {
		var i AgentSession
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.UserID,
			&i.WorkflowRunID,
			&i.Title,
			&i.Status,
			&i.Metadata,
			&i.WorkspaceID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
