// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing_plan_grants.sql

package db

import (
	"context"
	"time"
)

const getActiveBillingPlanGrant = `-- name: GetActiveBillingPlanGrant :one
SELECT id, owner_type, owner_id, source_key, plan_key, expires_at, actor, reason, created_at FROM billing_plan_grants
WHERE owner_type = $1 AND owner_id = $2
 AND expires_at > $3::timestamptz
ORDER BY id DESC LIMIT 1
`

type GetActiveBillingPlanGrantParams struct {
	OwnerType string    `json:"owner_type"`
	OwnerID   int64     `json:"owner_id"`
	AsOf      time.Time `json:"as_of"`
}

func (q *Queries) GetActiveBillingPlanGrant(ctx context.Context, arg GetActiveBillingPlanGrantParams) (BillingPlanGrant, error) {
	row := q.db.QueryRow(ctx, getActiveBillingPlanGrant, arg.OwnerType, arg.OwnerID, arg.AsOf)
	var i BillingPlanGrant
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.SourceKey,
		&i.PlanKey,
		&i.ExpiresAt,
		&i.Actor,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getBillingPlanGrantByKey = `-- name: GetBillingPlanGrantByKey :one
SELECT id, owner_type, owner_id, source_key, plan_key, expires_at, actor, reason, created_at FROM billing_plan_grants
WHERE owner_type = $1 AND owner_id = $2
 AND source_key = $3
`

type GetBillingPlanGrantByKeyParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   int64  `json:"owner_id"`
	SourceKey string `json:"source_key"`
}

func (q *Queries) GetBillingPlanGrantByKey(ctx context.Context, arg GetBillingPlanGrantByKeyParams) (BillingPlanGrant, error) {
	row := q.db.QueryRow(ctx, getBillingPlanGrantByKey, arg.OwnerType, arg.OwnerID, arg.SourceKey)
	var i BillingPlanGrant
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.SourceKey,
		&i.PlanKey,
		&i.ExpiresAt,
		&i.Actor,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const insertBillingPlanGrant = `-- name: InsertBillingPlanGrant :execrows
INSERT INTO billing_plan_grants (owner_type, owner_id, source_key, plan_key, expires_at, actor, reason)
VALUES ($1, $2, $3, $4,
 $5, $6, $7)
ON CONFLICT (owner_type, owner_id, source_key) DO NOTHING
`

type InsertBillingPlanGrantParams struct {
	OwnerType string    `json:"owner_type"`
	OwnerID   int64     `json:"owner_id"`
	SourceKey string    `json:"source_key"`
	PlanKey   string    `json:"plan_key"`
	ExpiresAt time.Time `json:"expires_at"`
	Actor     string    `json:"actor"`
	Reason    string    `json:"reason"`
}

func (q *Queries) InsertBillingPlanGrant(ctx context.Context, arg InsertBillingPlanGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBillingPlanGrant,
		arg.OwnerType,
		arg.OwnerID,
		arg.SourceKey,
		arg.PlanKey,
		arg.ExpiresAt,
		arg.Actor,
		arg.Reason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
