// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branch_locks.sql

package db

import (
	"context"
)

const getBranchLockJoinRequest = `-- name: GetBranchLockJoinRequest :one
SELECT id, repository_id, branch, requester_id, status, resolver_id, created_at, resolved_at, lock_generation FROM branch_lock_join_requests
WHERE id = $1
`

func (q *Queries) GetBranchLockJoinRequest(ctx context.Context, id int64) (BranchLockJoinRequest, error) {
	row := q.db.QueryRow(ctx, getBranchLockJoinRequest, id)
	var i BranchLockJoinRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Branch,
		&i.RequesterID,
		&i.Status,
		&i.ResolverID,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.LockGeneration,
	)
	return i, err
}
