// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: build_cache.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const buildCacheRepositoryBytes = `-- name: BuildCacheRepositoryBytes :one
SELECT COALESCE((SELECT size_bytes FROM build_cache_repository_usage
WHERE repository_id = $1), 0)::bigint AS bytes
`

func (q *Queries) BuildCacheRepositoryBytes(ctx context.Context, repositoryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, buildCacheRepositoryBytes, repositoryID)
	var bytes int64
	err := row.Scan(&bytes)
	return bytes, err
}

const createBuildCacheReadToken = `-- name: CreateBuildCacheReadToken :one
INSERT INTO build_cache_read_tokens (repository_id, created_by, name, token_hash, token_last_eight, namespace_prefix)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, repository_id, created_by, name, token_hash, token_last_eight, last_used_at, revoked_at, created_at, namespace_prefix
`

type CreateBuildCacheReadTokenParams struct {
	RepositoryID    int64       `json:"repository_id"`
	CreatedBy       pgtype.Int8 `json:"created_by"`
	Name            string      `json:"name"`
	TokenHash       string      `json:"token_hash"`
	TokenLastEight  string      `json:"token_last_eight"`
	NamespacePrefix string      `json:"namespace_prefix"`
}

func (q *Queries) CreateBuildCacheReadToken(ctx context.Context, arg CreateBuildCacheReadTokenParams) (BuildCacheReadToken, error) {
	row := q.db.QueryRow(ctx, createBuildCacheReadToken,
		arg.RepositoryID,
		arg.CreatedBy,
		arg.Name,
		arg.TokenHash,
		arg.TokenLastEight,
		arg.NamespacePrefix,
	)
	var i BuildCacheReadToken
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.CreatedBy,
		&i.Name,
		&i.TokenHash,
		&i.TokenLastEight,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.NamespacePrefix,
	)
	return i, err
}

const deleteBuildCacheEntry = `-- name: DeleteBuildCacheEntry :one
DELETE FROM build_cache_entries
WHERE repository_id = $1
  AND key_digest = $2
RETURNING key_digest
`

type DeleteBuildCacheEntryParams struct {
	RepositoryID int64  `json:"repository_id"`
	KeyDigest    string `json:"key_digest"`
}

func (q *Queries) DeleteBuildCacheEntry(ctx context.Context, arg DeleteBuildCacheEntryParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteBuildCacheEntry, arg.RepositoryID, arg.KeyDigest)
	var key_digest string
	err := row.Scan(&key_digest)
	return key_digest, err
}

const deleteBuildCacheEntryFenced = `-- name: DeleteBuildCacheEntryFenced :one
DELETE FROM build_cache_entries
WHERE repository_id = $1
  AND key_digest = $2
  AND recorded_run_id = $3
  AND recorded_event_seq = $4
RETURNING key_digest
`

type DeleteBuildCacheEntryFencedParams struct {
	RepositoryID     int64       `json:"repository_id"`
	KeyDigest        string      `json:"key_digest"`
	RecordedRunID    pgtype.Text `json:"recorded_run_id"`
	RecordedEventSeq pgtype.Int8 `json:"recorded_event_seq"`
}

func (q *Queries) DeleteBuildCacheEntryFenced(ctx context.Context, arg DeleteBuildCacheEntryFencedParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteBuildCacheEntryFenced,
		arg.RepositoryID,
		arg.KeyDigest,
		arg.RecordedRunID,
		arg.RecordedEventSeq,
	)
	var key_digest string
	err := row.Scan(&key_digest)
	return key_digest, err
}

const expireBuildCacheArtifacts = `-- name: ExpireBuildCacheArtifacts :many
WITH doomed AS (
    SELECT a.digest FROM build_cache_artifacts a
    WHERE a.repository_id = $1 AND a.created_at <= $2::timestamptz
      AND NOT EXISTS (SELECT 1 FROM build_cache_entry_artifacts r
                      WHERE r.repository_id = a.repository_id AND r.digest = a.digest)
    ORDER BY a.created_at, a.digest LIMIT 16
)
DELETE FROM build_cache_artifacts a USING doomed d
WHERE a.repository_id = $1 AND a.digest = d.digest
RETURNING a.gcs_key
`

type ExpireBuildCacheArtifactsParams struct {
	RepositoryID int64     `json:"repository_id"`
	Cutoff       time.Time `json:"cutoff"`
}

func (q *Queries) ExpireBuildCacheArtifacts(ctx context.Context, arg ExpireBuildCacheArtifactsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, expireBuildCacheArtifacts, arg.RepositoryID, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var gcs_key string
		if err := rows.Scan(&gcs_key); err != nil {
			return nil, err
		}
		items = append(items, gcs_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireBuildCacheEntries = `-- name: ExpireBuildCacheEntries :exec
WITH candidates AS (
    (SELECT e.key_digest FROM build_cache_entries e
     WHERE e.repository_id = $1 AND e.created_at <= $2::timestamptz
     ORDER BY e.created_at, e.key_digest LIMIT 64)
    UNION
    (SELECT r.key_digest FROM build_cache_entry_artifacts r
     JOIN (
       SELECT a.digest FROM build_cache_artifacts a
       WHERE a.repository_id = $1 AND a.created_at <= $2::timestamptz
       ORDER BY a.created_at, a.digest LIMIT 16
     ) expired ON expired.digest = r.digest
     WHERE r.repository_id = $1 LIMIT 64)
), doomed AS (SELECT key_digest FROM candidates LIMIT 64)
DELETE FROM build_cache_entries e USING doomed d
WHERE e.repository_id = $1 AND e.key_digest = d.key_digest
`

type ExpireBuildCacheEntriesParams struct {
	RepositoryID int64     `json:"repository_id"`
	Cutoff       time.Time `json:"cutoff"`
}

func (q *Queries) ExpireBuildCacheEntries(ctx context.Context, arg ExpireBuildCacheEntriesParams) error {
	_, err := q.db.Exec(ctx, expireBuildCacheEntries, arg.RepositoryID, arg.Cutoff)
	return err
}

const getActiveBuildCacheReadTokenByHash = `-- name: GetActiveBuildCacheReadTokenByHash :one
SELECT id, repository_id, created_by, name, token_hash, token_last_eight, last_used_at, revoked_at, created_at, namespace_prefix
FROM build_cache_read_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) GetActiveBuildCacheReadTokenByHash(ctx context.Context, tokenHash string) (BuildCacheReadToken, error) {
	row := q.db.QueryRow(ctx, getActiveBuildCacheReadTokenByHash, tokenHash)
	var i BuildCacheReadToken
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.CreatedBy,
		&i.Name,
		&i.TokenHash,
		&i.TokenLastEight,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.NamespacePrefix,
	)
	return i, err
}

const getBuildCacheArtifact = `-- name: GetBuildCacheArtifact :one
UPDATE build_cache_artifacts
SET last_accessed_at = NOW(),
    access_count = CASE WHEN access_count < 9223372036854775807 THEN access_count + 1 ELSE access_count END
WHERE repository_id = $1
  AND digest = $2
  AND created_at > $3::timestamptz
RETURNING digest, size_bytes, gcs_key, created_at
`

type GetBuildCacheArtifactParams struct {
	RepositoryID int64     `json:"repository_id"`
	Digest       string    `json:"digest"`
	Cutoff       time.Time `json:"cutoff"`
}

type GetBuildCacheArtifactRow struct {
	Digest    string    `json:"digest"`
	SizeBytes int64     `json:"size_bytes"`
	GcsKey    string    `json:"gcs_key"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetBuildCacheArtifact(ctx context.Context, arg GetBuildCacheArtifactParams) (GetBuildCacheArtifactRow, error) {
	row := q.db.QueryRow(ctx, getBuildCacheArtifact, arg.RepositoryID, arg.Digest, arg.Cutoff)
	var i GetBuildCacheArtifactRow
	err := row.Scan(
		&i.Digest,
		&i.SizeBytes,
		&i.GcsKey,
		&i.CreatedAt,
	)
	return i, err
}

const getBuildCacheEntry = `-- name: GetBuildCacheEntry :one
UPDATE build_cache_entries
SET last_accessed_at = NOW(),
    access_count = CASE WHEN access_count < 9223372036854775807 THEN access_count + 1 ELSE access_count END
WHERE build_cache_entries.repository_id = $1
  AND build_cache_entries.key_digest = $2
  AND build_cache_entries.created_at > $3::timestamptz
  AND NOT EXISTS (
    SELECT 1 FROM build_cache_entry_artifacts r
    JOIN build_cache_artifacts a ON a.repository_id = r.repository_id AND a.digest = r.digest
    WHERE r.repository_id = build_cache_entries.repository_id
      AND r.key_digest = build_cache_entries.key_digest
      AND a.created_at <= $3::timestamptz
  )
RETURNING body
`

type GetBuildCacheEntryParams struct {
	RepositoryID int64     `json:"repository_id"`
	KeyDigest    string    `json:"key_digest"`
	Cutoff       time.Time `json:"cutoff"`
}

func (q *Queries) GetBuildCacheEntry(ctx context.Context, arg GetBuildCacheEntryParams) (string, error) {
	row := q.db.QueryRow(ctx, getBuildCacheEntry, arg.RepositoryID, arg.KeyDigest, arg.Cutoff)
	var body string
	err := row.Scan(&body)
	return body, err
}

const insertBuildCacheArtifact = `-- name: InsertBuildCacheArtifact :one
INSERT INTO build_cache_artifacts (repository_id, digest, size_bytes, gcs_key)
VALUES ($1, $2, $3, $4)
ON CONFLICT (repository_id, digest) DO NOTHING
RETURNING digest
`

type InsertBuildCacheArtifactParams struct {
	RepositoryID int64  `json:"repository_id"`
	Digest       string `json:"digest"`
	SizeBytes    int64  `json:"size_bytes"`
	GcsKey       string `json:"gcs_key"`
}

func (q *Queries) InsertBuildCacheArtifact(ctx context.Context, arg InsertBuildCacheArtifactParams) (string, error) {
	row := q.db.QueryRow(ctx, insertBuildCacheArtifact,
		arg.RepositoryID,
		arg.Digest,
		arg.SizeBytes,
		arg.GcsKey,
	)
	var digest string
	err := row.Scan(&digest)
	return digest, err
}

const insertBuildCacheEntry = `-- name: InsertBuildCacheEntry :one
INSERT INTO build_cache_entries (
    repository_id, key_digest, body, result_canonical, created_at_ms, recorded_run_id, recorded_event_seq
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
ON CONFLICT (repository_id, key_digest) DO NOTHING
RETURNING key_digest
`

type InsertBuildCacheEntryParams struct {
	RepositoryID     int64       `json:"repository_id"`
	KeyDigest        string      `json:"key_digest"`
	Body             string      `json:"body"`
	ResultCanonical  string      `json:"result_canonical"`
	CreatedAtMs      pgtype.Int8 `json:"created_at_ms"`
	RecordedRunID    pgtype.Text `json:"recorded_run_id"`
	RecordedEventSeq pgtype.Int8 `json:"recorded_event_seq"`
}

func (q *Queries) InsertBuildCacheEntry(ctx context.Context, arg InsertBuildCacheEntryParams) (string, error) {
	row := q.db.QueryRow(ctx, insertBuildCacheEntry,
		arg.RepositoryID,
		arg.KeyDigest,
		arg.Body,
		arg.ResultCanonical,
		arg.CreatedAtMs,
		arg.RecordedRunID,
		arg.RecordedEventSeq,
	)
	var key_digest string
	err := row.Scan(&key_digest)
	return key_digest, err
}

const listBuildCacheReadTokens = `-- name: ListBuildCacheReadTokens :many
SELECT id, repository_id, created_by, name, token_hash, token_last_eight, last_used_at, revoked_at, created_at, namespace_prefix
FROM build_cache_read_tokens
WHERE repository_id = $1
  AND revoked_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListBuildCacheReadTokens(ctx context.Context, repositoryID int64) ([]BuildCacheReadToken, error) {
	rows, err := q.db.Query(ctx, listBuildCacheReadTokens, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BuildCacheReadToken{}
	for rows.Next() {
		var i BuildCacheReadToken
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.CreatedBy,
			&i.Name,
			&i.TokenHash,
			&i.TokenLastEight,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.NamespacePrefix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredBuildCacheRepositories = `-- name: ListExpiredBuildCacheRepositories :many
SELECT DISTINCT repository_id FROM (
    (SELECT e.repository_id FROM build_cache_entries e
     WHERE e.created_at <= $1::timestamptz ORDER BY e.created_at LIMIT 64)
    UNION ALL
    (SELECT a.repository_id FROM build_cache_artifacts a
     WHERE a.created_at <= $1::timestamptz ORDER BY a.created_at LIMIT 64)
) expired
`

func (q *Queries) ListExpiredBuildCacheRepositories(ctx context.Context, cutoff time.Time) ([]int64, error) {
	rows, err := q.db.Query(ctx, listExpiredBuildCacheRepositories, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var repository_id int64
		if err := rows.Scan(&repository_id); err != nil {
			return nil, err
		}
		items = append(items, repository_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresentBuildCacheArtifacts = `-- name: ListPresentBuildCacheArtifacts :many
UPDATE build_cache_artifacts
SET last_accessed_at = NOW(),
    access_count = CASE WHEN access_count < 9223372036854775807 THEN access_count + 1 ELSE access_count END
WHERE repository_id = $1
  AND digest = ANY($2::char(64)[])
  AND created_at > $3::timestamptz
RETURNING digest
`

type ListPresentBuildCacheArtifactsParams struct {
	RepositoryID int64     `json:"repository_id"`
	Digests      []string  `json:"digests"`
	Cutoff       time.Time `json:"cutoff"`
}

func (q *Queries) ListPresentBuildCacheArtifacts(ctx context.Context, arg ListPresentBuildCacheArtifactsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPresentBuildCacheArtifacts, arg.RepositoryID, arg.Digests, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var digest string
		if err := rows.Scan(&digest); err != nil {
			return nil, err
		}
		items = append(items, digest)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBuildCacheArtifact = `-- name: LockBuildCacheArtifact :one
SELECT digest, size_bytes, gcs_key, created_at
FROM build_cache_artifacts
WHERE repository_id = $1
  AND digest = $2
FOR NO KEY UPDATE
`

type LockBuildCacheArtifactParams struct {
	RepositoryID int64  `json:"repository_id"`
	Digest       string `json:"digest"`
}

type LockBuildCacheArtifactRow struct {
	Digest    string    `json:"digest"`
	SizeBytes int64     `json:"size_bytes"`
	GcsKey    string    `json:"gcs_key"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) LockBuildCacheArtifact(ctx context.Context, arg LockBuildCacheArtifactParams) (LockBuildCacheArtifactRow, error) {
	row := q.db.QueryRow(ctx, lockBuildCacheArtifact, arg.RepositoryID, arg.Digest)
	var i LockBuildCacheArtifactRow
	err := row.Scan(
		&i.Digest,
		&i.SizeBytes,
		&i.GcsKey,
		&i.CreatedAt,
	)
	return i, err
}

const lockBuildCacheEntry = `-- name: LockBuildCacheEntry :one
SELECT (result_canonical = $1::text) AS same
FROM build_cache_entries
WHERE repository_id = $2
  AND key_digest = $3
FOR NO KEY UPDATE
`

type LockBuildCacheEntryParams struct {
	ResultCanonical string `json:"result_canonical"`
	RepositoryID    int64  `json:"repository_id"`
	KeyDigest       string `json:"key_digest"`
}

func (q *Queries) LockBuildCacheEntry(ctx context.Context, arg LockBuildCacheEntryParams) (bool, error) {
	row := q.db.QueryRow(ctx, lockBuildCacheEntry, arg.ResultCanonical, arg.RepositoryID, arg.KeyDigest)
	var same bool
	err := row.Scan(&same)
	return same, err
}

const recordBuildCacheEntryArtifacts = `-- name: RecordBuildCacheEntryArtifacts :exec
WITH present AS (
    SELECT a.digest
    FROM build_cache_artifacts AS a
    WHERE a.repository_id = $1
      AND a.digest = ANY($3::char(64)[])
    ORDER BY a.digest
    FOR KEY SHARE
)
INSERT INTO build_cache_entry_artifacts (repository_id, key_digest, digest)
SELECT $1, $2, present.digest
FROM present
ON CONFLICT DO NOTHING
`

type RecordBuildCacheEntryArtifactsParams struct {
	RepositoryID int64    `json:"repository_id"`
	KeyDigest    string   `json:"key_digest"`
	Digests      []string `json:"digests"`
}

func (q *Queries) RecordBuildCacheEntryArtifacts(ctx context.Context, arg RecordBuildCacheEntryArtifactsParams) error {
	_, err := q.db.Exec(ctx, recordBuildCacheEntryArtifacts, arg.RepositoryID, arg.KeyDigest, arg.Digests)
	return err
}

const repairBuildCacheArtifact = `-- name: RepairBuildCacheArtifact :exec
UPDATE build_cache_artifacts
SET size_bytes = $1,
    gcs_key = $2,
    created_at = NOW(),
    last_accessed_at = NOW()
WHERE repository_id = $3
  AND digest = $4
`

type RepairBuildCacheArtifactParams struct {
	SizeBytes    int64  `json:"size_bytes"`
	GcsKey       string `json:"gcs_key"`
	RepositoryID int64  `json:"repository_id"`
	Digest       string `json:"digest"`
}

func (q *Queries) RepairBuildCacheArtifact(ctx context.Context, arg RepairBuildCacheArtifactParams) error {
	_, err := q.db.Exec(ctx, repairBuildCacheArtifact,
		arg.SizeBytes,
		arg.GcsKey,
		arg.RepositoryID,
		arg.Digest,
	)
	return err
}

const revokeBuildCacheReadToken = `-- name: RevokeBuildCacheReadToken :one
UPDATE build_cache_read_tokens
SET revoked_at = NOW()
WHERE id = $1
  AND repository_id = $2
  AND revoked_at IS NULL
RETURNING id
`

type RevokeBuildCacheReadTokenParams struct {
	ID           int64 `json:"id"`
	RepositoryID int64 `json:"repository_id"`
}

func (q *Queries) RevokeBuildCacheReadToken(ctx context.Context, arg RevokeBuildCacheReadTokenParams) (int64, error) {
	row := q.db.QueryRow(ctx, revokeBuildCacheReadToken, arg.ID, arg.RepositoryID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const touchBuildCacheArtifact = `-- name: TouchBuildCacheArtifact :exec
UPDATE build_cache_artifacts
SET last_accessed_at = NOW(),
    access_count = CASE WHEN access_count < 9223372036854775807 THEN access_count + 1 ELSE access_count END
WHERE repository_id = $1
  AND digest = $2
`

type TouchBuildCacheArtifactParams struct {
	RepositoryID int64  `json:"repository_id"`
	Digest       string `json:"digest"`
}

func (q *Queries) TouchBuildCacheArtifact(ctx context.Context, arg TouchBuildCacheArtifactParams) error {
	_, err := q.db.Exec(ctx, touchBuildCacheArtifact, arg.RepositoryID, arg.Digest)
	return err
}

const touchBuildCacheEntry = `-- name: TouchBuildCacheEntry :exec
UPDATE build_cache_entries
SET last_accessed_at = NOW(),
    access_count = CASE WHEN access_count < 9223372036854775807 THEN access_count + 1 ELSE access_count END
WHERE repository_id = $1
  AND key_digest = $2
`

type TouchBuildCacheEntryParams struct {
	RepositoryID int64  `json:"repository_id"`
	KeyDigest    string `json:"key_digest"`
}

func (q *Queries) TouchBuildCacheEntry(ctx context.Context, arg TouchBuildCacheEntryParams) error {
	_, err := q.db.Exec(ctx, touchBuildCacheEntry, arg.RepositoryID, arg.KeyDigest)
	return err
}

const touchBuildCacheReadToken = `-- name: TouchBuildCacheReadToken :exec
UPDATE build_cache_read_tokens
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchBuildCacheReadToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchBuildCacheReadToken, id)
	return err
}
