// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: burst_files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBurstFile = `-- name: GetBurstFile :one
SELECT path, change, renamed_to, before_blob, after_blob, after_digest
FROM burst_files WHERE branch_id = $1 AND burst_id = $2 AND path = $3
`

type GetBurstFileParams struct {
	BranchID string `json:"branch_id"`
	BurstID  string `json:"burst_id"`
	Path     string `json:"path"`
}

type GetBurstFileRow struct {
	Path        string      `json:"path"`
	Change      string      `json:"change"`
	RenamedTo   pgtype.Text `json:"renamed_to"`
	BeforeBlob  pgtype.Text `json:"before_blob"`
	AfterBlob   pgtype.Text `json:"after_blob"`
	AfterDigest pgtype.Text `json:"after_digest"`
}

func (q *Queries) GetBurstFile(ctx context.Context, arg GetBurstFileParams) (GetBurstFileRow, error) {
	row := q.db.QueryRow(ctx, getBurstFile, arg.BranchID, arg.BurstID, arg.Path)
	var i GetBurstFileRow
	err := row.Scan(
		&i.Path,
		&i.Change,
		&i.RenamedTo,
		&i.BeforeBlob,
		&i.AfterBlob,
		&i.AfterDigest,
	)
	return i, err
}

const listBurstFiles = `-- name: ListBurstFiles :many
SELECT path, change, renamed_to, before_blob, after_blob, after_digest
FROM burst_files WHERE branch_id = $1 AND burst_id = $2 ORDER BY path
`

type ListBurstFilesParams struct {
	BranchID string `json:"branch_id"`
	BurstID  string `json:"burst_id"`
}

type ListBurstFilesRow struct {
	Path        string      `json:"path"`
	Change      string      `json:"change"`
	RenamedTo   pgtype.Text `json:"renamed_to"`
	BeforeBlob  pgtype.Text `json:"before_blob"`
	AfterBlob   pgtype.Text `json:"after_blob"`
	AfterDigest pgtype.Text `json:"after_digest"`
}

func (q *Queries) ListBurstFiles(ctx context.Context, arg ListBurstFilesParams) ([]ListBurstFilesRow, error) {
	rows, err := q.db.Query(ctx, listBurstFiles, arg.BranchID, arg.BurstID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBurstFilesRow{}
	for rows.Next() {
		var i ListBurstFilesRow
		if err := rows.Scan(
			&i.Path,
			&i.Change,
			&i.RenamedTo,
			&i.BeforeBlob,
			&i.AfterBlob,
			&i.AfterDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
