// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: factory_issue_ownership.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deferFactoryIssueFollower = `-- name: DeferFactoryIssueFollower :execrows
UPDATE repository_job_dispatches SET status='queued',error=$3,next_attempt_at=$4,
 attempts=GREATEST(attempts-1,0),claim_token=NULL,lease_until=NULL,updated_at=now()
WHERE id=$1 AND claim_token=$2 AND status='dispatching'
`

type DeferFactoryIssueFollowerParams struct {
	ID            string      `json:"id"`
	ClaimToken    pgtype.UUID `json:"claim_token"`
	Error         string      `json:"error"`
	NextAttemptAt time.Time   `json:"next_attempt_at"`
}

func (q *Queries) DeferFactoryIssueFollower(ctx context.Context, arg DeferFactoryIssueFollowerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deferFactoryIssueFollower,
		arg.ID,
		arg.ClaimToken,
		arg.Error,
		arg.NextAttemptAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveFactoryIssueClaim = `-- name: GetActiveFactoryIssueClaim :one
SELECT id, repository_id, issue_number, owner_kind, owner_id, approved_digest, authority, operation_id, claimed_at, released_at, release_reason FROM factory_issue_claims
WHERE repository_id=$1 AND issue_number=$2 AND released_at IS NULL
`

type GetActiveFactoryIssueClaimParams struct {
	RepositoryID int64 `json:"repository_id"`
	IssueNumber  int64 `json:"issue_number"`
}

func (q *Queries) GetActiveFactoryIssueClaim(ctx context.Context, arg GetActiveFactoryIssueClaimParams) (FactoryIssueClaim, error) {
	row := q.db.QueryRow(ctx, getActiveFactoryIssueClaim, arg.RepositoryID, arg.IssueNumber)
	var i FactoryIssueClaim
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.IssueNumber,
		&i.OwnerKind,
		&i.OwnerID,
		&i.ApprovedDigest,
		&i.Authority,
		&i.OperationID,
		&i.ClaimedAt,
		&i.ReleasedAt,
		&i.ReleaseReason,
	)
	return i, err
}

const getFactoryIssueClaimByContinuation = `-- name: GetFactoryIssueClaimByContinuation :one
SELECT id, repository_id, issue_number, owner_kind, owner_id, approved_digest, authority, operation_id, claimed_at, released_at, release_reason FROM factory_issue_claims
WHERE owner_kind='repository-job' AND authority->'continuations' ? $1::text
ORDER BY claimed_at DESC,id DESC LIMIT 1
`

func (q *Queries) GetFactoryIssueClaimByContinuation(ctx context.Context, dispatchID string) (FactoryIssueClaim, error) {
	row := q.db.QueryRow(ctx, getFactoryIssueClaimByContinuation, dispatchID)
	var i FactoryIssueClaim
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.IssueNumber,
		&i.OwnerKind,
		&i.OwnerID,
		&i.ApprovedDigest,
		&i.Authority,
		&i.OperationID,
		&i.ClaimedAt,
		&i.ReleasedAt,
		&i.ReleaseReason,
	)
	return i, err
}

const getFactoryIssueClaimByOwner = `-- name: GetFactoryIssueClaimByOwner :one
SELECT id, repository_id, issue_number, owner_kind, owner_id, approved_digest, authority, operation_id, claimed_at, released_at, release_reason FROM factory_issue_claims
WHERE owner_kind=$1 AND owner_id=$2 ORDER BY claimed_at DESC,id DESC LIMIT 1
`

type GetFactoryIssueClaimByOwnerParams struct {
	OwnerKind string `json:"owner_kind"`
	OwnerID   string `json:"owner_id"`
}

func (q *Queries) GetFactoryIssueClaimByOwner(ctx context.Context, arg GetFactoryIssueClaimByOwnerParams) (FactoryIssueClaim, error) {
	row := q.db.QueryRow(ctx, getFactoryIssueClaimByOwner, arg.OwnerKind, arg.OwnerID)
	var i FactoryIssueClaim
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.IssueNumber,
		&i.OwnerKind,
		&i.OwnerID,
		&i.ApprovedDigest,
		&i.Authority,
		&i.OperationID,
		&i.ClaimedAt,
		&i.ReleasedAt,
		&i.ReleaseReason,
	)
	return i, err
}

const getFactoryIssueClaimOperation = `-- name: GetFactoryIssueClaimOperation :one
SELECT r.id::text AS id,r.tenant_id,r.principal_id,r.cancellation_requested,d.external_receipt,d.external_started_at
FROM product_job_requests r JOIN product_job_dispatches d ON d.operation_id=r.id
WHERE r.id::text=$1
`

type GetFactoryIssueClaimOperationRow struct {
	ID                    string             `json:"id"`
	TenantID              string             `json:"tenant_id"`
	PrincipalID           string             `json:"principal_id"`
	CancellationRequested bool               `json:"cancellation_requested"`
	ExternalReceipt       []byte             `json:"external_receipt"`
	ExternalStartedAt     pgtype.Timestamptz `json:"external_started_at"`
}

func (q *Queries) GetFactoryIssueClaimOperation(ctx context.Context, id string) (GetFactoryIssueClaimOperationRow, error) {
	row := q.db.QueryRow(ctx, getFactoryIssueClaimOperation, id)
	var i GetFactoryIssueClaimOperationRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PrincipalID,
		&i.CancellationRequested,
		&i.ExternalReceipt,
		&i.ExternalStartedAt,
	)
	return i, err
}

const getLatestFactoryIssueEvent = `-- name: GetLatestFactoryIssueEvent :one
SELECT id, repository_id, delivery_key, source, event_type, event_action, issue_number, payload, received_at FROM repository_job_events
WHERE repository_id=$1 AND source='github' AND issue_number=$2 AND payload->'issue' IS NOT NULL
ORDER BY received_at DESC,id DESC LIMIT 1
`

type GetLatestFactoryIssueEventParams struct {
	RepositoryID int64 `json:"repository_id"`
	IssueNumber  int64 `json:"issue_number"`
}

func (q *Queries) GetLatestFactoryIssueEvent(ctx context.Context, arg GetLatestFactoryIssueEventParams) (RepositoryJobEvent, error) {
	row := q.db.QueryRow(ctx, getLatestFactoryIssueEvent, arg.RepositoryID, arg.IssueNumber)
	var i RepositoryJobEvent
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.DeliveryKey,
		&i.Source,
		&i.EventType,
		&i.EventAction,
		&i.IssueNumber,
		&i.Payload,
		&i.ReceivedAt,
	)
	return i, err
}

const listFactoryIssueDispatchesForCancellation = `-- name: ListFactoryIssueDispatchesForCancellation :many
SELECT d.id, d.registration_id, d.revision, d.digest, d.delivery_key, d.source, d.event_type, d.event_action, d.issue_number, d.payload, d.status, d.plan, d.run_id, d.signal_attempt, d.receipt, d.claim_token, d.lease_until, d.attempts, d.next_attempt_at, d.error, d.created_at, d.updated_at FROM repository_job_dispatches d JOIN repository_job_registrations r ON r.id=d.registration_id
WHERE r.repository_id=$1 AND r.job=$2
AND EXISTS(SELECT 1 FROM factory_issue_claims c WHERE c.repository_id=r.repository_id
 AND c.owner_kind='repository-job' AND c.released_at IS NULL
 AND (c.owner_id=d.id::text OR c.authority->'continuations' ? d.id::text))
ORDER BY d.created_at,d.id
`

type ListFactoryIssueDispatchesForCancellationParams struct {
	RepositoryID int64  `json:"repository_id"`
	Job          string `json:"job"`
}

func (q *Queries) ListFactoryIssueDispatchesForCancellation(ctx context.Context, arg ListFactoryIssueDispatchesForCancellationParams) ([]RepositoryJobDispatch, error) {
	rows, err := q.db.Query(ctx, listFactoryIssueDispatchesForCancellation, arg.RepositoryID, arg.Job)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RepositoryJobDispatch{}
	for rows.Next() {
		var i RepositoryJobDispatch
		if err := rows.Scan(
			&i.ID,
			&i.RegistrationID,
			&i.Revision,
			&i.Digest,
			&i.DeliveryKey,
			&i.Source,
			&i.EventType,
			&i.EventAction,
			&i.IssueNumber,
			&i.Payload,
			&i.Status,
			&i.Plan,
			&i.RunID,
			&i.SignalAttempt,
			&i.Receipt,
			&i.ClaimToken,
			&i.LeaseUntil,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
