// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: flow_relay_plans.sql

package db

import (
	"context"
)

const getFlowRelayPlan = `-- name: GetFlowRelayPlan :one
SELECT flow_id FROM flow_relay_plans
WHERE tenant_id = $1 AND principal_id = $2
  AND workspace_id = $3 AND plan_id = $4
  AND created_at > NOW() - INTERVAL '1 day'
`

type GetFlowRelayPlanParams struct {
	TenantID    string `json:"tenant_id"`
	PrincipalID string `json:"principal_id"`
	WorkspaceID string `json:"workspace_id"`
	PlanID      string `json:"plan_id"`
}

func (q *Queries) GetFlowRelayPlan(ctx context.Context, arg GetFlowRelayPlanParams) (string, error) {
	row := q.db.QueryRow(ctx, getFlowRelayPlan,
		arg.TenantID,
		arg.PrincipalID,
		arg.WorkspaceID,
		arg.PlanID,
	)
	var flow_id string
	err := row.Scan(&flow_id)
	return flow_id, err
}

const pruneFlowRelayPlans = `-- name: PruneFlowRelayPlans :execrows
DELETE FROM flow_relay_plans WHERE created_at <= NOW() - INTERVAL '1 day'
`

func (q *Queries) PruneFlowRelayPlans(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneFlowRelayPlans)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveFlowRelayPlan = `-- name: SaveFlowRelayPlan :exec
INSERT INTO flow_relay_plans (tenant_id, principal_id, workspace_id, plan_id, flow_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, principal_id, workspace_id, plan_id) DO UPDATE
SET flow_id = EXCLUDED.flow_id, created_at = NOW()
`

type SaveFlowRelayPlanParams struct {
	TenantID    string `json:"tenant_id"`
	PrincipalID string `json:"principal_id"`
	WorkspaceID string `json:"workspace_id"`
	PlanID      string `json:"plan_id"`
	FlowID      string `json:"flow_id"`
}

func (q *Queries) SaveFlowRelayPlan(ctx context.Context, arg SaveFlowRelayPlanParams) error {
	_, err := q.db.Exec(ctx, saveFlowRelayPlan,
		arg.TenantID,
		arg.PrincipalID,
		arg.WorkspaceID,
		arg.PlanID,
		arg.FlowID,
	)
	return err
}
