// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_app.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeGithubAppManifestState = `-- name: ConsumeGithubAppManifestState :one
UPDATE github_app_manifest_states
SET used_at = NOW()
WHERE digest = $1
  AND setup_session_digest = $2
  AND origin = $3
  AND NOT EXISTS (SELECT 1 FROM self_host_owners)
  AND EXISTS (
    SELECT 1 FROM install_settings
    WHERE key = 'setup.session.' || $2::TEXT
      AND (value->>'expires_at')::TIMESTAMPTZ > NOW()
  )
  AND used_at IS NULL
  AND expires_at > NOW()
  AND EXISTS (
    SELECT 1 FROM install_settings
    WHERE key = 'setup.step.app_manifest'
      AND value->>'status' = 'running'
      AND value->>'digest' = $1::TEXT
  )
RETURNING digest, setup_session_digest, owner_login, owner_kind, repository_name, origin, callback_urls, expires_at, used_at
`

type ConsumeGithubAppManifestStateParams struct {
	Digest             string `json:"digest"`
	SetupSessionDigest string `json:"setup_session_digest"`
	Origin             string `json:"origin"`
}

func (q *Queries) ConsumeGithubAppManifestState(ctx context.Context, arg ConsumeGithubAppManifestStateParams) (GithubAppManifestState, error) {
	row := q.db.QueryRow(ctx, consumeGithubAppManifestState, arg.Digest, arg.SetupSessionDigest, arg.Origin)
	var i GithubAppManifestState
	err := row.Scan(
		&i.Digest,
		&i.SetupSessionDigest,
		&i.OwnerLogin,
		&i.OwnerKind,
		&i.RepositoryName,
		&i.Origin,
		&i.CallbackUrls,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const createGithubApp = `-- name: CreateGithubApp :execrows
INSERT INTO github_app (
    id, slug, owner_login, owner_kind, client_id,
    pem_sealed, webhook_secret_sealed, client_secret_sealed, installation_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
ON CONFLICT DO NOTHING
`

type CreateGithubAppParams struct {
	ID                  int64       `json:"id"`
	Slug                string      `json:"slug"`
	OwnerLogin          string      `json:"owner_login"`
	OwnerKind           string      `json:"owner_kind"`
	ClientID            string      `json:"client_id"`
	PemSealed           string      `json:"pem_sealed"`
	WebhookSecretSealed string      `json:"webhook_secret_sealed"`
	ClientSecretSealed  string      `json:"client_secret_sealed"`
	InstallationID      pgtype.Int8 `json:"installation_id"`
}

func (q *Queries) CreateGithubApp(ctx context.Context, arg CreateGithubAppParams) (int64, error) {
	result, err := q.db.Exec(ctx, createGithubApp,
		arg.ID,
		arg.Slug,
		arg.OwnerLogin,
		arg.OwnerKind,
		arg.ClientID,
		arg.PemSealed,
		arg.WebhookSecretSealed,
		arg.ClientSecretSealed,
		arg.InstallationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createGithubAppManifestState = `-- name: CreateGithubAppManifestState :one
INSERT INTO github_app_manifest_states (digest, setup_session_digest, owner_login, owner_kind, repository_name, origin, callback_urls, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING digest, setup_session_digest, owner_login, owner_kind, repository_name, origin, callback_urls, expires_at, used_at
`

type CreateGithubAppManifestStateParams struct {
	Digest             string          `json:"digest"`
	SetupSessionDigest string          `json:"setup_session_digest"`
	OwnerLogin         string          `json:"owner_login"`
	OwnerKind          string          `json:"owner_kind"`
	RepositoryName     string          `json:"repository_name"`
	Origin             string          `json:"origin"`
	CallbackUrls       json.RawMessage `json:"callback_urls"`
	ExpiresAt          time.Time       `json:"expires_at"`
}

func (q *Queries) CreateGithubAppManifestState(ctx context.Context, arg CreateGithubAppManifestStateParams) (GithubAppManifestState, error) {
	row := q.db.QueryRow(ctx, createGithubAppManifestState,
		arg.Digest,
		arg.SetupSessionDigest,
		arg.OwnerLogin,
		arg.OwnerKind,
		arg.RepositoryName,
		arg.Origin,
		arg.CallbackUrls,
		arg.ExpiresAt,
	)
	var i GithubAppManifestState
	err := row.Scan(
		&i.Digest,
		&i.SetupSessionDigest,
		&i.OwnerLogin,
		&i.OwnerKind,
		&i.RepositoryName,
		&i.Origin,
		&i.CallbackUrls,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const deleteOtherGithubAppManifestStates = `-- name: DeleteOtherGithubAppManifestStates :exec
DELETE FROM github_app_manifest_states WHERE digest <> $1
`

func (q *Queries) DeleteOtherGithubAppManifestStates(ctx context.Context, digest string) error {
	_, err := q.db.Exec(ctx, deleteOtherGithubAppManifestStates, digest)
	return err
}

const getGithubApp = `-- name: GetGithubApp :one
SELECT id, singleton, slug, owner_login, owner_kind, client_id, pem_sealed, webhook_secret_sealed, client_secret_sealed, installation_id, created_at FROM github_app WHERE singleton = TRUE
`

func (q *Queries) GetGithubApp(ctx context.Context) (GithubApp, error) {
	row := q.db.QueryRow(ctx, getGithubApp)
	var i GithubApp
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.Slug,
		&i.OwnerLogin,
		&i.OwnerKind,
		&i.ClientID,
		&i.PemSealed,
		&i.WebhookSecretSealed,
		&i.ClientSecretSealed,
		&i.InstallationID,
		&i.CreatedAt,
	)
	return i, err
}

const getGithubAppManifestState = `-- name: GetGithubAppManifestState :one
SELECT digest, setup_session_digest, owner_login, owner_kind, repository_name, origin, callback_urls, expires_at, used_at FROM github_app_manifest_states WHERE digest = $1
`

func (q *Queries) GetGithubAppManifestState(ctx context.Context, digest string) (GithubAppManifestState, error) {
	row := q.db.QueryRow(ctx, getGithubAppManifestState, digest)
	var i GithubAppManifestState
	err := row.Scan(
		&i.Digest,
		&i.SetupSessionDigest,
		&i.OwnerLogin,
		&i.OwnerKind,
		&i.RepositoryName,
		&i.Origin,
		&i.CallbackUrls,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getInstallSetting = `-- name: GetInstallSetting :one
SELECT key, value, sealed, updated_by, updated_at FROM install_settings WHERE key = $1
`

func (q *Queries) GetInstallSetting(ctx context.Context, key string) (InstallSetting, error) {
	row := q.db.QueryRow(ctx, getInstallSetting, key)
	var i InstallSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Sealed,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const setGithubAppInstallation = `-- name: SetGithubAppInstallation :execrows
UPDATE github_app
SET installation_id = $1::BIGINT
WHERE singleton = TRUE
`

func (q *Queries) SetGithubAppInstallation(ctx context.Context, installationID int64) (int64, error) {
	result, err := q.db.Exec(ctx, setGithubAppInstallation, installationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertInstallSetting = `-- name: UpsertInstallSetting :exec
INSERT INTO install_settings (key, value, sealed, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value, sealed = EXCLUDED.sealed,
    updated_by = EXCLUDED.updated_by, updated_at = NOW()
`

type UpsertInstallSettingParams struct {
	Key       string          `json:"key"`
	Value     json.RawMessage `json:"value"`
	Sealed    bool            `json:"sealed"`
	UpdatedBy pgtype.Int8     `json:"updated_by"`
}

func (q *Queries) UpsertInstallSetting(ctx context.Context, arg UpsertInstallSettingParams) error {
	_, err := q.db.Exec(ctx, upsertInstallSetting,
		arg.Key,
		arg.Value,
		arg.Sealed,
		arg.UpdatedBy,
	)
	return err
}
