// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_mirror_sync_runs.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGithubMirrorSyncRun = `-- name: CreateGithubMirrorSyncRun :one
INSERT INTO github_mirror_sync_runs (repository_id, requested_by)
VALUES ($1, $2)
RETURNING id, repository_id, requested_by, state, started_at, finished_at, created_at, updated_at
`

type CreateGithubMirrorSyncRunParams struct {
	RepositoryID int64       `json:"repository_id"`
	RequestedBy  pgtype.Int8 `json:"requested_by"`
}

func (q *Queries) CreateGithubMirrorSyncRun(ctx context.Context, arg CreateGithubMirrorSyncRunParams) (GithubMirrorSyncRun, error) {
	row := q.db.QueryRow(ctx, createGithubMirrorSyncRun, arg.RepositoryID, arg.RequestedBy)
	var i GithubMirrorSyncRun
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.RequestedBy,
		&i.State,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireGithubMirrorSyncRuns = `-- name: ExpireGithubMirrorSyncRuns :execrows
WITH expired AS (
    UPDATE github_mirror_sync_runs
    SET state = 'failed', finished_at = NOW(), updated_at = NOW()
    WHERE id IN (
        SELECT id FROM github_mirror_sync_runs
        WHERE ($1::bigint = 0 OR repository_id = $1)
          AND state IN ('queued', 'running')
          AND created_at <= NOW() - INTERVAL '11 minutes'
        ORDER BY id
        LIMIT 1000
        FOR UPDATE SKIP LOCKED
    )
    RETURNING id, repository_id, created_at
), interrupted_refs AS (
    UPDATE github_mirror_sync_ref_results rr
    SET status = 'failed', error = 'Git mirror sync interrupted; retry reconciliation', updated_at = NOW()
    FROM expired
    WHERE rr.run_id = expired.id AND rr.status = 'pending'
    RETURNING rr.run_id
)
UPDATE repositories r
SET mirror_status = 'failed',
    mirror_behind_refs = (SELECT COUNT(*)::integer FROM github_mirror_sync_ref_results rr
                         WHERE rr.run_id = expired.id AND rr.status <> 'succeeded'),
    mirror_failed_refs = (SELECT COUNT(*)::integer FROM github_mirror_sync_ref_results rr
                         WHERE rr.run_id = expired.id AND rr.status <> 'succeeded'),
    last_mirror_error = 'Git mirror sync interrupted; retry reconciliation'
FROM expired
WHERE r.id = expired.repository_id
  AND (r.last_mirror_at IS NULL OR r.last_mirror_at <= expired.created_at)
`

// A fixed admission deadline also covers legacy rows and lost queued launches.
// Lock each run before its refs so late writers serialize with interruption.
// The result counts repository health updates, not interrupted runs: newer
// independently verified health is preserved even when its old run expires.
func (q *Queries) ExpireGithubMirrorSyncRuns(ctx context.Context, repositoryID int64) (int64, error) {
	result, err := q.db.Exec(ctx, expireGithubMirrorSyncRuns, repositoryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishGithubMirrorSyncRun = `-- name: FinishGithubMirrorSyncRun :exec
WITH finished AS (
    UPDATE github_mirror_sync_runs AS sync_run
    SET state = $1::text, finished_at = NOW(), updated_at = NOW()
    WHERE sync_run.id = $2 AND sync_run.state IN ('queued', 'running')
      AND sync_run.created_at > NOW() - INTERVAL '11 minutes'
    RETURNING sync_run.id, sync_run.repository_id, sync_run.state, sync_run.created_at
)
UPDATE repositories r
SET mirror_status = 'failed',
    mirror_behind_refs = (
        SELECT COUNT(*)::integer FROM github_mirror_sync_ref_results rr
        WHERE rr.run_id = finished.id AND rr.status <> 'succeeded'
    ),
    mirror_failed_refs = (
        SELECT COUNT(*)::integer FROM github_mirror_sync_ref_results rr
        WHERE rr.run_id = finished.id AND rr.status = 'failed'
    ),
    last_mirror_error = COALESCE((
        SELECT NULLIF(rr.error, '') FROM github_mirror_sync_ref_results rr
        WHERE rr.run_id = finished.id AND rr.status = 'failed' AND rr.error <> ''
        ORDER BY rr.name LIMIT 1
    ), 'Git mirror sync failed')
FROM finished
WHERE r.id = finished.repository_id AND finished.state = 'failed'
  AND (r.last_mirror_at IS NULL OR r.last_mirror_at <= finished.created_at)
`

type FinishGithubMirrorSyncRunParams struct {
	State string `json:"state"`
	ID    int64  `json:"id"`
}

// Failed runs publish current failure health without replacing the last
// verified success. A completed run cannot finalize again over newer health.
func (q *Queries) FinishGithubMirrorSyncRun(ctx context.Context, arg FinishGithubMirrorSyncRunParams) error {
	_, err := q.db.Exec(ctx, finishGithubMirrorSyncRun, arg.State, arg.ID)
	return err
}

const finishSuccessfulGithubMirrorSyncRun = `-- name: FinishSuccessfulGithubMirrorSyncRun :execrows
WITH finished AS (
    UPDATE github_mirror_sync_runs AS sync_run
    SET state = 'succeeded', finished_at = NOW(), updated_at = NOW()
    WHERE sync_run.id = $2 AND sync_run.state = 'running'
      AND sync_run.created_at > NOW() - INTERVAL '11 minutes'
    RETURNING sync_run.repository_id
)
UPDATE repositories r
SET mirror_status = 'synced', mirror_behind_refs = 0, mirror_failed_refs = 0,
    last_mirror_at = NOW(), last_mirror_error = NULL,
    last_mirror_github_head = $1::jsonb ->> ('refs/heads/' || r.default_bookmark)
FROM finished
WHERE r.id = finished.repository_id
`

type FinishSuccessfulGithubMirrorSyncRunParams struct {
	VerifiedRefs json.RawMessage `json:"verified_refs"`
	ID           int64           `json:"id"`
}

// A complete, verified push publishes its run receipt and repository health
// atomically. Per-ref retries use the ordinary finisher: they cannot certify
// the other refs. The default bookmark's SHA comes from the verified target.
func (q *Queries) FinishSuccessfulGithubMirrorSyncRun(ctx context.Context, arg FinishSuccessfulGithubMirrorSyncRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishSuccessfulGithubMirrorSyncRun, arg.VerifiedRefs, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGithubMirrorSyncRun = `-- name: GetGithubMirrorSyncRun :one
SELECT id, repository_id, requested_by, state, started_at, finished_at, created_at, updated_at
FROM github_mirror_sync_runs
WHERE id = $1
  AND repository_id = $2
`

type GetGithubMirrorSyncRunParams struct {
	ID           int64 `json:"id"`
	RepositoryID int64 `json:"repository_id"`
}

func (q *Queries) GetGithubMirrorSyncRun(ctx context.Context, arg GetGithubMirrorSyncRunParams) (GithubMirrorSyncRun, error) {
	row := q.db.QueryRow(ctx, getGithubMirrorSyncRun, arg.ID, arg.RepositoryID)
	var i GithubMirrorSyncRun
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.RequestedBy,
		&i.State,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestGithubMirrorSyncRefResult = `-- name: GetLatestGithubMirrorSyncRefResult :one
SELECT rr.id, rr.run_id, rr.name, rr.from_revision, rr.to_revision, rr.status, rr.error, rr.created_at, rr.updated_at
FROM github_mirror_sync_ref_results rr
JOIN github_mirror_sync_runs runs ON runs.id = rr.run_id
WHERE runs.repository_id = $1
  AND rr.name = $2::text
ORDER BY runs.created_at DESC, runs.id DESC
LIMIT 1
`

type GetLatestGithubMirrorSyncRefResultParams struct {
	RepositoryID int64  `json:"repository_id"`
	Name         string `json:"name"`
}

func (q *Queries) GetLatestGithubMirrorSyncRefResult(ctx context.Context, arg GetLatestGithubMirrorSyncRefResultParams) (GithubMirrorSyncRefResult, error) {
	row := q.db.QueryRow(ctx, getLatestGithubMirrorSyncRefResult, arg.RepositoryID, arg.Name)
	var i GithubMirrorSyncRefResult
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.FromRevision,
		&i.ToRevision,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestSucceededGithubMirrorSyncRefResult = `-- name: GetLatestSucceededGithubMirrorSyncRefResult :one
SELECT rr.id, rr.run_id, rr.name, rr.from_revision, rr.to_revision, rr.status, rr.error, rr.created_at, rr.updated_at
FROM github_mirror_sync_ref_results rr
JOIN github_mirror_sync_runs runs ON runs.id = rr.run_id
WHERE runs.repository_id = $1
  AND rr.name = $2::text
  AND rr.status = 'succeeded'
  AND rr.from_revision <> rr.to_revision
ORDER BY runs.created_at DESC, runs.id DESC
LIMIT 1
`

type GetLatestSucceededGithubMirrorSyncRefResultParams struct {
	RepositoryID int64  `json:"repository_id"`
	Name         string `json:"name"`
}

// The last revision this mirror verifiably wrote for a ref. Failed and
// refused or already-matching results never grant a prune.
func (q *Queries) GetLatestSucceededGithubMirrorSyncRefResult(ctx context.Context, arg GetLatestSucceededGithubMirrorSyncRefResultParams) (GithubMirrorSyncRefResult, error) {
	row := q.db.QueryRow(ctx, getLatestSucceededGithubMirrorSyncRefResult, arg.RepositoryID, arg.Name)
	var i GithubMirrorSyncRefResult
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.FromRevision,
		&i.ToRevision,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGithubMirrorSyncRefResults = `-- name: ListGithubMirrorSyncRefResults :many
SELECT id, run_id, name, from_revision, to_revision, status, error, created_at, updated_at
FROM github_mirror_sync_ref_results
WHERE run_id = $1
ORDER BY name
`

func (q *Queries) ListGithubMirrorSyncRefResults(ctx context.Context, runID int64) ([]GithubMirrorSyncRefResult, error) {
	rows, err := q.db.Query(ctx, listGithubMirrorSyncRefResults, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubMirrorSyncRefResult{}
	for rows.Next() {
		var i GithubMirrorSyncRefResult
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Name,
			&i.FromRevision,
			&i.ToRevision,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGithubMirrorSyncRunRunning = `-- name: MarkGithubMirrorSyncRunRunning :execrows
UPDATE github_mirror_sync_runs
SET state = 'running', started_at = NOW(), updated_at = NOW()
WHERE id = $1
  AND state = 'queued'
  AND created_at > NOW() - INTERVAL '10 minutes'
`

func (q *Queries) MarkGithubMirrorSyncRunRunning(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markGithubMirrorSyncRunRunning, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertGithubMirrorSyncRefResult = `-- name: UpsertGithubMirrorSyncRefResult :execrows
WITH active AS (
    SELECT sync_run.id FROM github_mirror_sync_runs sync_run
    WHERE sync_run.id = $6 AND sync_run.state = 'running'
      AND sync_run.created_at > NOW() - INTERVAL '11 minutes'
    FOR UPDATE
)
INSERT INTO github_mirror_sync_ref_results (
    run_id, name, from_revision, to_revision, status, error
)
SELECT active.id, $1::text,
    $2::text, $3::text,
    $4::text, $5::text
FROM active
ON CONFLICT (run_id, name) DO UPDATE
SET from_revision = EXCLUDED.from_revision,
    to_revision = EXCLUDED.to_revision,
    status = EXCLUDED.status,
    error = EXCLUDED.error,
    updated_at = NOW()
`

type UpsertGithubMirrorSyncRefResultParams struct {
	Name         string `json:"name"`
	FromRevision string `json:"from_revision"`
	ToRevision   string `json:"to_revision"`
	Status       string `json:"status"`
	Error        string `json:"error"`
	RunID        int64  `json:"run_id"`
}

func (q *Queries) UpsertGithubMirrorSyncRefResult(ctx context.Context, arg UpsertGithubMirrorSyncRefResultParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertGithubMirrorSyncRefResult,
		arg.Name,
		arg.FromRevision,
		arg.ToRevision,
		arg.Status,
		arg.Error,
		arg.RunID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
