// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: install_parallel.sql

package db

import (
	"context"
	"encoding/json"
)

const getInstallParallel = `-- name: GetInstallParallel :one
SELECT (SELECT value FROM install_settings WHERE key = 'parallel')::jsonb AS parallel
`

func (q *Queries) GetInstallParallel(ctx context.Context) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getInstallParallel)
	var parallel json.RawMessage
	err := row.Scan(&parallel)
	return parallel, err
}

const setInstallParallel = `-- name: SetInstallParallel :execrows
INSERT INTO install_settings (key, value, updated_by)
SELECT 'parallel', $1::jsonb, user_id
FROM self_host_owners WHERE singleton AND user_id = $2::bigint
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value, updated_by = EXCLUDED.updated_by, updated_at = NOW()
`

type SetInstallParallelParams struct {
	Value   json.RawMessage `json:"value"`
	ActorID int64           `json:"actor_id"`
}

func (q *Queries) SetInstallParallel(ctx context.Context, arg SetInstallParallelParams) (int64, error) {
	result, err := q.db.Exec(ctx, setInstallParallel, arg.Value, arg.ActorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
