// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: install_capacity.sql

package db

import (
	"context"
	"encoding/json"
)

const getInstallCapacity = `-- name: GetInstallCapacity :one
SELECT COALESCE((SELECT user_id FROM self_host_owners WHERE singleton), 0)::bigint AS owner_id,
       (SELECT value FROM install_settings WHERE key = 'capacity')::jsonb AS capacity
`

type GetInstallCapacityRow struct {
	OwnerID  int64           `json:"owner_id"`
	Capacity json.RawMessage `json:"capacity"`
}

func (q *Queries) GetInstallCapacity(ctx context.Context) (GetInstallCapacityRow, error) {
	row := q.db.QueryRow(ctx, getInstallCapacity)
	var i GetInstallCapacityRow
	err := row.Scan(&i.OwnerID, &i.Capacity)
	return i, err
}

const setInstallCapacity = `-- name: SetInstallCapacity :execrows
INSERT INTO install_settings (key, value, updated_by)
SELECT 'capacity', $1::jsonb, user_id
FROM self_host_owners WHERE singleton AND user_id = $2::bigint
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value, updated_by = EXCLUDED.updated_by, updated_at = NOW()
`

type SetInstallCapacityParams struct {
	Value   json.RawMessage `json:"value"`
	ActorID int64           `json:"actor_id"`
}

func (q *Queries) SetInstallCapacity(ctx context.Context, arg SetInstallCapacityParams) (int64, error) {
	result, err := q.db.Exec(ctx, setInstallCapacity, arg.Value, arg.ActorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
