// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const authorizeMemberUser = `-- name: AuthorizeMemberUser :one
SELECT EXISTS (
    SELECT 1
    FROM members m
    JOIN users u ON u.id = m.user_id
    WHERE m.user_id = $1
      AND m.removed_at IS NULL
      AND m.suspended_at IS NULL
      AND u.is_active = TRUE
      AND u.deleted_at IS NULL
)
`

// Whether a credential's user is on the roster: present, not removed and not
// suspended, with an active account.
func (q *Queries) AuthorizeMemberUser(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRow(ctx, authorizeMemberUser, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createOwnerMember = `-- name: CreateOwnerMember :one
INSERT INTO members (user_id, github_user_id, login, role)
VALUES ($1, $2, $3, 'owner')
RETURNING id, user_id, github_user_id, login, role, unix_uid, added_by, added_at, suspended_at, suspended_reason, removed_at, last_access_check_at
`

type CreateOwnerMemberParams struct {
	UserID       int64       `json:"user_id"`
	GithubUserID pgtype.Int8 `json:"github_user_id"`
	Login        string      `json:"login"`
}

func (q *Queries) CreateOwnerMember(ctx context.Context, arg CreateOwnerMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createOwnerMember, arg.UserID, arg.GithubUserID, arg.Login)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GithubUserID,
		&i.Login,
		&i.Role,
		&i.UnixUid,
		&i.AddedBy,
		&i.AddedAt,
		&i.SuspendedAt,
		&i.SuspendedReason,
		&i.RemovedAt,
		&i.LastAccessCheckAt,
	)
	return i, err
}

const createOwnerUser = `-- name: CreateOwnerUser :one
INSERT INTO users (username, lower_username, email, lower_email, display_name, is_admin)
VALUES ($1, $2, $3, $4, $5, TRUE)
RETURNING id, username, lower_username, email, lower_email, display_name, bio, search_vector, avatar_url, wallet_address, user_type, is_active, is_admin, prohibit_login, email_notifications_enabled, last_login_at, deleted_at, created_at, updated_at, is_synthetic
`

type CreateOwnerUserParams struct {
	Username      string      `json:"username"`
	LowerUsername string      `json:"lower_username"`
	Email         pgtype.Text `json:"email"`
	LowerEmail    pgtype.Text `json:"lower_email"`
	DisplayName   string      `json:"display_name"`
}

func (q *Queries) CreateOwnerUser(ctx context.Context, arg CreateOwnerUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createOwnerUser,
		arg.Username,
		arg.LowerUsername,
		arg.Email,
		arg.LowerEmail,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.LowerUsername,
		&i.Email,
		&i.LowerEmail,
		&i.DisplayName,
		&i.Bio,
		&i.SearchVector,
		&i.AvatarUrl,
		&i.WalletAddress,
		&i.UserType,
		&i.IsActive,
		&i.IsAdmin,
		&i.ProhibitLogin,
		&i.EmailNotificationsEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSynthetic,
	)
	return i, err
}

const deleteInstallSetting = `-- name: DeleteInstallSetting :execrows
DELETE FROM install_settings WHERE key = $1
`

func (q *Queries) DeleteInstallSetting(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInstallSetting, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInstallOwnerUser = `-- name: GetInstallOwnerUser :one
SELECT u.id, u.username, u.lower_username, u.email, u.lower_email, u.display_name, u.bio, u.search_vector, u.avatar_url, u.wallet_address, u.user_type, u.is_active, u.is_admin, u.prohibit_login, u.email_notifications_enabled, u.last_login_at, u.deleted_at, u.created_at, u.updated_at, u.is_synthetic
FROM members m
JOIN users u ON u.id = m.user_id
WHERE m.role = 'owner'
`

func (q *Queries) GetInstallOwnerUser(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, getInstallOwnerUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.LowerUsername,
		&i.Email,
		&i.LowerEmail,
		&i.DisplayName,
		&i.Bio,
		&i.SearchVector,
		&i.AvatarUrl,
		&i.WalletAddress,
		&i.UserType,
		&i.IsActive,
		&i.IsAdmin,
		&i.ProhibitLogin,
		&i.EmailNotificationsEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSynthetic,
	)
	return i, err
}

const getInstallSetting = `-- name: GetInstallSetting :one
SELECT value FROM install_settings WHERE key = $1
`

func (q *Queries) GetInstallSetting(ctx context.Context, key string) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getInstallSetting, key)
	var value json.RawMessage
	err := row.Scan(&value)
	return value, err
}

const getSignInMember = `-- name: GetSignInMember :one
SELECT id, user_id, github_user_id, login, role, unix_uid, added_by, added_at, suspended_at, suspended_reason, removed_at, last_access_check_at FROM members
WHERE github_user_id = $1
  AND removed_at IS NULL
`

// The roster row a GitHub account signs in as: present and not removed.
func (q *Queries) GetSignInMember(ctx context.Context, githubUserID pgtype.Int8) (Member, error) {
	row := q.db.QueryRow(ctx, getSignInMember, githubUserID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GithubUserID,
		&i.Login,
		&i.Role,
		&i.UnixUid,
		&i.AddedBy,
		&i.AddedAt,
		&i.SuspendedAt,
		&i.SuspendedReason,
		&i.RemovedAt,
		&i.LastAccessCheckAt,
	)
	return i, err
}

const installHasOwner = `-- name: InstallHasOwner :one
SELECT EXISTS (SELECT 1 FROM members WHERE role = 'owner')
`

func (q *Queries) InstallHasOwner(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, installHasOwner)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockInstallSetting = `-- name: LockInstallSetting :one
SELECT value FROM install_settings WHERE key = $1 FOR UPDATE
`

func (q *Queries) LockInstallSetting(ctx context.Context, key string) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, lockInstallSetting, key)
	var value json.RawMessage
	err := row.Scan(&value)
	return value, err
}

const putInstallSetting = `-- name: PutInstallSetting :exec
INSERT INTO install_settings (key, value, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()
`

type PutInstallSettingParams struct {
	Key   string          `json:"key"`
	Value json.RawMessage `json:"value"`
}

func (q *Queries) PutInstallSetting(ctx context.Context, arg PutInstallSettingParams) error {
	_, err := q.db.Exec(ctx, putInstallSetting, arg.Key, arg.Value)
	return err
}
