// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: onboarding_answers.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOnboardingAnswers = `-- name: GetOnboardingAnswers :one
SELECT answers, updated_at
FROM onboarding_answers
WHERE user_id = $1
`

type GetOnboardingAnswersRow struct {
	Answers   json.RawMessage    `json:"answers"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOnboardingAnswers(ctx context.Context, userID int64) (GetOnboardingAnswersRow, error) {
	row := q.db.QueryRow(ctx, getOnboardingAnswers, userID)
	var i GetOnboardingAnswersRow
	err := row.Scan(&i.Answers, &i.UpdatedAt)
	return i, err
}

const upsertOnboardingAnswers = `-- name: UpsertOnboardingAnswers :one
INSERT INTO onboarding_answers (user_id, answers)
VALUES ($1, $2)
ON CONFLICT (user_id)
DO UPDATE SET
    answers    = EXCLUDED.answers,
    updated_at = NOW()
RETURNING answers, updated_at
`

type UpsertOnboardingAnswersParams struct {
	UserID  int64           `json:"user_id"`
	Answers json.RawMessage `json:"answers"`
}

type UpsertOnboardingAnswersRow struct {
	Answers   json.RawMessage    `json:"answers"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertOnboardingAnswers(ctx context.Context, arg UpsertOnboardingAnswersParams) (UpsertOnboardingAnswersRow, error) {
	row := q.db.QueryRow(ctx, upsertOnboardingAnswers, arg.UserID, arg.Answers)
	var i UpsertOnboardingAnswersRow
	err := row.Scan(&i.Answers, &i.UpdatedAt)
	return i, err
}
