// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: owner_identity.sql

package db

import (
	"context"
)

const getSelfHostOwner = `-- name: GetSelfHostOwner :one
SELECT u.id, u.username, u.lower_username, u.email, u.lower_email, u.display_name, u.bio, u.search_vector, u.avatar_url, u.wallet_address, u.user_type, u.is_active, u.is_admin, u.prohibit_login, u.email_notifications_enabled, u.last_login_at, u.deleted_at, u.created_at, u.updated_at, u.is_synthetic
FROM self_host_owners o
JOIN users u ON u.id = o.user_id
WHERE o.singleton = TRUE
  AND u.is_active = TRUE
  AND u.deleted_at IS NULL
`

func (q *Queries) GetSelfHostOwner(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, getSelfHostOwner)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.LowerUsername,
		&i.Email,
		&i.LowerEmail,
		&i.DisplayName,
		&i.Bio,
		&i.SearchVector,
		&i.AvatarUrl,
		&i.WalletAddress,
		&i.UserType,
		&i.IsActive,
		&i.IsAdmin,
		&i.ProhibitLogin,
		&i.EmailNotificationsEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSynthetic,
	)
	return i, err
}
