// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projection_events.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const insertProjectionEvent = `-- name: InsertProjectionEvent :one
INSERT INTO projection_events (repository_id, topic, seq, payload) VALUES ($1, $2, $3, $4)
RETURNING repository_id, topic, seq, at, payload
`

type InsertProjectionEventParams struct {
	RepositoryID int64           `json:"repository_id"`
	Topic        string          `json:"topic"`
	Seq          int64           `json:"seq"`
	Payload      json.RawMessage `json:"payload"`
}

func (q *Queries) InsertProjectionEvent(ctx context.Context, arg InsertProjectionEventParams) (ProjectionEvent, error) {
	row := q.db.QueryRow(ctx, insertProjectionEvent,
		arg.RepositoryID,
		arg.Topic,
		arg.Seq,
		arg.Payload,
	)
	var i ProjectionEvent
	err := row.Scan(
		&i.RepositoryID,
		&i.Topic,
		&i.Seq,
		&i.At,
		&i.Payload,
	)
	return i, err
}

const listProjectionEvents = `-- name: ListProjectionEvents :many
SELECT repository_id, topic, seq, at, payload FROM projection_events
WHERE repository_id = $1 AND topic = $2 AND seq > $3::bigint
ORDER BY seq
LIMIT $4
`

type ListProjectionEventsParams struct {
	RepositoryID int64  `json:"repository_id"`
	Topic        string `json:"topic"`
	AfterSeq     int64  `json:"after_seq"`
	RowLimit     int32  `json:"row_limit"`
}

func (q *Queries) ListProjectionEvents(ctx context.Context, arg ListProjectionEventsParams) ([]ProjectionEvent, error) {
	rows, err := q.db.Query(ctx, listProjectionEvents,
		arg.RepositoryID,
		arg.Topic,
		arg.AfterSeq,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectionEvent{}
	for rows.Next() {
		var i ProjectionEvent
		if err := rows.Scan(
			&i.RepositoryID,
			&i.Topic,
			&i.Seq,
			&i.At,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextProjectionSeq = `-- name: NextProjectionSeq :one

INSERT INTO projection_topics (repository_id, topic, last_seq) VALUES ($1, $2, 1)
ON CONFLICT (repository_id, topic) DO UPDATE SET last_seq = projection_topics.last_seq + 1
RETURNING last_seq
`

type NextProjectionSeqParams struct {
	RepositoryID int64  `json:"repository_id"`
	Topic        string `json:"topic"`
}

// Projection events (spec §3.1, §3.3; services/projection.go is the only
// writer, the live channel of T-COL-02 the reader).
// Takes the topic's next seq and holds its row locked until commit, so seq
// order is commit order and a rollback gives the seq back.
func (q *Queries) NextProjectionSeq(ctx context.Context, arg NextProjectionSeqParams) (int64, error) {
	row := q.db.QueryRow(ctx, nextProjectionSeq, arg.RepositoryID, arg.Topic)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const notifyLive = `-- name: NotifyLive :exec
SELECT pg_notify('live', $1::text)
`

// Queued with the transaction: PostgreSQL delivers it only at commit.
func (q *Queries) NotifyLive(ctx context.Context, topic string) error {
	_, err := q.db.Exec(ctx, notifyLive, topic)
	return err
}

const pruneProjectionEvents = `-- name: PruneProjectionEvents :execrows
DELETE FROM projection_events e
USING projection_topics t
WHERE e.repository_id = t.repository_id AND e.topic = t.topic
  AND e.at < $1
  AND e.seq <= t.last_seq - $2::bigint
`

type PruneProjectionEventsParams struct {
	Cutoff time.Time `json:"cutoff"`
	Keep   int64     `json:"keep"`
}

// Deletes a topic's rows that are both older than cutoff and outside its
// newest keep rows: retention keeps the larger of the two windows (§3.3).
func (q *Queries) PruneProjectionEvents(ctx context.Context, arg PruneProjectionEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneProjectionEvents, arg.Cutoff, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
