// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_usage.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ownerAutonomyPaused = `-- name: OwnerAutonomyPaused :one
SELECT EXISTS (SELECT 1 FROM provider_connections
 WHERE user_id=$1 AND owner_type='user' AND state='active' AND used_percent >= 60)::boolean
`

func (q *Queries) OwnerAutonomyPaused(ctx context.Context, userID pgtype.Int8) (bool, error) {
	row := q.db.QueryRow(ctx, ownerAutonomyPaused, userID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const recordProviderUsage = `-- name: RecordProviderUsage :exec
UPDATE provider_connections SET used_percent=$2, usage_observed_at=clock_timestamp()
WHERE id=$1 AND state='active'
`

type RecordProviderUsageParams struct {
	ID          string        `json:"id"`
	UsedPercent pgtype.Float8 `json:"used_percent"`
}

func (q *Queries) RecordProviderUsage(ctx context.Context, arg RecordProviderUsageParams) error {
	_, err := q.db.Exec(ctx, recordProviderUsage, arg.ID, arg.UsedPercent)
	return err
}
