// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repository_registration_reports.sql

package db

import (
	"context"
	"encoding/json"
)

const getRepositoryRegistrationReport = `-- name: GetRepositoryRegistrationReport :one
SELECT host, owner, name, commit_sha, report, recorded_at
FROM repository_registration_reports
WHERE host = $1
  AND owner = $2
  AND name = $3
  AND commit_sha = $4
`

type GetRepositoryRegistrationReportParams struct {
	Host      string `json:"host"`
	Owner     string `json:"owner"`
	Name      string `json:"name"`
	CommitSha string `json:"commit_sha"`
}

func (q *Queries) GetRepositoryRegistrationReport(ctx context.Context, arg GetRepositoryRegistrationReportParams) (RepositoryRegistrationReport, error) {
	row := q.db.QueryRow(ctx, getRepositoryRegistrationReport,
		arg.Host,
		arg.Owner,
		arg.Name,
		arg.CommitSha,
	)
	var i RepositoryRegistrationReport
	err := row.Scan(
		&i.Host,
		&i.Owner,
		&i.Name,
		&i.CommitSha,
		&i.Report,
		&i.RecordedAt,
	)
	return i, err
}

const insertRepositoryRegistrationReport = `-- name: InsertRepositoryRegistrationReport :execrows
INSERT INTO repository_registration_reports (host, owner, name, commit_sha, report)
VALUES ($1, $2, $3, $4, $5::jsonb)
ON CONFLICT (host, owner, name, commit_sha) DO NOTHING
`

type InsertRepositoryRegistrationReportParams struct {
	Host      string          `json:"host"`
	Owner     string          `json:"owner"`
	Name      string          `json:"name"`
	CommitSha string          `json:"commit_sha"`
	Report    json.RawMessage `json:"report"`
}

func (q *Queries) InsertRepositoryRegistrationReport(ctx context.Context, arg InsertRepositoryRegistrationReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRepositoryRegistrationReport,
		arg.Host,
		arg.Owner,
		arg.Name,
		arg.CommitSha,
		arg.Report,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
