// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repository_transfer_requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRepositoryTransferRequest = `-- name: CreateRepositoryTransferRequest :one
INSERT INTO repository_transfer_requests
    (repository_id, sender_id, recipient_id, source_user_id, source_org_id, source_owner, source_name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, repository_id, sender_id, recipient_id, source_user_id, source_org_id, source_owner, source_name, status, created_at, expires_at, resolved_at
`

type CreateRepositoryTransferRequestParams struct {
	RepositoryID int64       `json:"repository_id"`
	SenderID     int64       `json:"sender_id"`
	RecipientID  int64       `json:"recipient_id"`
	SourceUserID pgtype.Int8 `json:"source_user_id"`
	SourceOrgID  pgtype.Int8 `json:"source_org_id"`
	SourceOwner  string      `json:"source_owner"`
	SourceName   string      `json:"source_name"`
}

func (q *Queries) CreateRepositoryTransferRequest(ctx context.Context, arg CreateRepositoryTransferRequestParams) (RepositoryTransferRequest, error) {
	row := q.db.QueryRow(ctx, createRepositoryTransferRequest,
		arg.RepositoryID,
		arg.SenderID,
		arg.RecipientID,
		arg.SourceUserID,
		arg.SourceOrgID,
		arg.SourceOwner,
		arg.SourceName,
	)
	var i RepositoryTransferRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.SenderID,
		&i.RecipientID,
		&i.SourceUserID,
		&i.SourceOrgID,
		&i.SourceOwner,
		&i.SourceName,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ResolvedAt,
	)
	return i, err
}

const expireRepositoryTransferRequests = `-- name: ExpireRepositoryTransferRequests :exec
UPDATE repository_transfer_requests SET status = 'expired', resolved_at = clock_timestamp()
WHERE repository_id = $1 AND status = 'pending' AND expires_at <= clock_timestamp()
`

func (q *Queries) ExpireRepositoryTransferRequests(ctx context.Context, repositoryID int64) error {
	_, err := q.db.Exec(ctx, expireRepositoryTransferRequests, repositoryID)
	return err
}

const getPendingRepositoryTransferRequest = `-- name: GetPendingRepositoryTransferRequest :one
SELECT id, repository_id, sender_id, recipient_id, source_user_id, source_org_id, source_owner, source_name, status, created_at, expires_at, resolved_at FROM repository_transfer_requests WHERE repository_id = $1 AND status = 'pending'
`

func (q *Queries) GetPendingRepositoryTransferRequest(ctx context.Context, repositoryID int64) (RepositoryTransferRequest, error) {
	row := q.db.QueryRow(ctx, getPendingRepositoryTransferRequest, repositoryID)
	var i RepositoryTransferRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.SenderID,
		&i.RecipientID,
		&i.SourceUserID,
		&i.SourceOrgID,
		&i.SourceOwner,
		&i.SourceName,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getRepositoryTransferRequest = `-- name: GetRepositoryTransferRequest :one
SELECT id, repository_id, sender_id, recipient_id, source_user_id, source_org_id, source_owner, source_name, status, created_at, expires_at, resolved_at FROM repository_transfer_requests WHERE id = $1
`

func (q *Queries) GetRepositoryTransferRequest(ctx context.Context, id int64) (RepositoryTransferRequest, error) {
	row := q.db.QueryRow(ctx, getRepositoryTransferRequest, id)
	var i RepositoryTransferRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.SenderID,
		&i.RecipientID,
		&i.SourceUserID,
		&i.SourceOrgID,
		&i.SourceOwner,
		&i.SourceName,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listRepositoryTransferRequests = `-- name: ListRepositoryTransferRequests :many
SELECT request.id, request.repository_id, request.sender_id, request.recipient_id, request.source_user_id, request.source_org_id, request.source_owner, request.source_name, request.status, request.created_at, request.expires_at, request.resolved_at FROM repository_transfer_requests request
JOIN repositories repo ON repo.id = request.repository_id
WHERE request.status = 'pending' AND request.expires_at > clock_timestamp()
  AND (request.recipient_id = $1 OR repo.user_id = $1
       OR EXISTS (SELECT 1 FROM org_members member
                  WHERE member.organization_id = repo.org_id
                    AND member.user_id = $1 AND member.role = 'owner'))
ORDER BY request.id
`

func (q *Queries) ListRepositoryTransferRequests(ctx context.Context, userID int64) ([]RepositoryTransferRequest, error) {
	rows, err := q.db.Query(ctx, listRepositoryTransferRequests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RepositoryTransferRequest{}
	for rows.Next() {
		var i RepositoryTransferRequest
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.SenderID,
			&i.RecipientID,
			&i.SourceUserID,
			&i.SourceOrgID,
			&i.SourceOwner,
			&i.SourceName,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveRepositoryTransferRequest = `-- name: ResolveRepositoryTransferRequest :one
UPDATE repository_transfer_requests SET status = $2, resolved_at = clock_timestamp()
WHERE id = $1 AND status = 'pending' AND expires_at > clock_timestamp()
RETURNING id, repository_id, sender_id, recipient_id, source_user_id, source_org_id, source_owner, source_name, status, created_at, expires_at, resolved_at
`

type ResolveRepositoryTransferRequestParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) ResolveRepositoryTransferRequest(ctx context.Context, arg ResolveRepositoryTransferRequestParams) (RepositoryTransferRequest, error) {
	row := q.db.QueryRow(ctx, resolveRepositoryTransferRequest, arg.ID, arg.Status)
	var i RepositoryTransferRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.SenderID,
		&i.RecipientID,
		&i.SourceUserID,
		&i.SourceOrgID,
		&i.SourceOwner,
		&i.SourceName,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ResolvedAt,
	)
	return i, err
}
