// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repository_egress_policies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRepositoryEgressPolicy = `-- name: GetRepositoryEgressPolicy :one
SELECT repository_id, allow_domains, updated_by, created_at, updated_at
FROM repository_egress_policies
WHERE repository_id = $1
`

func (q *Queries) GetRepositoryEgressPolicy(ctx context.Context, repositoryID int64) (RepositoryEgressPolicy, error) {
	row := q.db.QueryRow(ctx, getRepositoryEgressPolicy, repositoryID)
	var i RepositoryEgressPolicy
	err := row.Scan(
		&i.RepositoryID,
		&i.AllowDomains,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepositoryLiveSandboxIDs = `-- name: ListRepositoryLiveSandboxIDs :many
SELECT DISTINCT sandbox_id::text
FROM (
    SELECT w.vm_id AS sandbox_id
    FROM workspaces w
    WHERE w.repository_id = $1
      AND w.status = 'running'
      AND w.vm_id <> ''
      AND w.deleted_at IS NULL
    UNION
    SELECT t.vm_id AS sandbox_id
    FROM workflow_tasks t
    JOIN agent_sessions s ON s.workflow_run_id = t.workflow_run_id
    WHERE t.repository_id = $1
      AND t.status IN ('assigned', 'running')
      AND COALESCE(t.vm_id, '') <> ''
) live
ORDER BY sandbox_id
`

// The sandboxes of a repository whose egress proxy may be running and was
// created from the repository's policy: its running workspaces and the VMs
// of its agent sessions' live workflow tasks.
func (q *Queries) ListRepositoryLiveSandboxIDs(ctx context.Context, repositoryID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listRepositoryLiveSandboxIDs, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var sandbox_id string
		if err := rows.Scan(&sandbox_id); err != nil {
			return nil, err
		}
		items = append(items, sandbox_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRepositoryEgressPolicy = `-- name: UpsertRepositoryEgressPolicy :one
INSERT INTO repository_egress_policies (repository_id, allow_domains, updated_by)
VALUES ($1, $2::text[], $3)
ON CONFLICT (repository_id)
DO UPDATE SET
    allow_domains = EXCLUDED.allow_domains,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW()
RETURNING repository_id, allow_domains, updated_by, created_at, updated_at
`

type UpsertRepositoryEgressPolicyParams struct {
	RepositoryID int64       `json:"repository_id"`
	AllowDomains []string    `json:"allow_domains"`
	UpdatedBy    pgtype.Int8 `json:"updated_by"`
}

func (q *Queries) UpsertRepositoryEgressPolicy(ctx context.Context, arg UpsertRepositoryEgressPolicyParams) (RepositoryEgressPolicy, error) {
	row := q.db.QueryRow(ctx, upsertRepositoryEgressPolicy, arg.RepositoryID, arg.AllowDomains, arg.UpdatedBy)
	var i RepositoryEgressPolicy
	err := row.Scan(
		&i.RepositoryID,
		&i.AllowDomains,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
