package db

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"testing"
)

// Run alone with: go test packages/backend/internal/db/sqlc_regeneration_test.go
// The package TestMain starts Postgres, which this source-generation check does not need.
func TestSQLCRegenerationIsClean(t *testing.T) {
	sqlc, err := exec.LookPath("sqlc")
	if err != nil {
		t.Fatal("sqlc v1.30.0 is required on PATH: ", err)
	}
	version, err := exec.Command(sqlc, "version").CombinedOutput()
	if err != nil || strings.TrimSpace(string(version)) != "v1.30.0" {
		t.Fatalf("sqlc v1.30.0 is required (got %q, error %v)", strings.TrimSpace(string(version)), err)
	}

	_, sourceFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("locate sqlc regeneration test source")
	}
	sourceDB := filepath.Dir(sourceFile)
	moduleRoot := filepath.Clean(filepath.Join(sourceDB, "../../../.."))
	sourceProduct := filepath.Join(sourceDB, "../../db/product")
	tmp := t.TempDir()
	product := filepath.Join(tmp, "packages/backend/db/product")
	generatedDB := filepath.Join(tmp, "packages/backend/internal/db")

	copyFile := func(src, dst string) {
		t.Helper()
		data, err := os.ReadFile(src)
		if err != nil {
			t.Fatal(err)
		}
		if err := os.MkdirAll(filepath.Dir(dst), 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(dst, data, 0644); err != nil {
			t.Fatal(err)
		}
	}
	copyTree := func(name string) {
		t.Helper()
		src := filepath.Join(sourceProduct, name)
		err := filepath.WalkDir(src, func(path string, entry fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if entry.IsDir() {
				return nil
			}
			if !entry.Type().IsRegular() {
				return fmt.Errorf("unexpected sqlc input %s", path)
			}
			rel, err := filepath.Rel(src, path)
			if err != nil {
				return err
			}
			copyFile(path, filepath.Join(product, name, rel))
			return nil
		})
		if err != nil {
			t.Fatal(err)
		}
	}
	copyFile(filepath.Join(sourceProduct, "sqlc.yaml"), filepath.Join(product, "sqlc.yaml"))
	copyTree("migrations")
	copyTree("queries")

	const generatedHeader = "// Code generated by sqlc. DO NOT EDIT."
	generatedFiles := func(dir string) map[string][]byte {
		t.Helper()
		entries, err := os.ReadDir(dir)
		if err != nil {
			t.Fatal(err)
		}
		files := make(map[string][]byte)
		for _, entry := range entries {
			if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
				continue
			}
			data, err := os.ReadFile(filepath.Join(dir, entry.Name()))
			if err != nil {
				t.Fatal(err)
			}
			if bytes.HasPrefix(data, []byte(generatedHeader)) {
				files[entry.Name()] = data
			} else if dir == sourceDB {
				copyFile(filepath.Join(dir, entry.Name()), filepath.Join(generatedDB, entry.Name()))
			}
		}
		return files
	}
	committed := generatedFiles(sourceDB)
	if len(committed) == 0 {
		t.Fatal("no committed sqlc generated Go files found")
	}
	generate := func() {
		t.Helper()
		cmd := exec.Command(sqlc, "generate", "-f", "sqlc.yaml")
		cmd.Dir = product
		if output, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("sqlc generate: %v\n%s", err, output)
		}
	}
	compare := func(label string, want, got map[string][]byte) {
		t.Helper()
		var names []string
		for name := range want {
			names = append(names, name)
		}
		for name := range got {
			if _, exists := want[name]; !exists {
				names = append(names, name)
			}
		}
		slices.Sort(names)
		for _, name := range names {
			before, hadBefore := want[name]
			after, hasAfter := got[name]
			if !hadBefore || !hasAfter || !bytes.Equal(before, after) {
				t.Errorf("%s: %s differs (committed/present=%t, generated/present=%t)", label, name, hadBefore, hasAfter)
			}
		}
	}

	generate()
	first := generatedFiles(generatedDB)
	if len(first) == 0 {
		t.Fatal("sqlc generate produced no Go files")
	}
	compare("committed vs first generation", committed, first)

	// Build the generated files with the handwritten db files, without running TestMain.
	entries, err := os.ReadDir(generatedDB)
	if err != nil {
		t.Fatal(err)
	}
	args := []string{"build"}
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".go") {
			args = append(args, filepath.Join(generatedDB, entry.Name()))
		}
	}
	build := exec.Command("go", args...)
	build.Dir = moduleRoot // Use the module's dependencies and default shared Go caches.
	if output, err := build.CombinedOutput(); err != nil {
		t.Errorf("go build regenerated db bindings with handwritten sources: %v\n%s", err, output)
	}

	generate()
	compare("first vs second generation", first, generatedFiles(generatedDB))
}
