// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscription_token_scan.sql

package db

import (
	"context"
	"encoding/json"
)

const flagAgentEnvironmentSecretSubscriptionToken = `-- name: FlagAgentEnvironmentSecretSubscriptionToken :execrows
UPDATE repository_agent_environment_secrets
SET subscription_token_flagged_at = COALESCE(subscription_token_flagged_at, NOW())
WHERE repository_id = $1
  AND name = $2
  AND value_encrypted = $3
`

type FlagAgentEnvironmentSecretSubscriptionTokenParams struct {
	RepositoryID   int64  `json:"repository_id"`
	Name           string `json:"name"`
	ValueEncrypted []byte `json:"value_encrypted"`
}

func (q *Queries) FlagAgentEnvironmentSecretSubscriptionToken(ctx context.Context, arg FlagAgentEnvironmentSecretSubscriptionTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, flagAgentEnvironmentSecretSubscriptionToken, arg.RepositoryID, arg.Name, arg.ValueEncrypted)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const flagOrgSecretSubscriptionToken = `-- name: FlagOrgSecretSubscriptionToken :execrows
UPDATE organization_secrets
SET subscription_token_flagged_at = COALESCE(subscription_token_flagged_at, NOW())
WHERE id = $1
  AND value_encrypted = $2
`

type FlagOrgSecretSubscriptionTokenParams struct {
	ID             int64  `json:"id"`
	ValueEncrypted []byte `json:"value_encrypted"`
}

func (q *Queries) FlagOrgSecretSubscriptionToken(ctx context.Context, arg FlagOrgSecretSubscriptionTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, flagOrgSecretSubscriptionToken, arg.ID, arg.ValueEncrypted)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const flagRepositorySecretSubscriptionToken = `-- name: FlagRepositorySecretSubscriptionToken :execrows
UPDATE repository_secrets
SET subscription_token_flagged_at = COALESCE(subscription_token_flagged_at, NOW())
WHERE id = $1
  AND value_encrypted = $2
`

type FlagRepositorySecretSubscriptionTokenParams struct {
	ID             int64  `json:"id"`
	ValueEncrypted []byte `json:"value_encrypted"`
}

// The value must still be the one the scan read: a secret replaced since
// then passed the write-path refusal and is not flagged.
func (q *Queries) FlagRepositorySecretSubscriptionToken(ctx context.Context, arg FlagRepositorySecretSubscriptionTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, flagRepositorySecretSubscriptionToken, arg.ID, arg.ValueEncrypted)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAgentEnvironmentSecretValuesAfter = `-- name: ListAgentEnvironmentSecretValuesAfter :many
SELECT repository_id, name, value_encrypted
FROM repository_agent_environment_secrets
WHERE (repository_id, name) > ($1::bigint, $2::text)
ORDER BY repository_id, name
LIMIT $3
`

type ListAgentEnvironmentSecretValuesAfterParams struct {
	AfterRepositoryID int64  `json:"after_repository_id"`
	AfterName         string `json:"after_name"`
	PageSize          int32  `json:"page_size"`
}

type ListAgentEnvironmentSecretValuesAfterRow struct {
	RepositoryID   int64  `json:"repository_id"`
	Name           string `json:"name"`
	ValueEncrypted []byte `json:"value_encrypted"`
}

func (q *Queries) ListAgentEnvironmentSecretValuesAfter(ctx context.Context, arg ListAgentEnvironmentSecretValuesAfterParams) ([]ListAgentEnvironmentSecretValuesAfterRow, error) {
	rows, err := q.db.Query(ctx, listAgentEnvironmentSecretValuesAfter, arg.AfterRepositoryID, arg.AfterName, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentEnvironmentSecretValuesAfterRow{}
	for rows.Next() {
		var i ListAgentEnvironmentSecretValuesAfterRow
		if err := rows.Scan(&i.RepositoryID, &i.Name, &i.ValueEncrypted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentEnvironmentsAfter = `-- name: ListAgentEnvironmentsAfter :many
SELECT repository_id, setup_script, environment_variables
FROM repository_agent_environments
WHERE repository_id > $1
ORDER BY repository_id
LIMIT $2
`

type ListAgentEnvironmentsAfterParams struct {
	AfterRepositoryID int64 `json:"after_repository_id"`
	PageSize          int32 `json:"page_size"`
}

type ListAgentEnvironmentsAfterRow struct {
	RepositoryID         int64           `json:"repository_id"`
	SetupScript          string          `json:"setup_script"`
	EnvironmentVariables json.RawMessage `json:"environment_variables"`
}

func (q *Queries) ListAgentEnvironmentsAfter(ctx context.Context, arg ListAgentEnvironmentsAfterParams) ([]ListAgentEnvironmentsAfterRow, error) {
	rows, err := q.db.Query(ctx, listAgentEnvironmentsAfter, arg.AfterRepositoryID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentEnvironmentsAfterRow{}
	for rows.Next() {
		var i ListAgentEnvironmentsAfterRow
		if err := rows.Scan(&i.RepositoryID, &i.SetupScript, &i.EnvironmentVariables); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgSecretValuesAfter = `-- name: ListOrgSecretValuesAfter :many
SELECT id, organization_id, name, value_encrypted
FROM organization_secrets
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListOrgSecretValuesAfterParams struct {
	AfterID  int64 `json:"after_id"`
	PageSize int32 `json:"page_size"`
}

type ListOrgSecretValuesAfterRow struct {
	ID             int64  `json:"id"`
	OrganizationID int64  `json:"organization_id"`
	Name           string `json:"name"`
	ValueEncrypted []byte `json:"value_encrypted"`
}

func (q *Queries) ListOrgSecretValuesAfter(ctx context.Context, arg ListOrgSecretValuesAfterParams) ([]ListOrgSecretValuesAfterRow, error) {
	rows, err := q.db.Query(ctx, listOrgSecretValuesAfter, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgSecretValuesAfterRow{}
	for rows.Next() {
		var i ListOrgSecretValuesAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.ValueEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgVariablesAfter = `-- name: ListOrgVariablesAfter :many
SELECT id, organization_id, name, value
FROM organization_variables
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListOrgVariablesAfterParams struct {
	AfterID  int64 `json:"after_id"`
	PageSize int32 `json:"page_size"`
}

type ListOrgVariablesAfterRow struct {
	ID             int64  `json:"id"`
	OrganizationID int64  `json:"organization_id"`
	Name           string `json:"name"`
	Value          string `json:"value"`
}

func (q *Queries) ListOrgVariablesAfter(ctx context.Context, arg ListOrgVariablesAfterParams) ([]ListOrgVariablesAfterRow, error) {
	rows, err := q.db.Query(ctx, listOrgVariablesAfter, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgVariablesAfterRow{}
	for rows.Next() {
		var i ListOrgVariablesAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationRepositoryIDs = `-- name: ListOrganizationRepositoryIDs :many
SELECT id
FROM repositories
WHERE org_id = $1::bigint
ORDER BY id
`

func (q *Queries) ListOrganizationRepositoryIDs(ctx context.Context, organizationID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listOrganizationRepositoryIDs, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerModelCredentialValuesAfter = `-- name: ListOwnerModelCredentialValuesAfter :many
SELECT user_id, name, value_encrypted::text AS value_encrypted
FROM owner_model_credentials
WHERE value_encrypted IS NOT NULL
  AND (user_id, name) > ($1::bigint, $2::text)
ORDER BY user_id, name
LIMIT $3
`

type ListOwnerModelCredentialValuesAfterParams struct {
	AfterUserID int64  `json:"after_user_id"`
	AfterName   string `json:"after_name"`
	PageSize    int32  `json:"page_size"`
}

type ListOwnerModelCredentialValuesAfterRow struct {
	UserID         int64  `json:"user_id"`
	Name           string `json:"name"`
	ValueEncrypted string `json:"value_encrypted"`
}

func (q *Queries) ListOwnerModelCredentialValuesAfter(ctx context.Context, arg ListOwnerModelCredentialValuesAfterParams) ([]ListOwnerModelCredentialValuesAfterRow, error) {
	rows, err := q.db.Query(ctx, listOwnerModelCredentialValuesAfter, arg.AfterUserID, arg.AfterName, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnerModelCredentialValuesAfterRow{}
	for rows.Next() {
		var i ListOwnerModelCredentialValuesAfterRow
		if err := rows.Scan(&i.UserID, &i.Name, &i.ValueEncrypted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositorySecretValuesAfter = `-- name: ListRepositorySecretValuesAfter :many
SELECT id, repository_id, name, value_encrypted
FROM repository_secrets
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListRepositorySecretValuesAfterParams struct {
	AfterID  int64 `json:"after_id"`
	PageSize int32 `json:"page_size"`
}

type ListRepositorySecretValuesAfterRow struct {
	ID             int64  `json:"id"`
	RepositoryID   int64  `json:"repository_id"`
	Name           string `json:"name"`
	ValueEncrypted []byte `json:"value_encrypted"`
}

func (q *Queries) ListRepositorySecretValuesAfter(ctx context.Context, arg ListRepositorySecretValuesAfterParams) ([]ListRepositorySecretValuesAfterRow, error) {
	rows, err := q.db.Query(ctx, listRepositorySecretValuesAfter, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRepositorySecretValuesAfterRow{}
	for rows.Next() {
		var i ListRepositorySecretValuesAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Name,
			&i.ValueEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoryVariablesAfter = `-- name: ListRepositoryVariablesAfter :many
SELECT id, repository_id, name, value
FROM repository_variables
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListRepositoryVariablesAfterParams struct {
	AfterID  int64 `json:"after_id"`
	PageSize int32 `json:"page_size"`
}

type ListRepositoryVariablesAfterRow struct {
	ID           int64  `json:"id"`
	RepositoryID int64  `json:"repository_id"`
	Name         string `json:"name"`
	Value        string `json:"value"`
}

func (q *Queries) ListRepositoryVariablesAfter(ctx context.Context, arg ListRepositoryVariablesAfterParams) ([]ListRepositoryVariablesAfterRow, error) {
	rows, err := q.db.Query(ctx, listRepositoryVariablesAfter, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRepositoryVariablesAfterRow{}
	for rows.Next() {
		var i ListRepositoryVariablesAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Name,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRepositorySnapshotsRebuildRequired = `-- name: MarkRepositorySnapshotsRebuildRequired :execrows
UPDATE workspace_snapshots
SET rebuild_required_at = NOW()
WHERE repository_id = $1
  AND rebuild_required_at IS NULL
`

func (q *Queries) MarkRepositorySnapshotsRebuildRequired(ctx context.Context, repositoryID int64) (int64, error) {
	result, err := q.db.Exec(ctx, markRepositorySnapshotsRebuildRequired, repositoryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRepositoryWorkspacesRebuildRequired = `-- name: MarkRepositoryWorkspacesRebuildRequired :execrows
UPDATE workspaces
SET rebuild_required_at = NOW()
WHERE repository_id = $1
  AND deleted_at IS NULL
  AND rebuild_required_at IS NULL
`

// Every live workspace of the repository may hold what its setup delivered.
func (q *Queries) MarkRepositoryWorkspacesRebuildRequired(ctx context.Context, repositoryID int64) (int64, error) {
	result, err := q.db.Exec(ctx, markRepositoryWorkspacesRebuildRequired, repositoryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordStoredSubscriptionTokenScan = `-- name: RecordStoredSubscriptionTokenScan :exec
INSERT INTO stored_subscription_token_scan (counts)
VALUES ($1)
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) RecordStoredSubscriptionTokenScan(ctx context.Context, counts json.RawMessage) error {
	_, err := q.db.Exec(ctx, recordStoredSubscriptionTokenScan, counts)
	return err
}

const storedSubscriptionTokenScanCompleted = `-- name: StoredSubscriptionTokenScanCompleted :one
SELECT EXISTS (SELECT 1 FROM stored_subscription_token_scan)::boolean AS completed
`

func (q *Queries) StoredSubscriptionTokenScanCompleted(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, storedSubscriptionTokenScanCompleted)
	var completed bool
	err := row.Scan(&completed)
	return completed, err
}

const tryLockStoredSubscriptionTokenScan = `-- name: TryLockStoredSubscriptionTokenScan :one

SELECT pg_try_advisory_xact_lock(2206)::boolean AS locked
`

// #2206: the one-time scan for subscription tokens stored before the hosted
// refusal (services.ScanStoredSubscriptionTokens).
func (q *Queries) TryLockStoredSubscriptionTokenScan(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, tryLockStoredSubscriptionTokenScan)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}
