// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBranch = `-- name: GetBranch :one
SELECT branch_id::text AS id, repository_id, branch_name AS name, 'item'::text AS kind, id AS todo_id, github_branch
FROM todos WHERE branch_id = $1::uuid
`

type GetBranchRow struct {
	ID           string      `json:"id"`
	RepositoryID int64       `json:"repository_id"`
	Name         string      `json:"name"`
	Kind         string      `json:"kind"`
	TodoID       string      `json:"todo_id"`
	GithubBranch pgtype.Text `json:"github_branch"`
}

func (q *Queries) GetBranch(ctx context.Context, id string) (GetBranchRow, error) {
	row := q.db.QueryRow(ctx, getBranch, id)
	var i GetBranchRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Name,
		&i.Kind,
		&i.TodoID,
		&i.GithubBranch,
	)
	return i, err
}

const getTodo = `-- name: GetTodo :one
SELECT id, repository_id, number, title, state, state_reason, owner_id, issue_number, fixes_issue, stack_position, branch_id, branch_name, github_branch, pr_number, created_by_actor, flow_name, flow_digest, merging, needs_you, failure, queue, current_step, lessons, merged_at, dropped_at, version, create_key, create_digest, created_at, updated_at FROM todos WHERE id = $1
`

func (q *Queries) GetTodo(ctx context.Context, id string) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.StateReason,
		&i.OwnerID,
		&i.IssueNumber,
		&i.FixesIssue,
		&i.StackPosition,
		&i.BranchID,
		&i.BranchName,
		&i.GithubBranch,
		&i.PRNumber,
		&i.CreatedByActor,
		&i.FlowName,
		&i.FlowDigest,
		&i.Merging,
		&i.NeedsYou,
		&i.Failure,
		&i.Queue,
		&i.CurrentStep,
		&i.Lessons,
		&i.MergedAt,
		&i.DroppedAt,
		&i.Version,
		&i.CreateKey,
		&i.CreateDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodoByCreateKey = `-- name: GetTodoByCreateKey :one
SELECT id, repository_id, number, title, state, state_reason, owner_id, issue_number, fixes_issue, stack_position, branch_id, branch_name, github_branch, pr_number, created_by_actor, flow_name, flow_digest, merging, needs_you, failure, queue, current_step, lessons, merged_at, dropped_at, version, create_key, create_digest, created_at, updated_at
FROM todos
WHERE repository_id = $1
  AND created_by_actor ->> 'person' = $2::text
  AND create_key = $3::text
`

type GetTodoByCreateKeyParams struct {
	RepositoryID int64  `json:"repository_id"`
	Person       string `json:"person"`
	CreateKey    string `json:"create_key"`
}

func (q *Queries) GetTodoByCreateKey(ctx context.Context, arg GetTodoByCreateKeyParams) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodoByCreateKey, arg.RepositoryID, arg.Person, arg.CreateKey)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.StateReason,
		&i.OwnerID,
		&i.IssueNumber,
		&i.FixesIssue,
		&i.StackPosition,
		&i.BranchID,
		&i.BranchName,
		&i.GithubBranch,
		&i.PRNumber,
		&i.CreatedByActor,
		&i.FlowName,
		&i.FlowDigest,
		&i.Merging,
		&i.NeedsYou,
		&i.Failure,
		&i.Queue,
		&i.CurrentStep,
		&i.Lessons,
		&i.MergedAt,
		&i.DroppedAt,
		&i.Version,
		&i.CreateKey,
		&i.CreateDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodoByNumber = `-- name: GetTodoByNumber :one
SELECT id, repository_id, number, title, state, state_reason, owner_id, issue_number, fixes_issue, stack_position, branch_id, branch_name, github_branch, pr_number, created_by_actor, flow_name, flow_digest, merging, needs_you, failure, queue, current_step, lessons, merged_at, dropped_at, version, create_key, create_digest, created_at, updated_at FROM todos WHERE repository_id = $1 AND number = $2
`

type GetTodoByNumberParams struct {
	RepositoryID int64 `json:"repository_id"`
	Number       int64 `json:"number"`
}

func (q *Queries) GetTodoByNumber(ctx context.Context, arg GetTodoByNumberParams) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodoByNumber, arg.RepositoryID, arg.Number)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.StateReason,
		&i.OwnerID,
		&i.IssueNumber,
		&i.FixesIssue,
		&i.StackPosition,
		&i.BranchID,
		&i.BranchName,
		&i.GithubBranch,
		&i.PRNumber,
		&i.CreatedByActor,
		&i.FlowName,
		&i.FlowDigest,
		&i.Merging,
		&i.NeedsYou,
		&i.Failure,
		&i.Queue,
		&i.CurrentStep,
		&i.Lessons,
		&i.MergedAt,
		&i.DroppedAt,
		&i.Version,
		&i.CreateKey,
		&i.CreateDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTodo = `-- name: InsertTodo :one
INSERT INTO todos (
    id, repository_id, number, title, state, owner_id, issue_number, fixes_issue, stack_position, branch_id, branch_name, github_branch,
    created_by_actor, flow_name, create_key, create_digest
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16
)
RETURNING id, repository_id, number, title, state, state_reason, owner_id, issue_number, fixes_issue, stack_position, branch_id, branch_name, github_branch, pr_number, created_by_actor, flow_name, flow_digest, merging, needs_you, failure, queue, current_step, lessons, merged_at, dropped_at, version, create_key, create_digest, created_at, updated_at
`

type InsertTodoParams struct {
	ID             string          `json:"id"`
	RepositoryID   int64           `json:"repository_id"`
	Number         int64           `json:"number"`
	Title          string          `json:"title"`
	State          string          `json:"state"`
	OwnerID        pgtype.Int8     `json:"owner_id"`
	IssueNumber    pgtype.Int8     `json:"issue_number"`
	FixesIssue     bool            `json:"fixes_issue"`
	StackPosition  string          `json:"stack_position"`
	BranchID       pgtype.UUID     `json:"branch_id"`
	BranchName     string          `json:"branch_name"`
	GithubBranch   pgtype.Text     `json:"github_branch"`
	CreatedByActor json.RawMessage `json:"created_by_actor"`
	FlowName       string          `json:"flow_name"`
	CreateKey      pgtype.Text     `json:"create_key"`
	CreateDigest   pgtype.Text     `json:"create_digest"`
}

func (q *Queries) InsertTodo(ctx context.Context, arg InsertTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, insertTodo,
		arg.ID,
		arg.RepositoryID,
		arg.Number,
		arg.Title,
		arg.State,
		arg.OwnerID,
		arg.IssueNumber,
		arg.FixesIssue,
		arg.StackPosition,
		arg.BranchID,
		arg.BranchName,
		arg.GithubBranch,
		arg.CreatedByActor,
		arg.FlowName,
		arg.CreateKey,
		arg.CreateDigest,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.StateReason,
		&i.OwnerID,
		&i.IssueNumber,
		&i.FixesIssue,
		&i.StackPosition,
		&i.BranchID,
		&i.BranchName,
		&i.GithubBranch,
		&i.PRNumber,
		&i.CreatedByActor,
		&i.FlowName,
		&i.FlowDigest,
		&i.Merging,
		&i.NeedsYou,
		&i.Failure,
		&i.Queue,
		&i.CurrentStep,
		&i.Lessons,
		&i.MergedAt,
		&i.DroppedAt,
		&i.Version,
		&i.CreateKey,
		&i.CreateDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTodoEvent = `-- name: InsertTodoEvent :one
INSERT INTO todo_events (todo_id, seq, actor, kind, from_state, to_state, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, todo_id, seq, at, actor, kind, from_state, to_state, payload
`

type InsertTodoEventParams struct {
	TodoID    string          `json:"todo_id"`
	Seq       int64           `json:"seq"`
	Actor     json.RawMessage `json:"actor"`
	Kind      string          `json:"kind"`
	FromState pgtype.Text     `json:"from_state"`
	ToState   string          `json:"to_state"`
	Payload   json.RawMessage `json:"payload"`
}

func (q *Queries) InsertTodoEvent(ctx context.Context, arg InsertTodoEventParams) (TodoEvent, error) {
	row := q.db.QueryRow(ctx, insertTodoEvent,
		arg.TodoID,
		arg.Seq,
		arg.Actor,
		arg.Kind,
		arg.FromState,
		arg.ToState,
		arg.Payload,
	)
	var i TodoEvent
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.Seq,
		&i.At,
		&i.Actor,
		&i.Kind,
		&i.FromState,
		&i.ToState,
		&i.Payload,
	)
	return i, err
}

const insertTodoRetryAttempt = `-- name: InsertTodoRetryAttempt :exec
INSERT INTO todo_attempts (todo_id, attempt)
SELECT $1::uuid, COALESCE(MAX(attempt), 0) + 1
FROM todo_attempts WHERE todo_id = $1::uuid
`

// The TODO row is locked by projectItem; earlier attempts/evidence are immutable.
func (q *Queries) InsertTodoRetryAttempt(ctx context.Context, todoID string) error {
	_, err := q.db.Exec(ctx, insertTodoRetryAttempt, todoID)
	return err
}

const insertTodoRevision = `-- name: InsertTodoRevision :one
INSERT INTO todo_revisions (todo_id, rev, prompt, acceptance, author_actor, reason, issue_digest)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING todo_id, rev, prompt, acceptance, seed_patch_blob, author_actor, reason, issue_digest, created_at
`

type InsertTodoRevisionParams struct {
	TodoID      string          `json:"todo_id"`
	Rev         int32           `json:"rev"`
	Prompt      string          `json:"prompt"`
	Acceptance  string          `json:"acceptance"`
	AuthorActor json.RawMessage `json:"author_actor"`
	Reason      string          `json:"reason"`
	IssueDigest pgtype.Text     `json:"issue_digest"`
}

func (q *Queries) InsertTodoRevision(ctx context.Context, arg InsertTodoRevisionParams) (TodoRevision, error) {
	row := q.db.QueryRow(ctx, insertTodoRevision,
		arg.TodoID,
		arg.Rev,
		arg.Prompt,
		arg.Acceptance,
		arg.AuthorActor,
		arg.Reason,
		arg.IssueDigest,
	)
	var i TodoRevision
	err := row.Scan(
		&i.TodoID,
		&i.Rev,
		&i.Prompt,
		&i.Acceptance,
		&i.SeedPatchBlob,
		&i.AuthorActor,
		&i.Reason,
		&i.IssueDigest,
		&i.CreatedAt,
	)
	return i, err
}

const lastTodoStackPosition = `-- name: LastTodoStackPosition :one
SELECT COALESCE(MAX(stack_position), '')::text AS stack_position
FROM todos
WHERE repository_id = $1
`

func (q *Queries) LastTodoStackPosition(ctx context.Context, repositoryID int64) (string, error) {
	row := q.db.QueryRow(ctx, lastTodoStackPosition, repositoryID)
	var stack_position string
	err := row.Scan(&stack_position)
	return stack_position, err
}

const listMythicalStackRepositories = `-- name: ListMythicalStackRepositories :many
SELECT repository_id FROM mythical_stacks ORDER BY repository_id LIMIT 2
`

// The repositories that have a stack; the TODO routes default to the only one.
func (q *Queries) ListMythicalStackRepositories(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listMythicalStackRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var repository_id int64
		if err := rows.Scan(&repository_id); err != nil {
			return nil, err
		}
		items = append(items, repository_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoEvents = `-- name: ListTodoEvents :many
SELECT id, todo_id, seq, at, actor, kind, from_state, to_state, payload FROM todo_events WHERE todo_id = $1 ORDER BY seq
`

func (q *Queries) ListTodoEvents(ctx context.Context, todoID string) ([]TodoEvent, error) {
	rows, err := q.db.Query(ctx, listTodoEvents, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoEvent{}
	for rows.Next() {
		var i TodoEvent
		if err := rows.Scan(
			&i.ID,
			&i.TodoID,
			&i.Seq,
			&i.At,
			&i.Actor,
			&i.Kind,
			&i.FromState,
			&i.ToState,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoItemFacts = `-- name: ListTodoItemFacts :many
SELECT t.id, t.number, t.state, (t.needs_you IS NOT NULL AND t.needs_you <> 'null'::jsonb)::boolean AS needs_you_open
FROM todos t
WHERE t.repository_id = $1 AND t.state NOT IN ('merged', 'dropped')
`

type ListTodoItemFactsRow struct {
	ID           string `json:"id"`
	Number       int64  `json:"number"`
	State        string `json:"state"`
	NeedsYouOpen bool   `json:"needs_you_open"`
}

// What the stack engine reads of its unsettled items' TODOs in one pass.
func (q *Queries) ListTodoItemFacts(ctx context.Context, repositoryID int64) ([]ListTodoItemFactsRow, error) {
	rows, err := q.db.Query(ctx, listTodoItemFacts, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTodoItemFactsRow{}
	for rows.Next() {
		var i ListTodoItemFactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.State,
			&i.NeedsYouOpen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoNumbers = `-- name: ListTodoNumbers :many
SELECT id, number FROM todos WHERE repository_id = $1
`

type ListTodoNumbersRow struct {
	ID     string `json:"id"`
	Number int64  `json:"number"`
}

func (q *Queries) ListTodoNumbers(ctx context.Context, repositoryID int64) ([]ListTodoNumbersRow, error) {
	rows, err := q.db.Query(ctx, listTodoNumbers, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTodoNumbersRow{}
	for rows.Next() {
		var i ListTodoNumbersRow
		if err := rows.Scan(&i.ID, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoRevisions = `-- name: ListTodoRevisions :many
SELECT todo_id, rev, prompt, acceptance, seed_patch_blob, author_actor, reason, issue_digest, created_at FROM todo_revisions WHERE todo_id = $1 ORDER BY rev
`

func (q *Queries) ListTodoRevisions(ctx context.Context, todoID string) ([]TodoRevision, error) {
	rows, err := q.db.Query(ctx, listTodoRevisions, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoRevision{}
	for rows.Next() {
		var i TodoRevision
		if err := rows.Scan(
			&i.TodoID,
			&i.Rev,
			&i.Prompt,
			&i.Acceptance,
			&i.SeedPatchBlob,
			&i.AuthorActor,
			&i.Reason,
			&i.IssueDigest,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodos = `-- name: ListTodos :many
SELECT t.id, t.repository_id, t.number, t.title, t.state, t.state_reason, t.owner_id, t.issue_number, t.fixes_issue, t.stack_position, t.branch_id, t.branch_name, t.github_branch, t.pr_number, t.created_by_actor, t.flow_name, t.flow_digest, t.merging, t.needs_you, t.failure, t.queue, t.current_step, t.lessons, t.merged_at, t.dropped_at, t.version, t.create_key, t.create_digest, t.created_at, t.updated_at, t.branch_name,
       (SELECT count(*) FROM todo_revisions r WHERE r.todo_id = t.id)::bigint AS revisions,
       (SELECT COALESCE(max(e.seq), 0) FROM todo_events e WHERE e.todo_id = t.id)::bigint AS seq,
       (sum(CASE WHEN t.state NOT IN ('merged', 'dropped') THEN 1 ELSE 0 END)
          OVER (ORDER BY (t.state IN ('merged', 'dropped')), t.stack_position, t.number))::bigint AS place
FROM todos t
WHERE t.repository_id = $1
ORDER BY (t.state IN ('merged', 'dropped')), t.stack_position, t.number
LIMIT $2
`

type ListTodosParams struct {
	RepositoryID int64 `json:"repository_id"`
	Limit        int32 `json:"limit"`
}

type ListTodosRow struct {
	Todo       Todo   `json:"todo"`
	BranchName string `json:"branch_name"`
	Revisions  int64  `json:"revisions"`
	Seq        int64  `json:"seq"`
	Place      int64  `json:"place"`
}

// A repository's TODOs in stack order, unmerged first-to-last, then the
// merged and dropped ones.
func (q *Queries) ListTodos(ctx context.Context, arg ListTodosParams) ([]ListTodosRow, error) {
	rows, err := q.db.Query(ctx, listTodos, arg.RepositoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTodosRow{}
	for rows.Next() {
		var i ListTodosRow
		if err := rows.Scan(
			&i.Todo.ID,
			&i.Todo.RepositoryID,
			&i.Todo.Number,
			&i.Todo.Title,
			&i.Todo.State,
			&i.Todo.StateReason,
			&i.Todo.OwnerID,
			&i.Todo.IssueNumber,
			&i.Todo.FixesIssue,
			&i.Todo.StackPosition,
			&i.Todo.BranchID,
			&i.Todo.BranchName,
			&i.Todo.GithubBranch,
			&i.Todo.PRNumber,
			&i.Todo.CreatedByActor,
			&i.Todo.FlowName,
			&i.Todo.FlowDigest,
			&i.Todo.Merging,
			&i.Todo.NeedsYou,
			&i.Todo.Failure,
			&i.Todo.Queue,
			&i.Todo.CurrentStep,
			&i.Todo.Lessons,
			&i.Todo.MergedAt,
			&i.Todo.DroppedAt,
			&i.Todo.Version,
			&i.Todo.CreateKey,
			&i.Todo.CreateDigest,
			&i.Todo.CreatedAt,
			&i.Todo.UpdatedAt,
			&i.BranchName,
			&i.Revisions,
			&i.Seq,
			&i.Place,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTodoCreation = `-- name: LockTodoCreation :exec

SELECT pg_advisory_xact_lock(hashtextextended('smithers.todos.create:' || $1::bigint::text, 0))
`

// TODOs, their revisions, events and item branch facts (spec §3, §4.1;
// services/todo_service.go is the only writer).
// Serializes a repository's TODO creation until commit, so its numbers stay
// sequential with no gap and its append positions never collide.
func (q *Queries) LockTodoCreation(ctx context.Context, repositoryID int64) error {
	_, err := q.db.Exec(ctx, lockTodoCreation, repositoryID)
	return err
}

const memberOfUser = `-- name: MemberOfUser :one
SELECT id FROM members WHERE user_id = $1 AND removed_at IS NULL AND suspended_at IS NULL
`

// The member a signed-in user is, while they have access.
func (q *Queries) MemberOfUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, memberOfUser, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const nextTodoEventSeq = `-- name: NextTodoEventSeq :one
SELECT (COALESCE(MAX(seq), 0) + 1)::bigint AS seq FROM todo_events WHERE todo_id = $1
`

func (q *Queries) NextTodoEventSeq(ctx context.Context, todoID string) (int64, error) {
	row := q.db.QueryRow(ctx, nextTodoEventSeq, todoID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const nextTodoNumber = `-- name: NextTodoNumber :one
SELECT (COALESCE(MAX(number), 0) + 1)::bigint AS number FROM todos WHERE repository_id = $1
`

func (q *Queries) NextTodoNumber(ctx context.Context, repositoryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, nextTodoNumber, repositoryID)
	var number int64
	err := row.Scan(&number)
	return number, err
}

const settleTodoWaits = `-- name: SettleTodoWaits :exec
UPDATE todo_waits
SET settled_at = NOW(), settled_by = $1, outcome = $2::text
WHERE todo_id = $3 AND settled_at IS NULL
`

type SettleTodoWaitsParams struct {
	Actor   []byte `json:"actor"`
	Outcome string `json:"outcome"`
	TodoID  string `json:"todo_id"`
}

// End every open wait with the TODO, leaving settled answers intact.
func (q *Queries) SettleTodoWaits(ctx context.Context, arg SettleTodoWaitsParams) error {
	_, err := q.db.Exec(ctx, settleTodoWaits, arg.Actor, arg.Outcome, arg.TodoID)
	return err
}

const todoBranchName = `-- name: TodoBranchName :one
SELECT todo_branch_name($1::bigint, $2::text)::text AS name
`

type TodoBranchNameParams struct {
	RepositoryID int64  `json:"repository_id"`
	Title        string `json:"title"`
}

func (q *Queries) TodoBranchName(ctx context.Context, arg TodoBranchNameParams) (string, error) {
	row := q.db.QueryRow(ctx, todoBranchName, arg.RepositoryID, arg.Title)
	var name string
	err := row.Scan(&name)
	return name, err
}

const unmergedTodoPlace = `-- name: UnmergedTodoPlace :one
SELECT count(*)::bigint AS place
FROM todos t
WHERE t.repository_id = $1
  AND t.state NOT IN ('merged', 'dropped')
  AND t.stack_position <= $2::text COLLATE "C"
`

type UnmergedTodoPlaceParams struct {
	RepositoryID  int64  `json:"repository_id"`
	StackPosition string `json:"stack_position"`
}

// A TODO's 1-based place among its repository's unmerged, undropped TODOs.
func (q *Queries) UnmergedTodoPlace(ctx context.Context, arg UnmergedTodoPlaceParams) (int64, error) {
	row := q.db.QueryRow(ctx, unmergedTodoPlace, arg.RepositoryID, arg.StackPosition)
	var place int64
	err := row.Scan(&place)
	return place, err
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos SET
    state = $1::varchar(16),
    state_reason = $2,
    merging = CASE WHEN $1::varchar(16) IN ('merged', 'dropped') THEN NULL ELSE merging END,
    pr_number = $3,
    needs_you = $4,
    failure = $5,
    queue = $6,
    current_step = $7,
    lessons = $8,
    merged_at = $9,
    dropped_at = $10,
    version = version + 1,
    updated_at = NOW()
WHERE id = $11 AND version = $12
RETURNING id, repository_id, number, title, state, state_reason, owner_id, issue_number, fixes_issue, stack_position, branch_id, branch_name, github_branch, pr_number, created_by_actor, flow_name, flow_digest, merging, needs_you, failure, queue, current_step, lessons, merged_at, dropped_at, version, create_key, create_digest, created_at, updated_at
`

type UpdateTodoParams struct {
	State       string             `json:"state"`
	StateReason string             `json:"state_reason"`
	PRNumber    pgtype.Int8        `json:"pr_number"`
	NeedsYou    json.RawMessage    `json:"needs_you"`
	Failure     json.RawMessage    `json:"failure"`
	Queue       json.RawMessage    `json:"queue"`
	CurrentStep pgtype.Text        `json:"current_step"`
	Lessons     int32              `json:"lessons"`
	MergedAt    pgtype.Timestamptz `json:"merged_at"`
	DroppedAt   pgtype.Timestamptz `json:"dropped_at"`
	ID          string             `json:"id"`
	Version     int64              `json:"version"`
}

// The conditional write every TODO change goes through: it answers no row
// when another writer changed the TODO since version was read.
func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.State,
		arg.StateReason,
		arg.PRNumber,
		arg.NeedsYou,
		arg.Failure,
		arg.Queue,
		arg.CurrentStep,
		arg.Lessons,
		arg.MergedAt,
		arg.DroppedAt,
		arg.ID,
		arg.Version,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.StateReason,
		&i.OwnerID,
		&i.IssueNumber,
		&i.FixesIssue,
		&i.StackPosition,
		&i.BranchID,
		&i.BranchName,
		&i.GithubBranch,
		&i.PRNumber,
		&i.CreatedByActor,
		&i.FlowName,
		&i.FlowDigest,
		&i.Merging,
		&i.NeedsYou,
		&i.Failure,
		&i.Queue,
		&i.CurrentStep,
		&i.Lessons,
		&i.MergedAt,
		&i.DroppedAt,
		&i.Version,
		&i.CreateKey,
		&i.CreateDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
