// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wiki.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSearchWikiPagesByRepo = `-- name: CountSearchWikiPagesByRepo :one
SELECT COUNT(*)
FROM wiki_pages
WHERE repository_id = $1 AND visibility = coalesce(nullif($2::text,''),'public')
  AND (
    strpos(lower(title), lower($3::text)) > 0
    OR strpos(lower(slug), lower($3::text)) > 0
    OR strpos(lower(body), lower($3::text)) > 0
  )
`

type CountSearchWikiPagesByRepoParams struct {
	RepositoryID int64  `json:"repository_id"`
	Visibility   string `json:"visibility"`
	Query        string `json:"query"`
}

func (q *Queries) CountSearchWikiPagesByRepo(ctx context.Context, arg CountSearchWikiPagesByRepoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchWikiPagesByRepo, arg.RepositoryID, arg.Visibility, arg.Query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWikiPagesByRepo = `-- name: CountWikiPagesByRepo :one
SELECT COUNT(*)
FROM wiki_pages
WHERE repository_id = $1 AND visibility = coalesce(nullif($2::text,''),'public')
`

type CountWikiPagesByRepoParams struct {
	RepositoryID int64  `json:"repository_id"`
	Visibility   string `json:"visibility"`
}

func (q *Queries) CountWikiPagesByRepo(ctx context.Context, arg CountWikiPagesByRepoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWikiPagesByRepo, arg.RepositoryID, arg.Visibility)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWikiAttachment = `-- name: CreateWikiAttachment :one
INSERT INTO wiki_pages(repository_id,visibility,slug,path,title,body,author_id,attachment)
VALUES($1,$2,$3,$4,$5,'',$6,$7) RETURNING id, repository_id, slug, title, body, author_id, created_at, updated_at, revision, crdt_state, crdt_vector, last_update_id, last_update, visibility, path, content_digest, attachment, title_source
`

type CreateWikiAttachmentParams struct {
	RepositoryID int64  `json:"repository_id"`
	Visibility   string `json:"visibility"`
	Slug         string `json:"slug"`
	Path         string `json:"path"`
	Title        string `json:"title"`
	AuthorID     int64  `json:"author_id"`
	Attachment   []byte `json:"attachment"`
}

func (q *Queries) CreateWikiAttachment(ctx context.Context, arg CreateWikiAttachmentParams) (WikiPage, error) {
	row := q.db.QueryRow(ctx, createWikiAttachment,
		arg.RepositoryID,
		arg.Visibility,
		arg.Slug,
		arg.Path,
		arg.Title,
		arg.AuthorID,
		arg.Attachment,
	)
	var i WikiPage
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
		&i.CrdtState,
		&i.CrdtVector,
		&i.LastUpdateID,
		&i.LastUpdate,
		&i.Visibility,
		&i.Path,
		&i.ContentDigest,
		&i.Attachment,
		&i.TitleSource,
	)
	return i, err
}

const createWikiPage = `-- name: CreateWikiPage :one
INSERT INTO wiki_pages (repository_id, slug, title, body, author_id, visibility, path, title_source)
VALUES ($1, $2, $3, $4, $5, coalesce(nullif($6::text,''),'public'), $7, coalesce($8::text, 'explicit'))
RETURNING id, repository_id, slug, title, body, author_id, created_at, updated_at, revision, crdt_state, crdt_vector, last_update_id, last_update, visibility, path, content_digest, attachment, title_source
`

type CreateWikiPageParams struct {
	RepositoryID int64       `json:"repository_id"`
	Slug         string      `json:"slug"`
	Title        string      `json:"title"`
	Body         string      `json:"body"`
	AuthorID     int64       `json:"author_id"`
	Visibility   string      `json:"visibility"`
	Path         string      `json:"path"`
	TitleSource  pgtype.Text `json:"title_source"`
}

func (q *Queries) CreateWikiPage(ctx context.Context, arg CreateWikiPageParams) (WikiPage, error) {
	row := q.db.QueryRow(ctx, createWikiPage,
		arg.RepositoryID,
		arg.Slug,
		arg.Title,
		arg.Body,
		arg.AuthorID,
		arg.Visibility,
		arg.Path,
		arg.TitleSource,
	)
	var i WikiPage
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
		&i.CrdtState,
		&i.CrdtVector,
		&i.LastUpdateID,
		&i.LastUpdate,
		&i.Visibility,
		&i.Path,
		&i.ContentDigest,
		&i.Attachment,
		&i.TitleSource,
	)
	return i, err
}

const deleteWikiPage = `-- name: DeleteWikiPage :execrows
DELETE FROM wiki_pages
WHERE id = $1
  AND ($2::bigint IS NULL OR revision = $2)
`

type DeleteWikiPageParams struct {
	ID               int64       `json:"id"`
	ExpectedRevision pgtype.Int8 `json:"expected_revision"`
}

// A null expected_revision deletes whatever the page holds.
func (q *Queries) DeleteWikiPage(ctx context.Context, arg DeleteWikiPageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWikiPage, arg.ID, arg.ExpectedRevision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWikiLatestRevision = `-- name: GetWikiLatestRevision :one
SELECT id, repository_id, page_id, revision, slug, title, body, author_id, author_username, update_id, update_bytes, deleted, history_commit_id, created_at, visibility, path, content_digest, attachment, sequence, crdt_state, crdt_vector, title_source, source_commit FROM wiki_page_revisions WHERE repository_id=$1 AND visibility=$2 AND page_id=$3 ORDER BY revision DESC LIMIT 1
`

type GetWikiLatestRevisionParams struct {
	RepositoryID int64  `json:"repository_id"`
	Visibility   string `json:"visibility"`
	PageID       int64  `json:"page_id"`
}

func (q *Queries) GetWikiLatestRevision(ctx context.Context, arg GetWikiLatestRevisionParams) (WikiPageRevision, error) {
	row := q.db.QueryRow(ctx, getWikiLatestRevision, arg.RepositoryID, arg.Visibility, arg.PageID)
	var i WikiPageRevision
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.PageID,
		&i.Revision,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.AuthorID,
		&i.AuthorUsername,
		&i.UpdateID,
		&i.UpdateBytes,
		&i.Deleted,
		&i.HistoryCommitID,
		&i.CreatedAt,
		&i.Visibility,
		&i.Path,
		&i.ContentDigest,
		&i.Attachment,
		&i.Sequence,
		&i.CrdtState,
		&i.CrdtVector,
		&i.TitleSource,
		&i.SourceCommit,
	)
	return i, err
}

const getWikiPageBySlug = `-- name: GetWikiPageBySlug :one
SELECT
    wp.id,
    wp.repository_id,
    wp.slug,
    wp.title,
    wp.body,
    wp.author_id,
    wp.created_at,
    wp.updated_at,
    wp.revision,
    wp.visibility, wp.path, wp.content_digest, wp.attachment, wp.title_source,
    u.username AS author_username
FROM wiki_pages wp
JOIN users u ON u.id = wp.author_id
WHERE wp.repository_id = $1 AND wp.visibility = coalesce(nullif($3::text,''),'public') AND wp.slug = $2
`

type GetWikiPageBySlugParams struct {
	RepositoryID int64  `json:"repository_id"`
	Slug         string `json:"slug"`
	Visibility   string `json:"visibility"`
}

type GetWikiPageBySlugRow struct {
	ID             int64     `json:"id"`
	RepositoryID   int64     `json:"repository_id"`
	Slug           string    `json:"slug"`
	Title          string    `json:"title"`
	Body           string    `json:"body"`
	AuthorID       int64     `json:"author_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Revision       int64     `json:"revision"`
	Visibility     string    `json:"visibility"`
	Path           string    `json:"path"`
	ContentDigest  string    `json:"content_digest"`
	Attachment     []byte    `json:"attachment"`
	TitleSource    string    `json:"title_source"`
	AuthorUsername string    `json:"author_username"`
}

func (q *Queries) GetWikiPageBySlug(ctx context.Context, arg GetWikiPageBySlugParams) (GetWikiPageBySlugRow, error) {
	row := q.db.QueryRow(ctx, getWikiPageBySlug, arg.RepositoryID, arg.Slug, arg.Visibility)
	var i GetWikiPageBySlugRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
		&i.Visibility,
		&i.Path,
		&i.ContentDigest,
		&i.Attachment,
		&i.TitleSource,
		&i.AuthorUsername,
	)
	return i, err
}

const getWikiRevisionByNumber = `-- name: GetWikiRevisionByNumber :one
SELECT id, repository_id, page_id, revision, slug, title, body, author_id, author_username, update_id, update_bytes, deleted, history_commit_id, created_at, visibility, path, content_digest, attachment, sequence, crdt_state, crdt_vector, title_source, source_commit FROM wiki_page_revisions WHERE repository_id=$1 AND visibility=$2 AND page_id=$3 AND revision=$4
`

type GetWikiRevisionByNumberParams struct {
	RepositoryID int64  `json:"repository_id"`
	Visibility   string `json:"visibility"`
	PageID       int64  `json:"page_id"`
	Revision     int64  `json:"revision"`
}

func (q *Queries) GetWikiRevisionByNumber(ctx context.Context, arg GetWikiRevisionByNumberParams) (WikiPageRevision, error) {
	row := q.db.QueryRow(ctx, getWikiRevisionByNumber,
		arg.RepositoryID,
		arg.Visibility,
		arg.PageID,
		arg.Revision,
	)
	var i WikiPageRevision
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.PageID,
		&i.Revision,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.AuthorID,
		&i.AuthorUsername,
		&i.UpdateID,
		&i.UpdateBytes,
		&i.Deleted,
		&i.HistoryCommitID,
		&i.CreatedAt,
		&i.Visibility,
		&i.Path,
		&i.ContentDigest,
		&i.Attachment,
		&i.Sequence,
		&i.CrdtState,
		&i.CrdtVector,
		&i.TitleSource,
		&i.SourceCommit,
	)
	return i, err
}

const getWikiSpaceHead = `-- name: GetWikiSpaceHead :one
SELECT coalesce(max(head), 0)::bigint AS head FROM wiki_spaces WHERE repository_id = $1 AND visibility = $2
`

type GetWikiSpaceHeadParams struct {
	RepositoryID int64  `json:"repository_id"`
	Visibility   string `json:"visibility"`
}

// The last committed event sequence of one wiki, 0 before its first event.
func (q *Queries) GetWikiSpaceHead(ctx context.Context, arg GetWikiSpaceHeadParams) (int64, error) {
	row := q.db.QueryRow(ctx, getWikiSpaceHead, arg.RepositoryID, arg.Visibility)
	var head int64
	err := row.Scan(&head)
	return head, err
}

const listWikiEvents = `-- name: ListWikiEvents :many
SELECT id, repository_id, page_id, revision, slug, title, body, author_id, author_username, update_id, update_bytes, deleted, history_commit_id, created_at, visibility, path, content_digest, attachment, sequence, crdt_state, crdt_vector, title_source, source_commit FROM wiki_page_revisions WHERE repository_id=$1 AND visibility=$2 AND sequence>$3 ORDER BY sequence LIMIT $4
`

type ListWikiEventsParams struct {
	RepositoryID int64  `json:"repository_id"`
	Visibility   string `json:"visibility"`
	Sequence     int64  `json:"sequence"`
	Limit        int32  `json:"limit"`
}

func (q *Queries) ListWikiEvents(ctx context.Context, arg ListWikiEventsParams) ([]WikiPageRevision, error) {
	rows, err := q.db.Query(ctx, listWikiEvents,
		arg.RepositoryID,
		arg.Visibility,
		arg.Sequence,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WikiPageRevision{}
	for rows.Next() {
		var i WikiPageRevision
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.PageID,
			&i.Revision,
			&i.Slug,
			&i.Title,
			&i.Body,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.UpdateID,
			&i.UpdateBytes,
			&i.Deleted,
			&i.HistoryCommitID,
			&i.CreatedAt,
			&i.Visibility,
			&i.Path,
			&i.ContentDigest,
			&i.Attachment,
			&i.Sequence,
			&i.CrdtState,
			&i.CrdtVector,
			&i.TitleSource,
			&i.SourceCommit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWikiIndex = `-- name: ListWikiIndex :many
SELECT wp.id, wp.repository_id, wp.slug, wp.title, wp.body, wp.author_id, wp.created_at, wp.updated_at, wp.revision, wp.crdt_state, wp.crdt_vector, wp.last_update_id, wp.last_update, wp.visibility, wp.path, wp.content_digest, wp.attachment, wp.title_source, u.username AS author_username
FROM wiki_pages wp JOIN users u ON u.id = wp.author_id
WHERE wp.repository_id = $1 AND wp.visibility = $2
ORDER BY wp.id
`

type ListWikiIndexParams struct {
	RepositoryID int64  `json:"repository_id"`
	Visibility   string `json:"visibility"`
}

type ListWikiIndexRow struct {
	ID             int64       `json:"id"`
	RepositoryID   int64       `json:"repository_id"`
	Slug           string      `json:"slug"`
	Title          string      `json:"title"`
	Body           string      `json:"body"`
	AuthorID       int64       `json:"author_id"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	Revision       int64       `json:"revision"`
	CrdtState      []byte      `json:"crdt_state"`
	CrdtVector     []byte      `json:"crdt_vector"`
	LastUpdateID   pgtype.UUID `json:"last_update_id"`
	LastUpdate     []byte      `json:"last_update"`
	Visibility     string      `json:"visibility"`
	Path           string      `json:"path"`
	ContentDigest  string      `json:"content_digest"`
	Attachment     []byte      `json:"attachment"`
	TitleSource    string      `json:"title_source"`
	AuthorUsername string      `json:"author_username"`
}

func (q *Queries) ListWikiIndex(ctx context.Context, arg ListWikiIndexParams) ([]ListWikiIndexRow, error) {
	rows, err := q.db.Query(ctx, listWikiIndex, arg.RepositoryID, arg.Visibility)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWikiIndexRow{}
	for rows.Next() {
		var i ListWikiIndexRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Slug,
			&i.Title,
			&i.Body,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Revision,
			&i.CrdtState,
			&i.CrdtVector,
			&i.LastUpdateID,
			&i.LastUpdate,
			&i.Visibility,
			&i.Path,
			&i.ContentDigest,
			&i.Attachment,
			&i.TitleSource,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWikiPagesByRepo = `-- name: ListWikiPagesByRepo :many
SELECT
    wp.id,
    wp.repository_id,
    wp.slug,
    wp.title,
    wp.body,
    wp.author_id,
    wp.created_at,
    wp.updated_at,
    wp.revision,
    wp.visibility, wp.path, wp.content_digest, wp.attachment, wp.title_source,
    u.username AS author_username
FROM wiki_pages wp
JOIN users u ON u.id = wp.author_id
WHERE wp.repository_id = $1 AND wp.visibility = coalesce(nullif($4::text,''),'public')
ORDER BY wp.updated_at DESC, wp.id DESC
LIMIT $2 OFFSET $3
`

type ListWikiPagesByRepoParams struct {
	RepositoryID int64  `json:"repository_id"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
	Visibility   string `json:"visibility"`
}

type ListWikiPagesByRepoRow struct {
	ID             int64     `json:"id"`
	RepositoryID   int64     `json:"repository_id"`
	Slug           string    `json:"slug"`
	Title          string    `json:"title"`
	Body           string    `json:"body"`
	AuthorID       int64     `json:"author_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Revision       int64     `json:"revision"`
	Visibility     string    `json:"visibility"`
	Path           string    `json:"path"`
	ContentDigest  string    `json:"content_digest"`
	Attachment     []byte    `json:"attachment"`
	TitleSource    string    `json:"title_source"`
	AuthorUsername string    `json:"author_username"`
}

func (q *Queries) ListWikiPagesByRepo(ctx context.Context, arg ListWikiPagesByRepoParams) ([]ListWikiPagesByRepoRow, error) {
	rows, err := q.db.Query(ctx, listWikiPagesByRepo,
		arg.RepositoryID,
		arg.Limit,
		arg.Offset,
		arg.Visibility,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWikiPagesByRepoRow{}
	for rows.Next() {
		var i ListWikiPagesByRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Slug,
			&i.Title,
			&i.Body,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Revision,
			&i.Visibility,
			&i.Path,
			&i.ContentDigest,
			&i.Attachment,
			&i.TitleSource,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordWikiRevisionSource = `-- name: RecordWikiRevisionSource :execrows
UPDATE wiki_page_revisions SET source_commit=$1
WHERE repository_id=$2 AND visibility=$3 AND page_id=$4
 AND revision=$5 AND author_id=$6 AND NOT deleted AND source_commit=''
`

type RecordWikiRevisionSourceParams struct {
	SourceCommit string      `json:"source_commit"`
	RepositoryID int64       `json:"repository_id"`
	Visibility   string      `json:"visibility"`
	PageID       int64       `json:"page_id"`
	Revision     int64       `json:"revision"`
	AuthorID     pgtype.Int8 `json:"author_id"`
}

func (q *Queries) RecordWikiRevisionSource(ctx context.Context, arg RecordWikiRevisionSourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordWikiRevisionSource,
		arg.SourceCommit,
		arg.RepositoryID,
		arg.Visibility,
		arg.PageID,
		arg.Revision,
		arg.AuthorID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchWikiPagesByRepo = `-- name: SearchWikiPagesByRepo :many
SELECT
    wp.id,
    wp.repository_id,
    wp.slug,
    wp.title,
    wp.body,
    wp.author_id,
    wp.created_at,
    wp.updated_at,
    wp.revision,
    wp.visibility, wp.path, wp.content_digest, wp.attachment, wp.title_source,
    u.username AS author_username
FROM wiki_pages wp
JOIN users u ON u.id = wp.author_id
WHERE wp.repository_id = $1 AND wp.visibility = coalesce(nullif($2::text,''),'public')
  AND (
    strpos(lower(wp.title), lower($3::text)) > 0
    OR strpos(lower(wp.slug), lower($3::text)) > 0
    OR strpos(lower(wp.body), lower($3::text)) > 0
  )
ORDER BY
    CASE
        WHEN lower(wp.slug) = lower($3::text) THEN 0
        WHEN lower(wp.title) = lower($3::text) THEN 1
        WHEN starts_with(lower(wp.title), lower($3::text)) THEN 2
        WHEN starts_with(lower(wp.slug), lower($3::text)) THEN 3
        ELSE 4
    END,
    wp.updated_at DESC,
    wp.id DESC
LIMIT $5 OFFSET $4
`

type SearchWikiPagesByRepoParams struct {
	RepositoryID int64  `json:"repository_id"`
	Visibility   string `json:"visibility"`
	Query        string `json:"query"`
	PageOffset   int32  `json:"page_offset"`
	PageSize     int32  `json:"page_size"`
}

type SearchWikiPagesByRepoRow struct {
	ID             int64     `json:"id"`
	RepositoryID   int64     `json:"repository_id"`
	Slug           string    `json:"slug"`
	Title          string    `json:"title"`
	Body           string    `json:"body"`
	AuthorID       int64     `json:"author_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Revision       int64     `json:"revision"`
	Visibility     string    `json:"visibility"`
	Path           string    `json:"path"`
	ContentDigest  string    `json:"content_digest"`
	Attachment     []byte    `json:"attachment"`
	TitleSource    string    `json:"title_source"`
	AuthorUsername string    `json:"author_username"`
}

func (q *Queries) SearchWikiPagesByRepo(ctx context.Context, arg SearchWikiPagesByRepoParams) ([]SearchWikiPagesByRepoRow, error) {
	rows, err := q.db.Query(ctx, searchWikiPagesByRepo,
		arg.RepositoryID,
		arg.Visibility,
		arg.Query,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchWikiPagesByRepoRow{}
	for rows.Next() {
		var i SearchWikiPagesByRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Slug,
			&i.Title,
			&i.Body,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Revision,
			&i.Visibility,
			&i.Path,
			&i.ContentDigest,
			&i.Attachment,
			&i.TitleSource,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWikiAttachment = `-- name: UpdateWikiAttachment :one
UPDATE wiki_pages SET attachment=$1, path=$2,title=$3,author_id=$4,updated_at=now(),last_update_id=NULL,last_update=NULL
WHERE id=$5 AND repository_id=$6 AND revision=$7 AND attachment IS NOT NULL
RETURNING id, repository_id, slug, title, body, author_id, created_at, updated_at, revision, crdt_state, crdt_vector, last_update_id, last_update, visibility, path, content_digest, attachment, title_source
`

type UpdateWikiAttachmentParams struct {
	Attachment       []byte `json:"attachment"`
	Path             string `json:"path"`
	Title            string `json:"title"`
	AuthorID         int64  `json:"author_id"`
	PageID           int64  `json:"page_id"`
	RepositoryID     int64  `json:"repository_id"`
	ExpectedRevision int64  `json:"expected_revision"`
}

func (q *Queries) UpdateWikiAttachment(ctx context.Context, arg UpdateWikiAttachmentParams) (WikiPage, error) {
	row := q.db.QueryRow(ctx, updateWikiAttachment,
		arg.Attachment,
		arg.Path,
		arg.Title,
		arg.AuthorID,
		arg.PageID,
		arg.RepositoryID,
		arg.ExpectedRevision,
	)
	var i WikiPage
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
		&i.CrdtState,
		&i.CrdtVector,
		&i.LastUpdateID,
		&i.LastUpdate,
		&i.Visibility,
		&i.Path,
		&i.ContentDigest,
		&i.Attachment,
		&i.TitleSource,
	)
	return i, err
}

const updateWikiPage = `-- name: UpdateWikiPage :one
UPDATE wiki_pages
SET path = $6, slug = $2,
    title = $3,
    title_source = coalesce($7::text, title_source),
    body = $4,
    author_id = $5,
    updated_at = NOW(),
    last_update_id = NULL, last_update = NULL
WHERE id = $1 AND crdt_state IS NULL AND revision = $8
RETURNING id, repository_id, slug, title, body, author_id, created_at, updated_at, revision, crdt_state, crdt_vector, last_update_id, last_update, visibility, path, content_digest, attachment, title_source
`

type UpdateWikiPageParams struct {
	ID               int64       `json:"id"`
	Slug             string      `json:"slug"`
	Title            string      `json:"title"`
	Body             string      `json:"body"`
	AuthorID         int64       `json:"author_id"`
	Path             string      `json:"path"`
	TitleSource      pgtype.Text `json:"title_source"`
	ExpectedRevision int64       `json:"expected_revision"`
}

func (q *Queries) UpdateWikiPage(ctx context.Context, arg UpdateWikiPageParams) (WikiPage, error) {
	row := q.db.QueryRow(ctx, updateWikiPage,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Body,
		arg.AuthorID,
		arg.Path,
		arg.TitleSource,
		arg.ExpectedRevision,
	)
	var i WikiPage
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
		&i.CrdtState,
		&i.CrdtVector,
		&i.LastUpdateID,
		&i.LastUpdate,
		&i.Visibility,
		&i.Path,
		&i.ContentDigest,
		&i.Attachment,
		&i.TitleSource,
	)
	return i, err
}
