// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_sandbox_claims.sql

package db

import (
	"context"
	"time"
)

const claimQueuedSandboxWorkflowRuns = `-- name: ClaimQueuedSandboxWorkflowRuns :many
WITH candidates AS MATERIALIZED (
    SELECT wr.id
    FROM workflow_runs AS wr
    LEFT JOIN workflow_sandbox_claims AS existing
      ON existing.workflow_run_id = wr.id
    WHERE wr.execution_plane = 'sandbox'
      AND (
        wr.status = 'queued'
        OR (
          wr.status = 'running'
          AND (
            (existing.claim_token IS NOT NULL AND existing.lease_expires_at <= NOW())
            OR (existing.claim_token IS NULL AND wr.updated_at <= NOW() - INTERVAL '3 hours')
          )
        )
      )
    ORDER BY wr.created_at ASC, wr.id ASC
    FOR UPDATE OF wr SKIP LOCKED
    LIMIT $1
), leased AS (
    INSERT INTO workflow_sandbox_claims (
        workflow_run_id, generation, claim_token, claimed_at, lease_expires_at
    )
    SELECT candidates.id, 1, gen_random_uuid(), NOW(), NOW() + INTERVAL '2 minutes'
    FROM candidates
    ON CONFLICT (workflow_run_id) DO UPDATE
    SET generation = workflow_sandbox_claims.generation + 1,
        claim_token = gen_random_uuid(),
        claimed_at = NOW(),
        lease_expires_at = NOW() + INTERVAL '2 minutes'
    WHERE workflow_sandbox_claims.claim_token IS NULL
       OR workflow_sandbox_claims.lease_expires_at <= NOW()
    RETURNING workflow_run_id, generation, claim_token, lease_expires_at
)
UPDATE workflow_runs AS wr
SET status = 'running',
    started_at = COALESCE(wr.started_at, NOW()),
    completed_at = NULL,
    updated_at = NOW()
FROM leased
WHERE wr.id = leased.workflow_run_id
RETURNING wr.id, wr.repository_id, wr.workflow_definition_id, wr.trigger_ref,
    wr.trigger_commit_sha, wr.trigger_event, leased.claim_token::uuid AS claim_token,
    leased.generation::bigint AS claim_generation, leased.lease_expires_at::timestamptz AS claim_lease_expires_at
`

type ClaimQueuedSandboxWorkflowRunsRow struct {
	ID                   int64     `json:"id"`
	RepositoryID         int64     `json:"repository_id"`
	WorkflowDefinitionID int64     `json:"workflow_definition_id"`
	TriggerRef           string    `json:"trigger_ref"`
	TriggerCommitSha     string    `json:"trigger_commit_sha"`
	TriggerEvent         string    `json:"trigger_event"`
	ClaimToken           string    `json:"claim_token"`
	ClaimGeneration      int64     `json:"claim_generation"`
	ClaimLeaseExpiresAt  time.Time `json:"claim_lease_expires_at"`
}

// Atomically acquire renewable, generation-fenced ownership of queued
// sandbox-plane runs. Expired leases are reclaimed immediately. A running row
// without a lease predates the lease; it is recoverable after three hours,
// the old serial five-run batch at the maximum per-run timeout.
func (q *Queries) ClaimQueuedSandboxWorkflowRuns(ctx context.Context, limitCount int32) ([]ClaimQueuedSandboxWorkflowRunsRow, error) {
	rows, err := q.db.Query(ctx, claimQueuedSandboxWorkflowRuns, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimQueuedSandboxWorkflowRunsRow{}
	for rows.Next() {
		var i ClaimQueuedSandboxWorkflowRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.WorkflowDefinitionID,
			&i.TriggerRef,
			&i.TriggerCommitSha,
			&i.TriggerEvent,
			&i.ClaimToken,
			&i.ClaimGeneration,
			&i.ClaimLeaseExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishClaimedSandboxWorkflowRun = `-- name: FinishClaimedSandboxWorkflowRun :one
WITH claim_context AS MATERIALIZED (
    SELECT
      set_config('smithers.workflow_sandbox_claim_token', $3::text, true) AS claim_token,
      set_config('smithers.workflow_sandbox_claim_generation', ($4::bigint)::text, true) AS claim_generation
)
UPDATE workflow_runs AS wr
SET status = $1::text,
    completed_at = NOW(),
    updated_at = NOW()
FROM workflow_sandbox_claims AS claim, claim_context
WHERE wr.id = $2
  AND $1::text IN ('success', 'failure')
  AND wr.status = 'running'
  AND wr.execution_plane = 'sandbox'
  AND claim.workflow_run_id = wr.id
  AND claim.claim_token = $3::uuid
  AND claim.generation = $4::bigint
RETURNING wr.id, wr.repository_id, wr.workflow_definition_id, wr.status, wr.trigger_event, wr.trigger_ref, wr.trigger_commit_sha, wr.dispatch_inputs, wr.agent_token_hash, wr.agent_token_expires_at, wr.jjhub_token_id, wr.check_run_id, wr.check_run_url, wr.started_at, wr.completed_at, wr.created_at, wr.updated_at, wr.execution_plane, wr.log_bytes, wr.log_entry_count, wr.cancel_reason
`

type FinishClaimedSandboxWorkflowRunParams struct {
	Status          string `json:"status"`
	WorkflowRunID   int64  `json:"workflow_run_id"`
	ClaimToken      string `json:"claim_token"`
	ClaimGeneration int64  `json:"claim_generation"`
}

// Write a scheduler outcome only while the caller's token and generation own
// the run. The terminal guard trigger reads the claim from the transaction
// settings and the invalidation trigger clears the lease. No row means a
// cancel, resume, or newer owner took the run.
func (q *Queries) FinishClaimedSandboxWorkflowRun(ctx context.Context, arg FinishClaimedSandboxWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, finishClaimedSandboxWorkflowRun,
		arg.Status,
		arg.WorkflowRunID,
		arg.ClaimToken,
		arg.ClaimGeneration,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.WorkflowDefinitionID,
		&i.Status,
		&i.TriggerEvent,
		&i.TriggerRef,
		&i.TriggerCommitSha,
		&i.DispatchInputs,
		&i.AgentTokenHash,
		&i.AgentTokenExpiresAt,
		&i.JjhubTokenID,
		&i.CheckRunID,
		&i.CheckRunUrl,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExecutionPlane,
		&i.LogBytes,
		&i.LogEntryCount,
		&i.CancelReason,
	)
	return i, err
}

const renewSandboxWorkflowRunClaim = `-- name: RenewSandboxWorkflowRunClaim :one
UPDATE workflow_sandbox_claims AS claim
SET claimed_at = NOW(),
    lease_expires_at = NOW() + INTERVAL '2 minutes'
WHERE claim.workflow_run_id = $1
  AND claim.claim_token = $2::uuid
  AND claim.generation = $3::bigint
  AND EXISTS (
    SELECT 1
    FROM workflow_runs AS wr
    WHERE wr.id = claim.workflow_run_id
      AND wr.execution_plane = 'sandbox'
      AND wr.status = 'running'
  )
RETURNING claim.lease_expires_at::timestamptz
`

type RenewSandboxWorkflowRunClaimParams struct {
	WorkflowRunID   int64  `json:"workflow_run_id"`
	ClaimToken      string `json:"claim_token"`
	ClaimGeneration int64  `json:"claim_generation"`
}

// Extend a live lease. No row means the token or generation no longer owns a
// running sandbox-plane run.
func (q *Queries) RenewSandboxWorkflowRunClaim(ctx context.Context, arg RenewSandboxWorkflowRunClaimParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, renewSandboxWorkflowRunClaim, arg.WorkflowRunID, arg.ClaimToken, arg.ClaimGeneration)
	var claim_lease_expires_at time.Time
	err := row.Scan(&claim_lease_expires_at)
	return claim_lease_expires_at, err
}
