// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_service_previews.sql

package db

import (
	"context"
)

const authorizePublicWorkspaceService = `-- name: AuthorizePublicWorkspaceService :one
SELECT EXISTS (
    SELECT 1 FROM workspace_service_previews p
    JOIN workspaces w ON w.id = p.workspace_id
    JOIN users u ON u.id = w.user_id
    WHERE p.workspace_id = $1 AND p.port = $2 AND p.public AND w.deleted_at IS NULL
      AND u.is_active AND NOT u.prohibit_login AND u.deleted_at IS NULL
)
`

type AuthorizePublicWorkspaceServiceParams struct {
	WorkspaceID string `json:"workspace_id"`
	Port        int32  `json:"port"`
}

func (q *Queries) AuthorizePublicWorkspaceService(ctx context.Context, arg AuthorizePublicWorkspaceServiceParams) (bool, error) {
	row := q.db.QueryRow(ctx, authorizePublicWorkspaceService, arg.WorkspaceID, arg.Port)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setWorkspaceServicePublic = `-- name: SetWorkspaceServicePublic :exec
INSERT INTO workspace_service_previews (workspace_id, port, public)
VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, port) DO UPDATE SET public = EXCLUDED.public
`

type SetWorkspaceServicePublicParams struct {
	WorkspaceID string `json:"workspace_id"`
	Port        int32  `json:"port"`
	Public      bool   `json:"public"`
}

func (q *Queries) SetWorkspaceServicePublic(ctx context.Context, arg SetWorkspaceServicePublicParams) error {
	_, err := q.db.Exec(ctx, setWorkspaceServicePublic, arg.WorkspaceID, arg.Port, arg.Public)
	return err
}

const workspaceServicePublic = `-- name: WorkspaceServicePublic :one
SELECT EXISTS (SELECT 1 FROM workspace_service_previews WHERE workspace_id = $1 AND port = $2 AND public)
`

type WorkspaceServicePublicParams struct {
	WorkspaceID string `json:"workspace_id"`
	Port        int32  `json:"port"`
}

func (q *Queries) WorkspaceServicePublic(ctx context.Context, arg WorkspaceServicePublicParams) (bool, error) {
	row := q.db.QueryRow(ctx, workspaceServicePublic, arg.WorkspaceID, arg.Port)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
