// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_children.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLiveWorkspaceChildren = `-- name: CountLiveWorkspaceChildren :one
SELECT COUNT(*)
FROM workspace_children
WHERE user_id = $1
  AND stopped_at IS NULL
`

func (q *Queries) CountLiveWorkspaceChildren(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveWorkspaceChildren, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspaceChildBatch = `-- name: CreateWorkspaceChildBatch :one
INSERT INTO workspace_child_batches (parent_workspace_id, user_id, profile, requested, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, parent_workspace_id, user_id, profile, requested, snapshot_id, snapshot_deleted_at, expires_at, created_at
`

type CreateWorkspaceChildBatchParams struct {
	ParentWorkspaceID string    `json:"parent_workspace_id"`
	UserID            int64     `json:"user_id"`
	Profile           string    `json:"profile"`
	Requested         int32     `json:"requested"`
	ExpiresAt         time.Time `json:"expires_at"`
}

func (q *Queries) CreateWorkspaceChildBatch(ctx context.Context, arg CreateWorkspaceChildBatchParams) (WorkspaceChildBatch, error) {
	row := q.db.QueryRow(ctx, createWorkspaceChildBatch,
		arg.ParentWorkspaceID,
		arg.UserID,
		arg.Profile,
		arg.Requested,
		arg.ExpiresAt,
	)
	var i WorkspaceChildBatch
	err := row.Scan(
		&i.ID,
		&i.ParentWorkspaceID,
		&i.UserID,
		&i.Profile,
		&i.Requested,
		&i.SnapshotID,
		&i.SnapshotDeletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspaceChildRows = `-- name: CreateWorkspaceChildRows :many
INSERT INTO workspaces (
    id, repository_id, user_id, name, is_fork, parent_workspace_id, target_bookmark, kind,
    environment_source, environment_revision, environment_closure_hash, environment_image,
    status, idle_timeout_secs
)
SELECT c.workspace_id, p.repository_id, p.user_id,
       'child-' || left(b.id::text, 8) || '-' || c.ordinal::text,
       TRUE, p.id, p.target_bookmark, p.kind,
       p.environment_source, p.environment_revision, p.environment_closure_hash, p.environment_image,
       'starting', 0
FROM workspace_children c
JOIN workspace_child_batches b ON b.id = c.batch_id
JOIN workspaces p ON p.id = b.parent_workspace_id
WHERE c.batch_id = $1
ORDER BY c.ordinal
RETURNING id, repository_id, user_id, name, is_fork, parent_workspace_id, target_bookmark, source_snapshot_id, kind, environment_source, environment_revision, environment_closure_hash, agent_session_id, head_push_token_id, environment_image, desktop_session_id, desktop_session_token_hash, desktop_session_expires_at, vm_id, provisioning_generation, status, failure_code, failure_message, provisioning_stage, last_activity_at, idle_timeout_secs, suspended_at, started_at, resumed_at, head_change_id, head_commit_id, ahead, behind, last_accessed_at, deleted_at, created_at, updated_at, rebuild_required_at, client_lease_secs, client_lease_expires_at
`

// A child copies its parent's repository, bookmark, kind and environment. It
// has no idle timeout of its own: the child reaper stops it when idle.
func (q *Queries) CreateWorkspaceChildRows(ctx context.Context, batchID string) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, createWorkspaceChildRows, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.UserID,
			&i.Name,
			&i.IsFork,
			&i.ParentWorkspaceID,
			&i.TargetBookmark,
			&i.SourceSnapshotID,
			&i.Kind,
			&i.EnvironmentSource,
			&i.EnvironmentRevision,
			&i.EnvironmentClosureHash,
			&i.AgentSessionID,
			&i.HeadPushTokenID,
			&i.EnvironmentImage,
			&i.DesktopSessionID,
			&i.DesktopSessionTokenHash,
			&i.DesktopSessionExpiresAt,
			&i.VmID,
			&i.ProvisioningGeneration,
			&i.Status,
			&i.FailureCode,
			&i.FailureMessage,
			&i.ProvisioningStage,
			&i.LastActivityAt,
			&i.IdleTimeoutSecs,
			&i.SuspendedAt,
			&i.StartedAt,
			&i.ResumedAt,
			&i.HeadChangeID,
			&i.HeadCommitID,
			&i.Ahead,
			&i.Behind,
			&i.LastAccessedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RebuildRequiredAt,
			&i.ClientLeaseSecs,
			&i.ClientLeaseExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceChildParentForUpdate = `-- name: GetWorkspaceChildParentForUpdate :one
SELECT id, repository_id, user_id, name, is_fork, parent_workspace_id, target_bookmark, source_snapshot_id, kind, environment_source, environment_revision, environment_closure_hash, agent_session_id, head_push_token_id, environment_image, desktop_session_id, desktop_session_token_hash, desktop_session_expires_at, vm_id, provisioning_generation, status, failure_code, failure_message, provisioning_stage, last_activity_at, idle_timeout_secs, suspended_at, started_at, resumed_at, head_change_id, head_commit_id, ahead, behind, last_accessed_at, deleted_at, created_at, updated_at, rebuild_required_at, client_lease_secs, client_lease_expires_at
FROM workspaces
WHERE id = $1
  AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetWorkspaceChildParentForUpdate(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceChildParentForUpdate, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.UserID,
		&i.Name,
		&i.IsFork,
		&i.ParentWorkspaceID,
		&i.TargetBookmark,
		&i.SourceSnapshotID,
		&i.Kind,
		&i.EnvironmentSource,
		&i.EnvironmentRevision,
		&i.EnvironmentClosureHash,
		&i.AgentSessionID,
		&i.HeadPushTokenID,
		&i.EnvironmentImage,
		&i.DesktopSessionID,
		&i.DesktopSessionTokenHash,
		&i.DesktopSessionExpiresAt,
		&i.VmID,
		&i.ProvisioningGeneration,
		&i.Status,
		&i.FailureCode,
		&i.FailureMessage,
		&i.ProvisioningStage,
		&i.LastActivityAt,
		&i.IdleTimeoutSecs,
		&i.SuspendedAt,
		&i.StartedAt,
		&i.ResumedAt,
		&i.HeadChangeID,
		&i.HeadCommitID,
		&i.Ahead,
		&i.Behind,
		&i.LastAccessedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RebuildRequiredAt,
		&i.ClientLeaseSecs,
		&i.ClientLeaseExpiresAt,
	)
	return i, err
}

const isWorkspaceChild = `-- name: IsWorkspaceChild :one
SELECT EXISTS (SELECT 1 FROM workspace_children WHERE workspace_id = $1)
`

func (q *Queries) IsWorkspaceChild(ctx context.Context, workspaceID string) (bool, error) {
	row := q.db.QueryRow(ctx, isWorkspaceChild, workspaceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listDrainedWorkspaceChildSnapshots = `-- name: ListDrainedWorkspaceChildSnapshots :many
SELECT b.id, b.snapshot_id
FROM workspace_child_batches b
WHERE b.snapshot_id <> ''
  AND b.snapshot_deleted_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM workspace_children c WHERE c.batch_id = b.id AND c.stopped_at IS NULL)
ORDER BY b.created_at, b.id
LIMIT $1
`

type ListDrainedWorkspaceChildSnapshotsRow struct {
	ID         string `json:"id"`
	SnapshotID string `json:"snapshot_id"`
}

// Batch snapshots no live child still boots from.
func (q *Queries) ListDrainedWorkspaceChildSnapshots(ctx context.Context, maxRows int32) ([]ListDrainedWorkspaceChildSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, listDrainedWorkspaceChildSnapshots, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDrainedWorkspaceChildSnapshotsRow{}
	for rows.Next() {
		var i ListDrainedWorkspaceChildSnapshotsRow
		if err := rows.Scan(&i.ID, &i.SnapshotID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReapableWorkspaceChildren = `-- name: ListReapableWorkspaceChildren :many
SELECT workspace_id, vm_id, reason::text AS reason
FROM (
    SELECT c.workspace_id, w.vm_id, c.created_at,
        CASE
            WHEN p.id IS NULL OR p.deleted_at IS NOT NULL OR p.status <> 'running' THEN 'parent_stopped'
            WHEN w.status = 'failed' THEN 'failed'
            WHEN w.deleted_at IS NOT NULL OR w.status IN ('suspended', 'stopped') THEN 'requested'
            WHEN b.expires_at <= now() THEN 'expired'
            WHEN w.status IN ('pending', 'starting') AND w.vm_id = ''
                AND c.created_at < now() - make_interval(secs => $1::int) THEN 'abandoned'
            WHEN w.status = 'running'
                AND w.last_activity_at < now() - make_interval(secs => $2::int) THEN 'idle'
        END AS reason
    FROM workspace_children c
    JOIN workspace_child_batches b ON b.id = c.batch_id
    JOIN workspaces w ON w.id = c.workspace_id
    LEFT JOIN workspaces p ON p.id = b.parent_workspace_id
    WHERE c.stopped_at IS NULL
      AND ($3::uuid IS NULL OR b.parent_workspace_id = $3::uuid)
) candidates
WHERE reason IS NOT NULL
ORDER BY created_at, workspace_id
LIMIT $4
`

type ListReapableWorkspaceChildrenParams struct {
	AbandonAfterSecs  int32       `json:"abandon_after_secs"`
	IdleAfterSecs     int32       `json:"idle_after_secs"`
	ParentWorkspaceID pgtype.UUID `json:"parent_workspace_id"`
	MaxRows           int32       `json:"max_rows"`
}

type ListReapableWorkspaceChildrenRow struct {
	WorkspaceID string `json:"workspace_id"`
	VmID        string `json:"vm_id"`
	Reason      string `json:"reason"`
}

// Live children that must stop, and why: their parent stopped, they stopped
// themselves, their batch expired, they never booted, or they went idle.
func (q *Queries) ListReapableWorkspaceChildren(ctx context.Context, arg ListReapableWorkspaceChildrenParams) ([]ListReapableWorkspaceChildrenRow, error) {
	rows, err := q.db.Query(ctx, listReapableWorkspaceChildren,
		arg.AbandonAfterSecs,
		arg.IdleAfterSecs,
		arg.ParentWorkspaceID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReapableWorkspaceChildrenRow{}
	for rows.Next() {
		var i ListReapableWorkspaceChildrenRow
		if err := rows.Scan(&i.WorkspaceID, &i.VmID, &i.Reason); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceChildOrdinals = `-- name: ListWorkspaceChildOrdinals :many
SELECT workspace_id, ordinal
FROM workspace_children
WHERE batch_id = $1
ORDER BY ordinal
`

type ListWorkspaceChildOrdinalsRow struct {
	WorkspaceID string `json:"workspace_id"`
	Ordinal     int32  `json:"ordinal"`
}

func (q *Queries) ListWorkspaceChildOrdinals(ctx context.Context, batchID string) ([]ListWorkspaceChildOrdinalsRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceChildOrdinals, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceChildOrdinalsRow{}
	for rows.Next() {
		var i ListWorkspaceChildOrdinalsRow
		if err := rows.Scan(&i.WorkspaceID, &i.Ordinal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceChildReceipts = `-- name: ListWorkspaceChildReceipts :many
SELECT c.workspace_id, c.batch_id, c.ordinal, c.vm_id, c.started_at, c.stopped_at,
       c.stop_reason, c.failure_message, b.profile, b.snapshot_id, b.expires_at, w.status
FROM workspace_children c
JOIN workspace_child_batches b ON b.id = c.batch_id
JOIN workspaces w ON w.id = c.workspace_id
WHERE b.parent_workspace_id = $1
ORDER BY b.created_at, b.id, c.ordinal
`

type ListWorkspaceChildReceiptsRow struct {
	WorkspaceID    string             `json:"workspace_id"`
	BatchID        string             `json:"batch_id"`
	Ordinal        int32              `json:"ordinal"`
	VmID           string             `json:"vm_id"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	StoppedAt      pgtype.Timestamptz `json:"stopped_at"`
	StopReason     pgtype.Text        `json:"stop_reason"`
	FailureMessage pgtype.Text        `json:"failure_message"`
	Profile        string             `json:"profile"`
	SnapshotID     string             `json:"snapshot_id"`
	ExpiresAt      time.Time          `json:"expires_at"`
	Status         string             `json:"status"`
}

func (q *Queries) ListWorkspaceChildReceipts(ctx context.Context, parentWorkspaceID string) ([]ListWorkspaceChildReceiptsRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceChildReceipts, parentWorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceChildReceiptsRow{}
	for rows.Next() {
		var i ListWorkspaceChildReceiptsRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.BatchID,
			&i.Ordinal,
			&i.VmID,
			&i.StartedAt,
			&i.StoppedAt,
			&i.StopReason,
			&i.FailureMessage,
			&i.Profile,
			&i.SnapshotID,
			&i.ExpiresAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserForWorkspaceChildren = `-- name: LockUserForWorkspaceChildren :one

SELECT id FROM users WHERE id = $1 FOR UPDATE
`

// #2802: child workspaces fanned out from one snapshot of a running parent.
// Serializes one user's child admissions so the live count cannot race.
func (q *Queries) LockUserForWorkspaceChildren(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockUserForWorkspaceChildren, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markWorkspaceChildSnapshotDeleted = `-- name: MarkWorkspaceChildSnapshotDeleted :exec
UPDATE workspace_child_batches
SET snapshot_deleted_at = now()
WHERE id = $1
  AND snapshot_deleted_at IS NULL
`

func (q *Queries) MarkWorkspaceChildSnapshotDeleted(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markWorkspaceChildSnapshotDeleted, id)
	return err
}

const reserveWorkspaceChildren = `-- name: ReserveWorkspaceChildren :exec
INSERT INTO workspace_children (workspace_id, batch_id, user_id, ordinal)
SELECT gen_random_uuid(), b.id, b.user_id, ordinal
FROM workspace_child_batches b
CROSS JOIN generate_series(0, b.requested - 1) AS ordinal
WHERE b.id = $1
`

// Written before the workspace rows (the foreign key is deferred) so the
// quota trigger sees each row as a child.
func (q *Queries) ReserveWorkspaceChildren(ctx context.Context, batchID string) error {
	_, err := q.db.Exec(ctx, reserveWorkspaceChildren, batchID)
	return err
}

const setWorkspaceChildBatchSnapshot = `-- name: SetWorkspaceChildBatchSnapshot :exec
UPDATE workspace_child_batches
SET snapshot_id = $1
WHERE id = $2
`

type SetWorkspaceChildBatchSnapshotParams struct {
	SnapshotID string `json:"snapshot_id"`
	ID         string `json:"id"`
}

func (q *Queries) SetWorkspaceChildBatchSnapshot(ctx context.Context, arg SetWorkspaceChildBatchSnapshotParams) error {
	_, err := q.db.Exec(ctx, setWorkspaceChildBatchSnapshot, arg.SnapshotID, arg.ID)
	return err
}

const startWorkspaceChild = `-- name: StartWorkspaceChild :execrows
WITH started AS (
    UPDATE workspaces
    SET vm_id = $1, status = 'running', started_at = now(),
        last_activity_at = now(), updated_at = now()
    WHERE id = $2
      AND status = 'starting'
      AND deleted_at IS NULL
      AND EXISTS (SELECT 1 FROM workspace_children c WHERE c.workspace_id = $2 AND c.stopped_at IS NULL)
    RETURNING id
)
UPDATE workspace_children c
SET vm_id = $1, started_at = now()
FROM started
WHERE c.workspace_id = started.id
`

type StartWorkspaceChildParams struct {
	VmID        string `json:"vm_id"`
	WorkspaceID string `json:"workspace_id"`
}

// Registers a booted child. Zero rows means the child was stopped while it
// booted, and the caller deletes the machine it created.
func (q *Queries) StartWorkspaceChild(ctx context.Context, arg StartWorkspaceChildParams) (int64, error) {
	result, err := q.db.Exec(ctx, startWorkspaceChild, arg.VmID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stopWorkspaceChild = `-- name: StopWorkspaceChild :one
WITH receipt AS (
    UPDATE workspace_children
    SET stopped_at = now(), stop_reason = $1::text,
        failure_message = $2
    WHERE workspace_id = $3
      AND stopped_at IS NULL
    RETURNING workspace_id
)
UPDATE workspaces w
SET status = CASE WHEN $1::text = 'failed' OR w.status = 'failed' THEN 'failed' ELSE 'stopped' END,
    failure_code = CASE WHEN $1::text = 'failed' THEN COALESCE(w.failure_code, 'child_provision_failed') ELSE w.failure_code END,
    failure_message = COALESCE($2, w.failure_message),
    deleted_at = COALESCE(w.deleted_at, now()),
    updated_at = now()
FROM receipt
WHERE w.id = receipt.workspace_id
RETURNING w.vm_id
`

type StopWorkspaceChildParams struct {
	StopReason     string      `json:"stop_reason"`
	FailureMessage pgtype.Text `json:"failure_message"`
	WorkspaceID    string      `json:"workspace_id"`
}

// Closes a child's receipt once and tombstones its workspace. Returns the
// machine the child held at that moment; no row means it was already stopped.
func (q *Queries) StopWorkspaceChild(ctx context.Context, arg StopWorkspaceChildParams) (string, error) {
	row := q.db.QueryRow(ctx, stopWorkspaceChild, arg.StopReason, arg.FailureMessage, arg.WorkspaceID)
	var vm_id string
	err := row.Scan(&vm_id)
	return vm_id, err
}
