// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_share_authority.sql

package db

import (
	"context"
)

const lockWorkspaceShareForMutation = `-- name: LockWorkspaceShareForMutation :one
SELECT ws.level
FROM workspaces w
JOIN workspace_shares ws ON ws.workspace_id = w.id
WHERE w.id = $1::uuid
  AND ws.grantee_user_id = $2::bigint
  AND w.deleted_at IS NULL
FOR KEY SHARE OF w
FOR SHARE OF ws
`

type LockWorkspaceShareForMutationParams struct {
	WorkspaceID   string `json:"workspace_id"`
	GranteeUserID int64  `json:"grantee_user_id"`
}

// Returns a grantee's share level on a live workspace and holds the share row
// (and the workspace key) until the caller's transaction ends. A mutation runs
// inside that transaction, so a revocation, demotion or hard delete waits for
// it, and a mutation that starts after the change no longer finds the grant.
func (q *Queries) LockWorkspaceShareForMutation(ctx context.Context, arg LockWorkspaceShareForMutationParams) (string, error) {
	row := q.db.QueryRow(ctx, lockWorkspaceShareForMutation, arg.WorkspaceID, arg.GranteeUserID)
	var level string
	err := row.Scan(&level)
	return level, err
}
