// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_log_retention.sql

package db

import (
	"context"
	"time"
)

const deleteWorkflowLogsOlderThan = `-- name: DeleteWorkflowLogsOlderThan :execrows
WITH run_lock AS MATERIALIZED (
 SELECT r.id FROM workflow_runs r
 WHERE r.completed_at < $1::timestamptz
   AND r.status IN ('success', 'failure', 'cancelled')
   AND EXISTS (SELECT 1 FROM workflow_logs l WHERE l.workflow_run_id = r.id AND l.created_at < $1::timestamptz)
 ORDER BY r.completed_at, r.id
 LIMIT 1
 FOR UPDATE OF r SKIP LOCKED
)
DELETE FROM workflow_logs
WHERE id IN (
 SELECT l.id FROM workflow_logs l JOIN run_lock r ON r.id = l.workflow_run_id
 WHERE l.created_at < $1::timestamptz
 ORDER BY l.created_at, l.id
 LIMIT LEAST(GREATEST($2::int, 0), 1000)
)
`

type DeleteWorkflowLogsOlderThanParams struct {
	Cutoff     time.Time `json:"cutoff"`
	BatchLimit int32     `json:"batch_limit"`
}

// Lock the parent before log rows, matching insertion and cascading deletion.
func (q *Queries) DeleteWorkflowLogsOlderThan(ctx context.Context, arg DeleteWorkflowLogsOlderThanParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkflowLogsOlderThan, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWorkflowRunLogsOlderThan = `-- name: DeleteWorkflowRunLogsOlderThan :execrows
WITH run_lock AS MATERIALIZED (
 SELECT r.id FROM workflow_runs r
 WHERE r.completed_at < $1::timestamptz
   AND r.status IN ('success', 'failure', 'cancelled')
   AND EXISTS (SELECT 1 FROM workflow_run_logs l WHERE l.workflow_run_id = r.id AND l.created_at < $1::timestamptz)
 ORDER BY r.completed_at, r.id
 LIMIT 1
 FOR UPDATE OF r SKIP LOCKED
)
DELETE FROM workflow_run_logs
WHERE id IN (
 SELECT l.id FROM workflow_run_logs l JOIN run_lock r ON r.id = l.workflow_run_id
 WHERE l.created_at < $1::timestamptz
 ORDER BY l.created_at, l.id
 LIMIT LEAST(GREATEST($2::int, 0), 1000)
)
`

type DeleteWorkflowRunLogsOlderThanParams struct {
	Cutoff     time.Time `json:"cutoff"`
	BatchLimit int32     `json:"batch_limit"`
}

// Lock the parent before log rows, matching insertion and cascading deletion.
func (q *Queries) DeleteWorkflowRunLogsOlderThan(ctx context.Context, arg DeleteWorkflowRunLogsOlderThanParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkflowRunLogsOlderThan, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
