package wire

type field struct {
	tag      byte
	required bool
	typ      string
}

var structures = map[string][]field{
	"local_request":   {{1, true, "u32"}, {2, true, "local_call"}},
	"empty":           {},
	"principal":       {{1, true, "bytes1024"}},
	"session_actor":   {{1, true, "u32"}},
	"run_actor":       {{1, true, "str"}},
	"digest_base":     {{1, true, "digest"}},
	"user":            {{1, true, "str"}, {2, true, "u32"}},
	"size":            {{1, true, "u16"}, {2, true, "u16"}},
	"challenge":       {{1, true, "magic"}, {2, true, "version"}, {3, true, "id128"}, {4, true, "digest"}},
	"proof":           {{1, true, "version"}, {2, true, "digest"}},
	"hello":           {{1, true, "bytes1024"}, {2, true, "id128"}, {3, true, "u64"}, {4, true, "sessions"}},
	"goodbye":         {{1, true, "protocol_error"}, {2, false, "str1024"}},
	"request":         {{1, true, "u32"}, {2, true, "call"}},
	"response":        {{1, true, "u32"}, {2, true, "result"}},
	"args1":           {},
	"args2":           {{1, true, "str"}, {2, false, "oid"}},
	"args3":           {{1, true, "str"}, {2, true, "base"}, {3, true, "content"}, {4, true, "host_actor"}},
	"args4":           {},
	"args5":           {{1, true, "oid"}},
	"args6":           {{1, true, "user"}, {2, true, "session_kind"}, {3, false, "list:str"}, {4, false, "size"}, {5, false, "id128"}, {6, false, "str"}},
	"args7":           {{1, true, "u16"}, {2, false, "id128"}, {3, false, "str"}},
	"args8":           {{1, true, "u32"}},
	"args9":           {{1, true, "target"}},
	"args10":          {{1, true, "str"}, {2, true, "u32"}},
	"args11":          {{1, true, "oid"}, {2, true, "host_actor"}},
	"args12":          {{1, true, "host_actor"}},
	"args13":          {{1, true, "str"}, {2, false, "host_actor"}},
	"args14":          {{1, true, "u32"}},
	"args15":          {{1, true, "u32"}, {2, true, "u64"}},
	"args16":          {{1, true, "list:user"}},
	"result16":        {},
	"raced":           {{1, true, "str"}, {2, true, "digest"}, {3, true, "version_ref"}},
	"args17":          {{1, true, "list:local_mutation"}, {2, true, "host_actor"}},
	"local_mutation":  {{1, true, "str"}, {2, true, "base"}, {3, false, "content"}},
	"mutation_result": {{1, true, "base"}, {2, false, "raced"}},
	"local_batch":     {{1, true, "list:local_mutation"}},
	"result17":        {{1, true, "list:mutation_result"}, {2, false, "batch_failure"}},
	"batch_failure":   {{1, true, "u16"}, {2, true, "bool"}, {3, true, "error"}},
	"local_write":     {{1, true, "str"}, {2, true, "base"}, {3, true, "content"}},
	"result1":         {{1, true, "state"}, {2, true, "version"}, {3, true, "str"}, {4, true, "u32"}, {5, false, "oid"}, {6, true, "u16"}},
	"result2":         {{1, true, "content"}, {2, true, "digest"}, {3, true, "u32"}},
	"result3":         {{1, true, "digest"}, {2, false, "raced"}},
	"result4":         {{1, true, "oid"}, {2, true, "oid"}, {3, true, "u16"}},
	"result5":         {{1, true, "outcome"}},
	"result6":         {{1, true, "u32"}},
	"result7":         {{1, true, "u32"}},
	"result8":         {},
	"result9":         {{1, true, "u16"}},
	"result10":        {},
	"result11":        {{1, true, "oid"}},
	"result12":        {{1, true, "oid"}},
	"result13":        {{1, true, "u32"}},
	"result14":        {},
	"result15":        {{1, true, "u64"}},
	"target_user":     {{1, true, "user"}},
	"moved":           {{1, true, "oid"}},
	"conflict":        {{1, true, "list:str"}},
	"error":           {{1, true, "error_code"}, {2, false, "str"}, {3, false, "digest"}, {4, false, "u32"}, {5, false, "u32"}, {6, false, "protocol_error"}, {7, false, "list:oid"}},
	"durable":         {{1, true, "u64"}, {2, true, "id128"}, {3, true, "event"}},
	"hint_wrapper":    {{1, true, "hint"}},
	"ack":             {{1, true, "u64"}, {2, true, "ack_outcome"}, {3, false, "list:oid"}, {4, false, "error"}, {5, false, "list:oid"}},
	"burst":           {{1, true, "id128"}, {2, true, "actor"}, {3, true, "list:burst_file"}, {4, true, "oid"}, {5, false, "u16"}, {6, false, "u16"}},
	"burst_file":      {{1, true, "str"}, {2, true, "change"}, {3, false, "str"}, {4, false, "oid"}, {5, false, "oid"}, {6, false, "digest"}},
	"moved_off":       {{1, true, "actor"}, {2, true, "u64"}, {3, true, "oid"}, {4, false, "bool"}},
	"captured":        {{1, true, "oid"}, {2, true, "oid"}, {3, true, "oid"}},
	"reconciled":      {{1, true, "oid"}, {2, true, "oid"}, {3, true, "reconcile_outcome"}, {4, false, "list:str"}},
	"written":         {{1, true, "str"}, {2, true, "actor"}, {3, false, "digest"}},
	"transcript":      {{1, true, "u16"}, {2, true, "u32"}, {3, true, "id128"}, {4, true, "id128"}, {5, true, "str"}, {6, true, "u64"}, {7, true, "u64"}, {8, true, "u64"}, {9, true, "record"}},
	"snapshot":        {{1, true, "list:where"}},
	"where":           {{1, true, "u32"}, {2, false, "str"}},
}
var unions = map[string]map[byte]string{
	"local_control": {1: "local_request"},
	"actor":         {1: "principal", 2: "session_actor", 3: "run_actor", 4: "empty"},
	"host_actor":    {1: "principal"},
	"base":          {1: "digest_base", 2: "empty"},
	"hello_message": {1: "challenge", 2: "proof", 3: "hello", 4: "empty", 5: "goodbye"},
	"control":       {1: "request", 2: "response"},
	"call":          {1: "args1", 2: "args2", 3: "args3", 4: "args4", 5: "args5", 6: "args6", 7: "args7", 8: "args8", 9: "args9", 10: "args10", 11: "args11", 12: "args12", 13: "args13", 14: "args14", 15: "args15", 16: "args16", 17: "args17"},
	"local_call":    {1: "args1", 2: "args2", 3: "local_write", 6: "args6", 17: "local_batch"},
	"result":        {1: "result1", 2: "result2", 3: "result3", 4: "result4", 5: "result5", 6: "result6", 7: "result7", 8: "result8", 9: "result9", 10: "result10", 11: "result11", 12: "result12", 13: "result13", 14: "result14", 15: "result15", 16: "result16", 17: "result17", 255: "error"},
	"target":        {1: "target_user", 2: "run_actor", 3: "session_actor"},
	"outcome":       {1: "empty", 2: "moved", 3: "conflict"},
	"events":        {1: "durable", 2: "hint_wrapper", 3: "ack"},
	"event":         {1: "burst", 2: "captured", 3: "reconciled", 4: "moved_off", 5: "transcript"},
	"hint":          {1: "written"},
	"presence":      {1: "snapshot"},
}

// reserved union variants are refused with BadValue whatever their body
// (ADR 0004 ruling 3). Event 6 (doc_edit) waits for T-COL-08a. Event 5
// (transcript) is defined by ruling 2.
var reserved = map[string]map[byte]bool{"event": {6: true}}
