/** SQL fragments shared by the SQLite and PostgreSQL stores.
 * @since 1.0.0
 */

import { Effect } from "effect"
import type { SqlClient } from "effect/unstable/sql/SqlClient"
import type { Fragment } from "effect/unstable/sql/Statement"

/**
 * Is postgres.
 *
 * @category guards
 * @since 1.0.0
 */
export const isPostgres = (sql: SqlClient): boolean => sql.onDialectOrElse({ pg: () => true, orElse: () => false })
/** Numeric preserves rejected fractional writes instead of PostgreSQL bigint's rounding.
 * @category fragments
 * @since 1.0.0
 */
export const integer = (sql: SqlClient): Fragment => sql.literal(isPostgres(sql) ? "NUMERIC" : "INTEGER")
/**
 * Is integer.
 *
 * @category fragments
 * @since 1.0.0
 */
export const isInteger = (sql: SqlClient, value: Fragment): Fragment =>
  isPostgres(sql) ? sql`trunc(${value}) = ${value}` : sql`typeof(${value}) = 'integer'`
/**
 * Json valid.
 *
 * @category fragments
 * @since 1.0.0
 */
export const jsonValid = (sql: SqlClient, value: Fragment): Fragment =>
  isPostgres(sql) ? sql`${value} IS JSON` : sql`json_valid(${value})`
/** Scalar text extraction; paths are trusted SQL literals supplied by the store.
 * @category fragments
 * @since 1.0.0
 */
export const jsonText = (sql: SqlClient, value: Fragment, path: string): Fragment => {
  if (!isPostgres(sql)) return sql`json_extract(${value}, ${sql.literal(`'${path}'`)})`
  const parts = path.replace(/^\$\.?/, "").replace(/\[(\d+)\]/g, ".$1").split(".").filter(Boolean)
  return sql`(${value}::jsonb #>> ${sql.literal(`'{${parts.join(",")}}'`)})`
}
/**
 * Identity.
 *
 * @category fragments
 * @since 1.0.0
 */
export const identity = (sql: SqlClient): Fragment =>
  sql.literal(
    isPostgres(sql) ? "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" : "INTEGER PRIMARY KEY AUTOINCREMENT"
  )
/**
 * Tables.
 *
 * @category queries
 * @since 1.0.0
 */
export const tables = (sql: SqlClient) =>
  isPostgres(sql)
    ? sql<{ readonly name: string }>`SELECT tablename AS name FROM pg_tables WHERE schemaname = current_schema()`
    : sql<{ readonly name: string }>`SELECT name FROM sqlite_master WHERE type = 'table'`
/**
 * Columns.
 *
 * @category queries
 * @since 1.0.0
 */
export const columns = (sql: SqlClient, table: string) =>
  isPostgres(sql)
    ? sql<{ readonly name: string }>`SELECT column_name AS name FROM information_schema.columns
      WHERE table_schema = current_schema() AND table_name = ${table}`
    : sql<{ readonly name: string }>`PRAGMA table_info(${sql(table)})`
/** Creates a row trigger from trusted migration SQL, with one shared body.
 * @category migrations
 * @since 1.0.0
 */
export const trigger = (sql: SqlClient, options: {
  readonly name: string
  readonly table: string
  readonly event: string
  readonly when?: string
  readonly body?: string
  readonly reject?: string
  readonly ignore?: boolean
}) =>
  Effect.gen(function*() {
    const { name, table, event, when, body = "", reject, ignore } = options
    if (!isPostgres(sql)) {
      yield* sql.unsafe(`CREATE TRIGGER ${name} ${event} ON ${table}
      ${when ? `WHEN ${when}` : ""} BEGIN ${
        reject ? `SELECT RAISE(ABORT, '${reject}');` : ignore ? "SELECT RAISE(IGNORE);" : body
      } END`)
      return
    }
    yield* sql.unsafe(`CREATE OR REPLACE FUNCTION ${name}_fn() RETURNS trigger LANGUAGE plpgsql AS $trigger$
    BEGIN ${when ? `IF ${when} THEN` : ""}
      ${reject ? `RAISE EXCEPTION '${reject}' USING ERRCODE = '23514';` : ignore ? "RETURN NULL;" : body}
      ${when ? "END IF;" : ""}
      RETURN ${event.includes("DELETE") ? "OLD" : "NEW"};
    END $trigger$`)
    yield* sql.unsafe(`CREATE TRIGGER ${name} ${event} ON ${table} FOR EACH ROW EXECUTE FUNCTION ${name}_fn()`)
  })
/**
 * Drop trigger.
 *
 * @category migrations
 * @since 1.0.0
 */
export const dropTrigger = (sql: SqlClient, name: string, table: string) =>
  sql.unsafe(`DROP TRIGGER ${name}${isPostgres(sql) ? ` ON ${table}` : ""}`)
/** SQLite's query planner hint; PostgreSQL selects its own index.
 * @category fragments
 * @since 1.0.0
 */
export const indexHint = (sql: SqlClient, name: string): Fragment =>
  sql.literal(isPostgres(sql) ? "" : `INDEXED BY ${name}`)
/**
 * Greatest.
 *
 * @category fragments
 * @since 1.0.0
 */
export const greatest = (sql: SqlClient): Fragment => sql.literal(isPostgres(sql) ? "GREATEST" : "MAX")
/** SQLite tables expose an insertion ordinal implicitly; PostgreSQL declares it.
 * @category fragments
 * @since 1.0.0
 */
export const rowId = (sql: SqlClient): Fragment =>
  sql.literal(isPostgres(sql) ? "rowid BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE," : "")
/** Bind a generated query whose trusted template uses positional question marks.
 * Templates must not contain question marks in string literals.
 * @category queries
 * @since 1.0.0
 */
export const query = <A extends object = Record<string, unknown>>(
  sql: SqlClient,
  template: string,
  values: ReadonlyArray<string | number | null>
) => {
  let index = 0
  return sql.unsafe<A>(isPostgres(sql) ? template.replaceAll("?", () => `$${++index}`) : template, values)
}
